### ISSUE TITLE
How do I get the list of available functions when using qalc?

### ISSUE THREAD

**Issue by sixpointzero** [Qalculate/libqalculate#1]
I'm using `libqalculate` right now and I can't find a man page or a any information about the list of available functions when using `qalc`. Note that I'm not using the GTK version but the CLI version.

**Comment by hanna-kn** [comment]
A list of available functions, variables and units is not currently available in the CLI version. Until this has been implemented (I am not yet sure how to best present such a long list in the CLI), you will have to look in the manual of the GUI version (see Appendix A: http://qalculate.github.io/manual/qalculate-definitions-functions.html), as instructed in the text of the CLI 'help' command, or in the lists inside the GUI.

**Comment by sixpointzero** [comment]
You can list all the functions inside a man page.

**Comment by hanna-kn** [comment]
I have now added an option to display a list of all functions, variables or units.

**Comment by sixpointzero** [comment]
Thanks! You should release a new version if it's ready.
