### ISSUE TITLE
Failed to download exchange rates from ECB

### ISSUE THREAD

**Issue by Art-2** [Qalculate/libqalculate#100]
`$ qalc 1 USD to HNL`
`It has been 97 day(s) since the exchange rates last were updated.`
`Do you wish to update the exchange rates now? yes`
`error: Failed to download exchange rates from ECB: .`
`1 * dollar = approx. HNL 23.568`

**Comment by hanna-kn** [comment]
Which version of Qalculate! and operating system/distribution are you using?
Does `curl https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml` work (does it return a list of exchange rates in xml format)?
Is the directory ~/.local/share/qalculate present and writable?

**Comment by Art-2** [comment]
1. Qalculate 2.6.2
Xubuntu 18.04.1
2. Yes, it works.
3. Yes, I even manually download the eurofxref-daily.xml and placed it there but it does not update it

![imagen](https://user-images.githubusercontent.com/12375357/44866805-69a4e280-ac43-11e8-857a-6282aa5eacb0.png)
_Maybe I did not compile the program well_

**Comment by hanna-kn** [comment]
What character is it that the program fails to display correctly at the end of the error message?

Can you please try the following patch and post the error message you get when exchange rates are updated:
[100_error.patch](https://gist.githubusercontent.com/hanna-kn/2dea3abc9ffb420adf57cd5ce0276629/raw/1fd015f1c73b647e4675fbdd2c177b2cd26b070c/100_error.patch)
(apply with `patch -p1 < 100_error.patch` in the top directory in the libqalculate source)

Perhaps you could try the snap package and see if that works.

**Comment by Art-2** [comment]
I do not know an appropriate way to share the character because it changes here in GitHub to this: 

Tell me if I did it right
`:~/libqalculate-master$ patch -p1 < 100_error.patch`
`patching file libqalculate/Calculator.cc`

then:
`qalc 1 USD`
`It has been 98 day(s) since the exchange rates last were updated.`
`Do you wish to update the exchange rates now? yes`
`error: Failed to download exchange rates from ECB 2: Problem with the SSL CA cert (path? access rights?).`
`1 * dollar = approx. HNL 23.568`

Using Qalculate-gtk
1 USD = 1 × dollar
Failed to download exchange rates from ECB 1: .
≈ HNL 23.568

The problem is not present with the snap package but I do not want to have snap packages my system. :/

**Comment by hanna-kn** [comment]
The issue seems to be caused by a problem with libcurl and/or CA certificates on your system. I was able to reproduce the error by installing libcurl4-nss-dev instead of libcurl4-openssl-dev. 

The empty error message and the undisplayable character was caused by incomplete error handling (the curl error buffer is not always set when curl returns and error code and was not initialized).
