### ISSUE TITLE
Wrong uncertainty for Avogadro Constant

### ISSUE THREAD

**Issue by pmrv** [Qalculate/libqalculate#102]
The Avogadro Constant is defined with an error of 7.4e25, which is larger than the actual value. I guess it's just a typo as NIST[[1]](https://physics.nist.gov/cgi-bin/cuu/Value?na|search_for=avogadro) and others put the error at 7.4e15.

**Comment by hanna-kn** [comment]
The typo has now been fixed. 
All values and uncertainties of physical constants are taken from NIST.

**Comment by pmrv** [comment]
Cool, thanks for the quick fix.
