### ISSUE TITLE
Error in "convert to base units"

### ISSUE THREAD

**Issue by PetraBaum** [Qalculate/libqalculate#107]
When using the function "convert to base units", qalc converts kg to g, which is wrong. The SI base unit is kg. 

In this case, the result should be "1000kg×m/s²", but I either get this (which does not use base units) or something with Megagrams if i allow it to use prefixes.
![grafik](https://user-images.githubusercontent.com/11257079/46615642-05feb680-cb19-11e8-8ea8-08a2211a9486.png)

**Comment by hanna-kn** [comment]
kg as base is logically a bit problematic since it includes a prefix, now I've nevertheless fixed the issue in a hopefully acceptable way.

**Comment by PetraBaum** [comment]
Thanks, it's working as expected.
