### ISSUE TITLE
Recent regression

### ISSUE THREAD

**Issue by vvs-** [Qalculate/libqalculate#108]
This equation can't be solved anymore: `sin(x)cos(x)=cos(x)`.

P.S. Random tests won't catch such regressions, especially shortly before release.

**Comment by hanna-kn** [comment]
Fixed.

It's more difficult to find missing solutions then wrong solutions.

**Comment by vvs-** [comment]
Thanks!

That's exactly the point: the burden of finding missing solutions should lay on users, not on core developers. The core becomes too overweighted.
