### ISSUE TITLE
Approximation looks more "exact"

### ISSUE THREAD

**Issue by vvs-** [Qalculate/libqalculate#113]
In exact mode `(e^(2i))^(1/2)` is represented exactly this, without simplification. While in approximate mode with exponential complex format it is simplified to `e^i`.

Is there any particular reason for this behavior? Yes, I noticed other "nice" looking (-1)^(1/3) and know the difference, but why in above case?

**Comment by hanna-kn** [comment]
In approximate mode:
e^(2i) ≈ −0,41614684 + 0,90929743i
(−0,41614684 + 0,90929743i)^(1/2) ≈ 0,54030231 + 0,84147098i
arg(0,54030231 + 0,84147098i) ≈ 1

Qalculate! cannot reduce e^(2i) further in exact mode and does not know that (e^(2i))^(1/2) can be simplified to e^i. (a^b)^c can easily be simplified to a^(b*c) if a is positive (and in some other cases), and b and c are real. This is on most cases not true for complex b (e.g. (e^(4i))^(1/2) does not equal e^(2i)).

**Comment by vvs-** [comment]
> This is on most cases not true for complex b (e.g. (e^(4i))^(1/2) does not equal e^(2i)).

Yes, because its principal branch is `-e^(2i)`. But it's not _that_ different.

**Comment by hanna-kn** [comment]
(e^(a*i))^(1/2) equals e^(a/2*i) for -pi < a <= pi, and -e^(a/2*i) for pi < a <= 3pi (the sign changes every 2pi). 
This is only true for e as base and 1/2 as second exponent.

**Comment by hanna-kn** [comment]
> Other CASes which I've tried can simplify that case without trouble. But, if for some reason it's too problematic to process it specially, then this issue should be closed, I guess.

Maxima doesn't... 

I've now implemented simplification of (e^(a*i))^(b) when a and b are real numbers, and b equals 1/2 or abs(a) < pi.

**Comment by vvs-** [comment]
Thanks!

> Maxima doesn't...

It does it wrong, which surprised me. Wolfram Alpha does, I suppose it used Mathematica as a back-end. From what I've seen it might use polar form for intermediate calculations, because it's just a simple divide and trigonometric transformation.

**Comment by vvs-** [comment]
After investigating some more I found the algorithm, that Wolfram Alpha used for simplification of any root of complex number in exponential form. They don't use principal of the _root_ to calculate it, but they use principal of the _logarithm_ of that number instead. They reduce the angle to (-pi,pi] interval, so `ln((e^(16i))^(1/4))` becomes `i(1/4)(16-6pi)` and corresponding root is simplified to `ie^(4i)`.

So, it's arguable which form is "right". But this makes sense from a computational point of view.

**Comment by hanna-kn** [comment]
The algorithm has now been modified using (e^(a*i))^b = e^(ln(e^(a*i))*b).

**Comment by vvs-** [comment]
Thanks!

Works perfectly.
