### ISSUE TITLE
libqalculate 2.8.0 fails to build when readline is disabled

### ISSUE THREAD

**Issue by awilfox** [Qalculate/libqalculate#116]
qalc.cc line 1037 only defines `rcount` if `HAVE_LIBREADLINE` is defined.  7dd310e broke building without readline because the `rcount` variable is used unconditionally:

```
qalc.cc:2321:4: error: ´rcount´ was not declared in this scope
    rcount += 2;
    ^~~~~~
qalc.cc:3009:5: error: ´rcount´ was not declared in this scope
     rcount += 2; CHECK_IF_SCREEN_FILLED
     ^~~~~~
```

**Comment by hanna-kn** [comment]
Fixed (with commit 9398f8f70a98e731e29f58439bdc75faa554dd04).
