### ISSUE TITLE
RAID Calculator

### ISSUE THREAD

**Issue by majumeke** [Qalculate/libqalculate#118]
could you consider adding a function like the one found on this page https://www.servethehome.com/RAID/index.php into Qalculate! it would be helpful to be able to calculate how much space i'll be left with when i use a specific RAID level from within Qalculate! rather than open up a web page or a separate application.

**Comment by hanna-kn** [comment]
A RAID capacity calculation function has been implemented using the following expression
`if(\x=0,\z*\y,if(\x=1,if(\z>=2,\y,0),if(\x=2,if(\z>=3,(\z-log(\z+1,2))*\y,0),if(\x=3||\x=4||\x=5,if(\z>=3,(\z-1)*\y,0),if(\x=6,if(\z>=4,(\z-2)*\y,0),if(\x=10,if(\z>=4&&even(\z),\z/2*\y,0),if(\x=11,if(\z>=4,\z/\A{2}*\y,0),if(\x=16,if(\z>=8,(\A-2)*\y,0),if(\x=50,if(\z>=6,(\z-\A)*\y,0),if(\x=60,if(\z>=8,(\z-\A*2)*\y,0),0))))))))))`

**Comment by majumeke** [comment]
once again you are awesome! Thank You very much for implementing this.
