### ISSUE TITLE
Aliases for currencies

### ISSUE THREAD

**Issue by mnn** [Qalculate/libqalculate#12]
It is a bit cumbersome to convert to e.g. czech koruna. Sign isn't supported and code is accepted only as upper case which is not so comfortable to write. (All those $2 outputs are incorrect.)
```
qalc -t 2$ to czk
$2

qalc -t 2$ to CZK
CZK 48.959957

qalc -t 2$ to Kč
$2

qalc -t 2$ to Kc
$2

qalc -t 2$ to kc
$2
```
Also full name seems to be missing:
```
qalc -t 2 DOLLAR to EURO
EUR 1.8119224

qalc -t 2$ to CZECH KORUNA
7.751938((u$*A*C*EC*H*K*N*R*s) / (MA^2 * K*g*m^3))

qalc -t 2$ to CZECHKORUNA
7.751938((u$*A*C*EC*H*K*N*R*s) / (MA^2 * K*g*m^3))

qalc -t 2$ to CZECH_KORUNA
7.751938((u$*A*C*EC*H*K*N*R*s) / (MA^2 * K*g*m^3))

qalc -t 2$ to CZECH KORUNY
7.751938((n$*C*EC*H*K*N*R*s) / (GA*K*g*m^3))

qalc -t 2$ to CZECHKORUNY
7.751938((n$*C*EC*H*K*N*R*s) / (GA*K*g*m^3))

qalc -t 2$ to CZECH_KORUNY
7.751938((n$*C*EC*H*K*N*R*s) / (GA*K*g*m^3))
```

I noticed that some currencies are way better with tons of synonyms and support of sign. E.g. dollar or euro:
```
qalc -t 2 dollars to euros
EUR 1.8119224

qalc -t 2$ to €
EUR 1.8119224
```

It would be nice to have other currencies supported as well (not just CZK).

**I think full name is not that important, but a currency sign is nice-to-have and a currency code in lower case is IMO a must.**

**Comment by hanna-kn** [comment]
I have now added Kč as symbol. 
I need to do some more thinking before making any additional changes.

The full name is a bit to long and needs an underscore and "koruna" might also refer to SKK.

I have previously decided against lower case currency codes to avoid confusion with the many other units, unit combinations and prefixes.

**Comment by mnn** [comment]
Yeah, you are right, there is so many currencies and lower case versions of them would cause a lot of unintended usages. I am not sure, it might be already possible, I am only a bit familiar with this project's GUI - but solution might be to let user define few aliases he uses - e.g. "kc" as alias to CZK.

**Comment by hanna-kn** [comment]
It is possible for the user to change almost any unit in any way (including adding "aliases") using the GUI.

Additional names and symbols for local currencies should ideally be added to (some) translations. The Swedish translation adds "kr", "krona" and "kronor" as aliases/alternative names for SEK.

**Comment by mnn** [comment]
Oh, didn't know it is possible. Found it, thank you for help :).

Since user can add an alias and it's also possible to do it via translations, I think I can close this as resolved, because in my opinion adding lower case codes would severely cripple applications usability.

**Comment by mnn** [comment]
It didn't occur to me until recently - in Slovakia is no longer used koruna as a currency, they switched to euro quite some time ago.

> Slovakia switched its currency from the koruna to the euro on 1 January 2009, at a rate of 30.1260 korunas to the euro.

https://en.wikipedia.org/wiki/Slovak_koruna
