### ISSUE TITLE
Lakh and crore support

### ISSUE THREAD

**Issue by GitterHubber** [Qalculate/libqalculate#120]
In the Indian system 

100,000 is denoted by lakh and (hundred thousand)
100 lakhs is denoted by crore (10 million)

Is it possible for a user to to configure Qalculate! to show these?

**Comment by GitterHubber** [comment]
Ok, thanks that works out pretty well.
When is the next version scheduled for release?
If I download the git version, would I need to build the windows executed using visual studio? Or are there prebuilt versions available?

**Comment by hanna-kn** [comment]
The are no release schedule. My best guesstimate is that I will release the next version 2019-02-04.
The Windows executable is built using MinGW (Visual Studio is only for the installer).
No prebuilt Git version is available.
