### ISSUE TITLE
How does for() work?

### ISSUE THREAD

**Issue by FauxFaux** [Qalculate/libqalculate#124]
I can't get the `for()` function to do anything.

I would expect a construction like `for(1; x; x<10; x=x+1; 2; y=y+1; y)` to run like a C for loop? `int y = 2; for (int x = 1; x < 10; ++x) { y++; }`.

The only behaviours I'm able to get are that it returns the "initial value" (2 in this example), or it computes "forever".

Can you please give me a working example of `for()`? I tried reading the code, but I am lost where it reassigns `mstruct = mupdate`, and how it can be updating variables.

https://github.com/Qalculate/libqalculate/blob/ed3d0c0d9753ad793916bca42d90894a550367b9/libqalculate/BuiltinFunctions.cc#L4907

Arguments:

> 0: initial counter
> 1: counter var
> 2: condition
> 3: update function
> 4: initial value
> 5: do function
> 6: variable
>

**Comment by hanna-kn** [comment]
The above example should be entered as `for(1; x; x<10; x+1; 2; y+1; y)` (or `2+sum(1, 1, 9)`). Assignment is automatic, and '=' is used for comparison, not assignment.

I've now added a for() example, and implemented handling of incorrect use of '=' in for().

**Comment by FauxFaux** [comment]
That example is great. Thanks!
