### ISSUE TITLE
Feature request: two's complement for hexadecimal

### ISSUE THREAD

**Issue by detly** [Qalculate/libqalculate#128]
If I want the binary two's complement representation of a negative number, that's easy, it's done by default. But the hexadecimal representation is also quite handy eg. when comparing with hex dumps. It would be nice to have a display option or function to do this. (Most handy for me would be the ability to just display it with a word size that I set, but I don't know what the most sensible way for you to do this would be.)

**Comment by hanna-kn** [comment]
Option to use two's complement for hexadecimal numbers has now been implemented in the same way as for binary numbers—a second boolean argument in hex() for input and output using automatic word size, activated using `set hextwos 1` in CLI or from the preferences dialog (default off).

**Comment by hanna-kn** [comment]
I should also mention that it is really easy to convert to and from two's complement, using 2^(word size)+x and x-2^(word size) (e.g. 2^8 - 30 = 2^8 - 0x1E = 0xE2 and 0xE2 - 2^8 = -0x1E = -30). You can create a function for conversion to two's complement in qalc using `function twos 2^\y+\x` (usage: twos(-52;x) to hex = 0xE2).

**Comment by detly** [comment]
Arg, I should have realised that, since I've spent the last week reading all about how C does this on casting. Thanks for adding a quicker way though!
