### ISSUE TITLE
The same code inside and many others

### ISSUE THREAD

**Issue by tigertv** [Qalculate/libqalculate#129]
https://github.com/Qalculate/libqalculate/blob/8e9578eddd98a26e3d9032670e3ae55ee2f5984c/libqalculate/Number.cc#L4015-L4021

Also, see https://www.viva64.com/en/b/0616/

**Comment by hanna-kn** [comment]
Fixed.

Most listed errors were harmless or affected very unusual use cases. The most critical error was only present in unreleased code and had already been fixed. The example above in Number.cc resulted in a potentially too narrow interval when calculating the square of a complex interval with different sign for upper and lower endpoint.
