### ISSUE TITLE
Compile fails 

### ISSUE THREAD

**Issue by luudee** [Qalculate/libqalculate#132]
CentOS Linux release 7.6.1810 (Core)
Linux cpu11 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

QalculateDateTime.cc: In member function 'std::string QalculateDateTime::toLocalString() const':
QalculateDateTime.cc:533:14: error: 'INT_MAX' was not declared in this scope
  if(i_year > INT_MAX || i_year < INT_MIN + 1900) return toISOString();
              ^
QalculateDateTime.cc:533:34: error: 'INT_MIN' was not declared in this scope
  if(i_year > INT_MAX || i_year < INT_MIN + 1900) return toISOString();
                                  ^
QalculateDateTime.cc: In member function 'bool QalculateDateTime::addMonths(const Number&)':
QalculateDateTime.cc:835:96: error: 'LONG_MAX' was not declared in this scope
  if(i_year > 0 && months > 0 && (unsigned long int) months / 12 + i_year > (unsigned long int) LONG_MAX) return false;
                                                                                                ^
QalculateDateTime.cc:836:99: error: 'LONG_MAX' was not declared in this scope
  if(i_year < 0 && months < 0 && (unsigned long int) (-months / 12) - i_year > (unsigned long int) LONG_MAX) return false;
                                                                                                   ^
QalculateDateTime.cc: In member function 'bool QalculateDateTime::addYears(const Number&)':
QalculateDateTime.cc:910:89: error: 'LONG_MAX' was not declared in this scope
  if(i_year > 0 && years > 0 && (unsigned long int) years + i_year > (unsigned long int) LONG_MAX) return false;
                                                                                         ^
QalculateDateTime.cc:911:92: error: 'LONG_MAX' was not declared in this scope
  if(i_year < 0 && years < 0 && (unsigned long int) (-years) - i_year > (unsigned long int) LONG_MAX) return false;
                                                                                            ^

**Comment by hanna-kn** [comment]
Fixed.
