### ISSUE TITLE
libidn2-4.dll Again

### ISSUE THREAD

**Issue by BugZappr** [Qalculate/libqalculate#133]
I just downed qalculate-3.0.0-i386.msi.  I installed it on Win7 SP1 Home, and I went to run Qalculate.  I got an error "This program can't start because libidn2-0.dll is missing from your computer."  I noticed that I had a libidn2-4.dll in the Qalculate directory, and renamed it libidn2-0.dll.  It started fine, then.

**Comment by hanna-kn** [comment]
Fixed.
