### ISSUE TITLE
Conversion from pascals to pounds-force per sq inch broken

### ISSUE THREAD

**Issue by pkail** [Qalculate/libqalculate#134]
120 pascal to lbf_p_sqin = 1062.0895 (in×lbf) ∕ m^3.

I apologise if I there is a setting which I have missed.

**Comment by hanna-kn** [comment]
There are no unit with the name 'lbf_p_sqin' (or more correctly there are a 'composite unit' with that name, but composite unit names cannot be used directly in expressions). You should use lbf/in^2 (or any equivalent expression) or psi.
`120 pascal to lbf/in^2 ≈ 0.01740452853 lbf / in^2`
`120 pascal to psi ≈ 0.01740452853 psi`

**Comment by pkail** [comment]
Thanks very much!
