### ISSUE TITLE
Feature request: uptime variable

### ISSUE THREAD

**Issue by peterzuger** [Qalculate/libqalculate#136]
Today I wanted to do the calculation:

    uptime - now

an realized that the variable ```uptime``` does not exist.

The same result can be achieved in sh with

    uptime --since

But maybe introducing a variable for uptime would still be helpful.

**Comment by hanna-kn** [comment]
I am not sure if an uptime variable really belongs in a calculator. It would require a different implementation for each platform. One would also reasonably expect a lot of other system information to be available, if there is a uptime variable.

This gives me two ideas:
- A GNU/Linux exclusive sysinfo() function which returns the information available in the sysinfo struct (e.g. `sysinfo(uptime)` would return uptime in seconds), and possibly more.
- A function returning the output of an external command (e.g. `command(uptime -s)` would returning the date and time of the last reboot on GNU/Linux, and the user could easily create the variable you are requesting using this command). This would probably not work well if using the snap package.

**Comment by peterzuger** [comment]
I had some time today and implemented it.
sort of ... https://github.com/peterzuger/libqalculate/commit/5d6b29315adffd00ebcd59cee4616ffbb8c6c629
I tested it on linux but i don't have a mac/windows/bsd machine to test.

The problem is that this variable returns this:

    > uptime
        uptime = "1970-01-03T02:42:01"
    > 

Instead of just the absolute time.

I do like the idea of the sysinfo() function though. Might be easier to maintain.
If there is real interest in the sysinfo() function I can try to implement it, if not, 
I don't really need ```uptime```, just wanted to get the idea out there. :)

**Comment by hanna-kn** [comment]
QalculateDateTime should probably not be involved at all. The variable should just return the uptime in seconds.

This is how I would implement it on Linux (not tested):
```
void UptimeVariable::calculate(MathStructure &m) const {
      struct sf;
      long int uptime = 0;
      if(sysinfo(&sf)) m.set(sf.uptime);
      Unit *u = CALCULATOR->getUnit("s");
      if(u) m *= u;
}
```

The uptime will then, in default mode, be presented in days, hours, minutes and seconds (and be converted to planck time or anything less random), and "now - uptime" will return a date.

With the functions for uptime retrieval on different platforms, I can quickly implement it myself.

The question is how to best handle this type of data. A lonely uptime variable appears a bit random.

**Comment by peterzuger** [comment]
Well I just copied the code from ```now``` :).
I have updated my test : https://github.com/peterzuger/libqalculate/commit/54bbe44bbd09e73272e1da89c69c14740de6ce37
If you can use my ```uptime``` functions that would be great.
I don't really know what would be best, feel free to use or not use as much as you want.

**Comment by hanna-kn** [comment]
I have now added the uptime variable. I used a simplified version of your code, avoiding library interface changes. Since I am unable to test platforms other than GNU/Linux and Windows, I only added code for those.

**Comment by peterzuger** [comment]
this is perfect.
cloned - compiled and tested works perfectly
thank you very much :)

**Comment by hanna-kn** [comment]
The fact that the result of now - uptime differs one second between calculations (often one second before the value returned by uptime -s) is primarily because of how seconds are rounded. "now" is probably truncated (using time(NULL)), sysinfo.uptime seems to be rounded upwards, and the final time is rounded to the nearest second. I have now hopefully fixed this by using gettimeofday() for "now" and /proc/uptime (when available) for uptime.

**Comment by peterzuger** [comment]
The diffeence of +-1 second was not the thing I ment.
I was thinking:   why does the result of ```now - uptime``` not change ?
Which is obvious... now that I'm not in *no-thinking* mode anymore.
```now - uptime``` is the time I started my OS which obviously doesn't change.

But the improved precision is nice !
Tested it and it does not jump around anymore :).
