### ISSUE TITLE
Decibel conversion

### ISSUE THREAD

**Issue by markus-k** [Qalculate/libqalculate#138]
libqalculate doesn't seem to support unit conversion like [dBm](https://en.wikipedia.org/wiki/DBm) to Watt. Entering "20 dBm to mW" should result in 100mW, but instead results in "2 (B×mW×s^3) ∕ (g×m)".

**Comment by hanna-kn** [comment]
The decibel-milliwatts unit is not currently included. dBm is therefore interpreted as decibel*meter.

You can add dBm to Qaclulate by copying https://gist.githubusercontent.com/hanna-kn/2bfc179e61addd9b88938547f303926b/raw/47acccb19a8c5138af9fe93b22dafbcad49a411a/dBm.xml to your local data directory (~/.local/share/qalculate/ on GNU/Linux).
