### ISSUE TITLE
Misspelling of "therefore" in source code

### ISSUE THREAD

**Issue by RogueScholar** [Qalculate/libqalculate#139]
This is exceedingly trivial to mention within such an amazing piece of software as is Qalculate, but I thought you might like to know that I believe there are several instances of the English word "therefore" that are misspelled as "therefor" within the files `/libqalculate/BuiltinFunctions.cc` and `/po/libqalculate.pot`. I am aware that "therefor" used to be an accepted spelling of the word, but all of the most recent editions of the leading English dictionaries now deem that spelling as archaic, except in legal parlance where the nuances of interpretations of the word in old documents may require its usage.

Thanks for all your hard work on this remarkable program.

**Comment by hanna-kn** [comment]
Thanks. Fixed.
