### ISSUE TITLE
How does currency conversion work with libqalculate?

### ISSUE THREAD

**Issue by dschopf** [Qalculate/libqalculate#140]
When I try to do currency conversion using libqaculate it never accepts my input as a currency. Instead it interprets the individual letters as variables and returns something unusable.

Here is a simplified example of my code:
```
#include <iostream>
#include <memory>

#include <libqalculate/qalculate.h>

void test(std::unique_ptr<Calculator>& c) {
  MathStructure result;
  EvaluationOptions opt;
  opt.local_currency_conversion = true;
  const bool res = c->calculate(&result, "1 dollar", 100, opt);
  std::cout << "res = " << result << "\n";
}

int main() {
 auto c = std::make_unique<Calculator>(new Calculator());
 c->loadGlobalDefinitions();
 c->loadLocalDefinitions();
 c->loadExchangeRates();
 c->fetchExchangeRates();
 auto t = c->getExchangeRatesTime();
 std::cout << "getExchangeRatesTime = " << asctime(gmtime(&t));
 std::cout << c->calculateAndPrint("1 dollar") << "\n";
 test(c);
 return 0;
}
```

The output is the following:
```
$ ./a.out                                                             
getExchangeRatesTime = Sun Jul 21 08:50:02 2019
0.0001 'o' 'r' d*m^8
res = ('o' 'r' d*m^8) / 10000
```

Do I need to set some special options to make it recognize "dollar" as $? It works for the `qalc` command line tool as well as for the gtk version.

**Comment by hanna-kn** [comment]
You need to call loadCurrencies() after loadExchangeRates() (I suggest that you simply call loadExchangeRates before loadGlobalDefinitions). I will update to API docs with this information.

**Comment by dschopf** [comment]
Hmm, I cannot find a function in the source code which is called loadCurrencies() for any object. Did you mean to write loadGlobalCurrencies()? At least after calling that function I get a currency returned for the same input.

Another somehow related question would be if it is possible to somehow set the default currency which inputs are converted into? Am I correct in the assumption that this is always converted into the locale?

**Comment by hanna-kn** [comment]
Yes, I meant loadGlobalCurrencies()? The currency definitions are however loaded by loadGlobalDefinitions(), so it's more efficient to simply call loadExchangeRates() before loadGlobalDefinitions() instead.

> Another somehow related question would be if it is possible to somehow set the default currency which inputs are converted into? Am I correct in the assumption that this is always converted into the locale?

The local currency is read from localeconv()->int_curr_symbol.

Options to convert to a different currency:
- Change the locale using `setlocale(LC_MONETARY, ...)`
- Append " to [currency code]" to the expression.
- Use one of the convert() functions

**Comment by hanna-kn** [comment]
I've now added Calculator::setLocalCurrency() (`c->setLocalCurrency(c->getActiveUnit("EUR"))`)

**Comment by dschopf** [comment]
Thanks, that's actually pretty useful. I will add it to the Plasma Applet.

Is there also a function which would return all possible currencies? Or should I just ask the user for a string and then call getActiveUnit and check the return value for what exactly? Null? IsCurrency?

**Comment by hanna-kn** [comment]
> Is there also a function which would return all possible currencies?

Use Calculator::units, which is a vector containing all units (I know that class variables should ideally not exposed and used like this, but that's how it has been since the first versions). Use Unit::isActive() and Unit::isCurrency() on each unit.

> Or should I just ask the user for a string and then call getActiveUnit and check the return value for what exactly? Null? IsCurrency?

```
Unit *u = CALCULATOR->getActiveUnit(UNIT_NAME);
if(u && u->isCurrency()) ...
```

**Comment by dschopf** [comment]
I finally managed to implement the currency support in the KDE plasma applet. Thanks for your help.
