### ISSUE TITLE
qalc man page

### ISSUE THREAD

**Issue by vlegout** [Qalculate/libqalculate#142]
Hello,

In Debian we ship a manpage for qalc. Would you be interested in adding it to libqalculate?

https://sources.debian.org/src/libqalculate/3.3.0-1/debian/qalc.1/

We also have one for qalculate-gtk:

https://sources.debian.org/src/qalculate-gtk/2.8.2-1/debian/qalculate-gtk.1/

Thanks,
Vincent

**Comment by hanna-kn** [comment]
I will use these as templates for creating more up-to-date man pages.

**Comment by hanna-kn** [comment]
Man pages has now been added for qalc (https://github.com/Qalculate/libqalculate/blob/master/man/qalc.1) and qalculate-gtk (https://github.com/Qalculate/qalculate-gtk/blob/master/data/qalculate-gtk.1).
