### ISSUE TITLE
Not getting a result for `185×9.81÷(38^2×pi×.25)`

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/libqalculate#145]
I'm using Q! 3.3.0 on Windows 10 x64.

I have this formula: `P = F ÷ A`. `F = 1850 kN` (or 185t). `A = d^2*pi*.25 | d = 38 mm`
`185×9.81÷(38^2×pi×.25)`
and all I want is a result. I typed it in google and got what I wanted - Q! does nothing (see first image).

Then, I tried this, without success:
`1850kN÷((38mm)^2×pi×.25) to MPa`
It does work on Wolframalpha: https://www.wolframalpha.com/input/?i=1850kN%C3%B7((38mm)%5E2%C3%97pi%C3%97.25)+to+MPa
SpeedCrunch has no issue with `185*9810/(38^2*pi*.25)`

Then I found this:
`9.81×185` = nothing!
....
`9.81×100` = 981 whaaaaa?!?!
`9.81×101` = 990.81 yay!
`9.81×102` = nothing?!?!
What am I doing wrong?

(Not even RPN can handle this: `9.81 185 ×`)

------

![image2](https://user-images.githubusercontent.com/10420187/62758321-54088180-ba7e-11e9-90e8-a4a80282016a.png)
Not what I expected!

![image2](https://user-images.githubusercontent.com/10420187/62756937-d8a4d100-ba79-11e9-9ee0-bde80d3dd413.png)
The result should be ~ 1630 MPa.

![image](https://user-images.githubusercontent.com/10420187/62757455-ad22e600-ba7b-11e9-8103-a6d8c4eee0b1.png)
What is going on?!

![image](https://user-images.githubusercontent.com/10420187/62757663-59fd6300-ba7c-11e9-9f07-416e7b474151.png)
Oh, no! Not you too, RPN!

**Comment by foreachthing** [comment]
Ok, I've found something: I get a result if I disable EXACT.
So ... If there is not an EXACT result, I'll get none?! Is this desired?

**Comment by hanna-kn** [comment]
That is not the normal behaviour.

<img width="359" alt="screenshot" src="https://user-images.githubusercontent.com/19703699/62777682-7e723300-baae-11e9-91c5-b525f9ce9ea7.png">

Please try the following:
- calculate `1/x`
- disable digit grouping (under Numbers & Operator in Edit->Preferences)
- completely remove (program directory and settings) and reinstall Qalculate!, or download the "portable" version (https://github.com/Qalculate/libqalculate/releases/download/v3.3.0/qalculate-3.3.0-i386.zip)

**Comment by hanna-kn** [comment]
This is likely caused by the use of 0xA0 (non-Unicode non-breaking space) as thousands separator.

**Comment by foreachthing** [comment]
Thanks for your reply.
Well, if I set the "Digit grouping" back to standard it works.
... [few minutes later] ... after I checked my Windows settings (Region -> Customize Format -> Numbers), I've found that there was _no_ digit grouping symbol set. So I set one. After restarting Q! it works with the "local" setting (exact and approx)!
Thanks for you support!
