### ISSUE TITLE
How to evaluate an expression for given values?

### ISSUE THREAD

**Issue by s-leroux** [Qalculate/libqalculate#147]
Hi Hanna and the other (possibly 0?) Qalculate devs. Congratulation for the work on Qalculate. I use Qalculate GTK for years now and except for few special circumstances where I log in to Wolfram Alpha, I wouldn't recommend any other calculator for day to day usage.

I searched through [the manual](https://qalculate.github.io/manual/index.html) but I can't find a way to evaluate an expression for the given value of an argument. For example, given the `x+y` expression, how to evaluate it for `x=1` and `y=2`?

I tried the obvious `x=1;y=2;x+y` (which [works in Wolfram Alpha](https://www.wolframalpha.com/input/?i=x%3D1;y%3D2;x%2By) ;), but it doesn't work in Qalculate since the `=` symbol is taken here as the comparison operator.

**Comment by s-leroux** [comment]
By looking deeper into the doc, I found the [Replace](https://qalculate.github.io/manual/qalculate-definitions-functions.html#qalculate-definitions-functions-1-Utilities) function. It looks like it was inspired from the [Wolfram Language Replace function](https://reference.wolfram.com/language/ref/Replace.html). But it becomes cumbersome to use when you have several replacement rules:

```
Replace(Replace((x+y); x; 1); y; 2)
```

The Wolfram Language has the [ReplaceAll function](https://reference.wolfram.com/language/ref/ReplaceAll.html) but I don't see how we could write a Qalculate function accepting an arbitrary number of mapping rules.

As an alternate solution, we could add a little bit of syntactic sugar on top of expressions to allow a more compact writing for nested `Replace` functions. Maybe something along the lines of:

```
x+y \. x=1; y=2
```
or
```
x+y where x->1; y->2
```

With your help, I could try to implement those changes myself.

**Comment by hanna-kn** [comment]
In recent versions, replace() accepts vectors as arguments:
`replace(x+y;[x;y];[1;2])`

alternative variant:
```
x+y
replace ans;x;1
replace ans;y;2
```

In qalculate-gtk you can use "Set Unknowns…" (in result context menu, Edit menu, "x=" button menu).

I would probably prefer the following syntaxes:
`x+y where x=1; x=2`
`x+y where x=1 and x=2`

**Comment by hanna-kn** [comment]
I've now begun implementation of "where" syntax. Currently `x+y where x=1 and x=2` is supported. "to" can also be used. I see no reason for not supporting "\." or "/." as a shortcut for "where".

The "where" syntax should also support expressions such as `x^2=4 where x>0`.

**Comment by s-leroux** [comment]
Hey @hanna-kn, all that seems quite interesting. I initially planed to take a look at that this WE. I had no idea you will take the time to work on that issue by yourself. Thanks a lot.

Concerning your implementation, how will it work with respect to values with units/`to` conversions?

```
x+y to kg where x=2g and y=1t
```

As a side question, while writing this I wonder if the new clause should be  name `where` or `with`. What is the most idiomatic in English?

- `x+y where x=1 and y=2`
- `x+y with x=1 and y=2`

**Comment by hanna-kn** [comment]
> Concerning your implementation, how will it work with respect to values with units/to conversions?

Currently "to" must be placed after "where" (e.g. `x+y where x=2g and y=1t  to kg`).

> As a side question, while writing this I wonder if the new clause should be name where or with. What is the most idiomatic in English?

English is not my native language, but "where" definitely feels better, especially for expression such "x^2=4 where x>0" ("with x is greater than" feels weird) and Google seems to agree (when comparing the number of search hits). It is of course possible to support both "where" and "with".

**Comment by s-leroux** [comment]
> It is of course possible to support both "where" and "with".
No, no need to add more keywords than necessary. You have good arguments in favor of _where_.

> expression such `x^2=4 where x>0`
Will this be supported? It looks more something we could see in the context of a solver rather than for expression transformations as I imagined it initially.
