### ISSUE TITLE
How to set qalc "numerical display mode" to "simple"?

### ISSUE THREAD

**Issue by jaimet** [Qalculate/libqalculate#149]
Hi.

I want to see the "full result" (all digits) of 123456789*987654321. If I install qalculator and perform this calculation, I see the result:

≈1.2193263x10↑17

Then I press the "Mode" button, then the "Numerical display" button and choose "Simple". Then I see:

=121 932 631 112 635 269

This is what I want to see. Then I try the same thing in qalc. I enter:

123456789*987654321

and the result appears:

123456789 * 987654321 = approx. 1.2193263E17

I want to change the "Numerical display" mode to "Simple", but entering "mode simple" does not do what I want it to do, neither does "set mode simple". I see that there is a "scientific notation (exp)" option, but according to the output from "help set", that option appears to have the following possible values:

```
off
auto
engineering
pure
scientific
>= 0
```

Is qalculator "numerical display mode" "simple" the same as qalc "scientific notation (exp)" option "off"?

Thank you.

**Comment by hanna-kn** [comment]
> Is qalculator "numerical display mode" "simple" the same as qalc "scientific notation (exp)" option "off"?

Yes. ("Simple" mode in GUI also disables negative exponents and places negative values last in polynomials.)

**Comment by jaimet** [comment]
Aah! I think I understand a bit better now. So does that mean that "Simple" mode is something that only applies to the GUI (i.e. qalc has no "Simple" mode)? Also, are the GUI's "numerical display modes" just collections (groups) of options?

**Comment by s-leroux** [comment]
> Also, are the GUI's "numerical display modes" just collections (groups) of options?

It seems to be the case. From https://raw.githubusercontent.com/Qalculate/qalculate-gtk/master/src/callbacks.cc line 13226 and following:

```
void on_combobox_numerical_display_changed(GtkComboBox *w, gpointer) {
	switch(gtk_combo_box_get_active(w)) {
		case 0: {
			printops.negative_exponents = false;
			printops.sort_options.minus_last = true;
			gtk_check_menu_item_set_active(GTK_CHECK_MENU_ITEM(gtk_builder_get_object(main_builder, "menu_item_display_normal")), TRUE);
			break;
		}
		case 1: {
			gtk_check_menu_item_set_active(GTK_CHECK_MENU_ITEM(gtk_builder_get_object(main_builder, "menu_item_display_engineering")), TRUE);
			break;
		}
		case 2: {
			printops.negative_exponents = true;
			printops.sort_options.minus_last = false;
			gtk_check_menu_item_set_active(GTK_CHECK_MENU_ITEM(gtk_builder_get_object(main_builder, "menu_item_display_scientific")), TRUE);
			break;
		}
		case 3: {
			printops.negative_exponents = true;
			printops.sort_options.minus_last = false;
			gtk_check_menu_item_set_active(GTK_CHECK_MENU_ITEM(gtk_builder_get_object(main_builder, "menu_item_display_purely_scientific")), TRUE);
			break;
		}
		case 4: {
			printops.negative_exponents = false;
			printops.sort_options.minus_last = true;
			gtk_check_menu_item_set_active(GTK_CHECK_MENU_ITEM(gtk_builder_get_object(main_builder, "menu_item_display_non_scientific")), TRUE);
			break;
		}
	}

/* ... */
```

As you can see, the simple mode (case 4) also set both the `negative_exponents` option to false and the `minus_last` option to true:


FWIW, while looking qt the code, I also noticed Qalculate-gtk does some custom output formating in the `improve_result_text` function (around line 649), so I'm not sure you can obtain the exact same output with the `qalc` command line tool.

**Comment by hanna-kn** [comment]
> Aah! I think I understand a bit better now. So does that mean that "Simple" mode is something that only applies to the GUI (i.e. qalc has no "Simple" mode)? Also, are the GUI's "numerical display modes" just collections (groups) of options?

This is only true for the numerical mode selection in menu (combo box) above the keypad (below the result) and in the context menu. The menu items (in the menu bar) only change when scientific notation is used. 

> FWIW, while looking at the code, I also noticed Qalculate-gtk does some custom output formating in the improve_result_text function (around line 649), so I'm not sure you can obtain the exact same output with the qalc command line tool.

That function only does some text formatting (italics and subscript) for history output. The output is similarly formatted in qalc (but without subscript).

**Comment by hanna-kn** [comment]
> is there a function to force simple mode output?
> 
> e.g.:
> 
> ```
> $ qalc "100 kWh to watt"
> 100 * kilowatt * hour = 3.6E8 W*s
> 
> $ qalc "simple(100 kWh to watt)"
> 100 * kilowatt * hour = 360 Ms  # i'd like to get this instead
> ```

For explicit unit conversion you have to either specify a prefix or prepend the unit expression with a question mark (e.g. `100 kWh to ?W` or `100 kWh to Ms`).

The use of scientific notation is controlled by the "exp" setting (to completely disable scientific notation use `set exp 0` within qalc, or add `-s "exp 0"` to the command line).  This does however not affect the use of prefixes.

**Comment by eadmaster** [comment]
when i pass `-s "exp 0"` i get this error:
````
$ qalc -s "exp 0" "factorial(20)"
Unrecognized option.
factorial(20) ≈ 2.432902008E18
````

**Comment by hanna-kn** [comment]
> when i pass `-s "exp 0"` i get this error:
> 
> ```
> $ qalc -s "exp 0" "factorial(20)"
> Unrecognized option.
> factorial(20) ≈ 2.432902008E18
> ```
 
If you are using an old version (< 2.8.2) you'll have to use the longer version of the option: `qalc -s "exp mode 0"` (or `qalc -s "exp mode off"`).

> This also does not work:
> 
> ```
> qalc "set exp 0 ; factorial(20)"
> ```

That kind of expressions (multiple expressions/commands separated by semicolon) are not supported.

**Comment by jaimet** [comment]
My apologies - I've just realised that I should have closed this bug some time ago!

**Comment by sergeevabc** [comment]
Dear fellows,
can you tell me how to get the light year in kilometers, but expressed shorter?

Right now there is

``` console
$ qalc "1 lightyear to kilometer"
1 lightyear = approx. 9460730472581 km
```

But what I'm looking for is `9.46×10^12` or '9.46E12'.

**Comment by sergeevabc** [comment]
@hanna-kn, is there a way to pass all three preferences in a single `set` statement?

``` console
$ qalc -s "exp 1" -s "maxdeci 2" -s "lowe" 1 ly to km
1 lightyear = approx. 9,46e12 km

$ qalc -s "exp 1; maxdeci 2; lowe" 1 ly to km
Illegal value.
```

And is there a flag to get output as `9.46×10^12` so that I don't have to explain to the recipient that in the case of `e` they have to multiply by 10 with so many zeros?

**Comment by hanna-kn** [comment]
> is there a way to pass all three preferences in a single set statement?

I've now added support for passing multiple options separated by semicolon. An alternative is to add set commands to a file and pass it on the command line using `-f FILE`.

> And is there a flag to get output as 9.46×10^12 so that I don't have to explain to the recipient that in the case of e they have to multiply by 10 with so many zeros?

Not in qalc (the GUIs by default uses ×10¹² instead of E12). It is possible to force qalc to return 9.46×10^12 using `to 10^12 km`, but I doubt that it is in acceptable solution.

**Comment by sergeevabc** [comment]
>  It is possible to force qalc to return 9.46×10^12 using to 10^12 km,
but I doubt that it is in acceptable solution.

Dear Hanna, what do you mean?

``` console
$ qalc -s "maxdeci 2" 1 ly to 10^12 km
1 lightyear = approx. 1012 * 9348547898 km
                                  
                      hmm, does not look like 9,46×10^12
```

**Comment by hanna-kn** [comment]
> ```
> $ qalc -s "maxdeci 2" 1 ly to 10^12 km
> 1 lightyear = approx. 1012 * 9348547898 km
>                                   
>                       hmm, does not look like 9,46×10^12
> ```

It seems as if you are using a terminal (e.g. Windows command prompt) which requires use of quotation marks for expressions with `^`.

**Comment by sergeevabc** [comment]
You're right, Hanna. I work under Windows 7 x64. Also `^^` is possible here.

``` console
$ qalc -s "maxdeci 2" "1 ly to 10^12 km"
1 lightyear = approx. 9,46 * 10^12 * km

$ qalc -s "maxdeci 2" 1 ly to 10^^12 km
1 lightyear = approx. 9,46 * 10^12 * km
```
The only thing that confuses me about the result is the presence of the 2nd asterisk.
I expected `1 lightyear = approx. 9,46 * 10^12 km`.

**Comment by hanna-kn** [comment]
@sergeevabc
I've now added `e notation` option in qalc (https://github.com/Qalculate/libqalculate/commit/b12d51a29d4250a729ac5f46d44936b3d80c38a4):
```
qalc -s "e notation 0; exp 1; maxdeci 2" 1 ly to km
1 lightyear ≈ (9.46 × 10^12) km
```
(I will fix the superfluous parentheses)

**Comment by sergeevabc** [comment]
> @hanna-kn
> qalc -s "e notation 0; exp 1; maxdeci 2" 1 ly to km
> 1 lightyear ≈ (9.46 × 10^12) km

I have just updated Qalc from 4.8.1 to 5.5.2 on Windows 7 x64. Let's see if it works.

``` console
$ qalc -s "e notation 0; exp 1; maxdeci 2" 1 ly to km

Unrecognized option.
Did you mean "ic" (interval calculation)?
Did you mean "up" (uncertainty propagation)?
Did you mean "exp" (scientific notation)?
Did you mean "ia" (interval arithmetic)?
Did you mean "fr" (fractions)?

1 lightyear = approx. 9.46E12 km
```

**Comment by hanna-kn** [comment]
To name of the option was changed (before released) from `e notation` to `exp display` (`edisp`).
```
qalc -s "edisp 2; exp 1; maxdeci 2" 1 ly to km
1 lightyear ≈ 9,46 × 10^12 km
```

**Comment by sergeevabc** [comment]
Thank you for letting me know, Hanna.
Options become hard to memorize, I'' copy that command into my knowledge base.
