### ISSUE TITLE
Ignore comma in numbers

### ISSUE THREAD

**Issue by Nowaker** [Qalculate/libqalculate#15]
qalculate-gtk has this option in preferences. How to enable it in command-line `qalc`? Is there any command line switch for it? If there is, can we get this listed in `qalc --help`? If not, please treat it as a feature request for `qalc`.

**Comment by hanna-kn** [comment]
I guess I forgot to add it to qalc. You can however manually change the setting in ~/.config/qalculate/qalc.cfg (you might first need to run and exit `qalc` without any expression to generate the configuration file).

**Comment by hanna-kn** [comment]
I have now added the option to qalc. It can be activated using `--set "comma as separator on"`, or `set comma as separator on`  in "interactive" mode (which makes the setting permanent by default).

**Comment by Nowaker** [comment]
Perfect! Huge thanks!

**Comment by Nowaker** [comment]
@hanna-kn Has anything changed since 2016?

```> set comma as separator on;
Unrecognized option.
> %                                                                                                                                                                  nowaker@nwkr-newmbp ~ % qalc --set "comma as separator on"
Unrecognized option.
> %                                                                                                                                                                  nowaker@nwkr-newmbp ~ % qalc --version
3.6.0
```

**Comment by hanna-kn** [comment]
The option was changed to "ignore comma" in version 2.4.0.

**Comment by Zedroid** [comment]
when enabling this option, can you make the result not have a space in between where the comma should have been, so 19 000 would become 19000 instead?
