### ISSUE TITLE
Inconsistent results with sub-expression replacement

### ISSUE THREAD

**Issue by s-leroux** [Qalculate/libqalculate#150]
I still have not checked the changes introduced with more recent versions of the `Replace` function, but as of Qalculate 0.9.7, it does not properly handle sub-expression replacements:

- `replace(x+y; x+y; x×y)` => `xy` as expected,
- but `replace(x+y+1; x+y; x×y)` => `x+y+1` (no substitution)
- same for `replace((x+y)+1; x+y; x×y)` => `x+y+1`
- whereas `replace(1+(x+y); x+y; x×y)` => `xy+1`

**Comment by hanna-kn** [comment]
The replace function is really only intended for replacement of variables. It is trivial to fix `replace(x+y+1; x+y; x×y)` and similar, but expression such as `replace(2x+2y; x+y; x×y)` and `replace(x+3; x+2; x+y)` are more problematic. The handling of these are more natural for the "where" syntax.

**Comment by s-leroux** [comment]
> [...] but expression such as `replace(2x+2y; x+y; x×y)` and `replace(x+3; x+2; x+y)` are more problematic.

In my mind, the `replace` function is more for pattern matching/substitution rather that for purely algebraic manipulations of an expression.

So, it should be sufficient to limit the scope of the `replace` function in replacing already existing expression sub-trees -- with the exception of the left- right-associativity issue I mentioned initially. 

On the other hand, I wouldn't expect `replace` to factor out the constant in `2x+2y` to make the pattern `x+y` appear. Same thing for `replace(x+3; x+2; x+y)`: the expression tree for `x+3` does not contain the subtree `x+2`. Unless maybe we imagine `x+3` as `x+1+1+1` and `x+2` as `x+1+1`. But as you said, it starts to be more problematic for little benefit. Or it isn't?
