### ISSUE TITLE
Replace can't replace function names

### ISSUE THREAD

**Issue by s-leroux** [Qalculate/libqalculate#151]
Barring issues described in #150, the `Replace` function can replace sub-expressions, but not functions:

- `replace(1+(x+y); x+y; x×y)` => `xy+1`
- however `replace(sin(x); sin; cos)` => `sin(x)`

With the new notation introduced with #147, we may also expect something like that to work:

`f(x+1)/(1+f(x)) where f=sin`

**Comment by hanna-kn** [comment]
Done.

The "where" syntax will initially likely only support expression such as `sin(x+1)/(1+sin(x)) where sin()=cos()`.

**Comment by s-leroux** [comment]
> The "where" syntax will initially likely only support expression such as `sin(x+1)/(1+sin(x)) where sin()=cos()`.

I think this syntax will introduce ambiguities with nullary functions:

```
f()*f() where f()=rand()
```

Does that produces the product of two independent random numbers, or the square of one random number?

**Comment by hanna-kn** [comment]
You are right, although it would be difficult for the user to notice the difference.
