### ISSUE TITLE
Conversion: MPa to kg/cm^2 off by factor 1000

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/libqalculate#153]
On Windows 10 x64 and with Q! 3.3.0 I get this funny result:

Conversion: `165MPa to kg/cm^2`

<img src="https://user-images.githubusercontent.com/10420187/63742104-079fad00-c898-11e9-87da-6475359dede0.png" width="320">

When entering the same thing in wolframalpha, I get this:
<img src="https://user-images.githubusercontent.com/10420187/63742255-8694e580-c898-11e9-92db-953570b1278b.png" width="640">

https://www.wolframalpha.com/input/?i=165+MPa+to+kg%2Fcm%5E2

Q!: `1650000 kg/(cm*s^2)` (what's `cm*s`??)
wa: `1683 kg/cm^2`

**Comment by hanna-kn** [comment]
The difference is that Wolfram alpha in this case interprets kg as kgf (kilogram-force or kilopond). Notice the 'f' in the WA result. It is not possible to convert MPa to kg/cm^2 (1 Pa = N/m^2 = 1 kg / (m*s^2)).

You will get the same result in Qalculate! if you type 165 MPa to kgf/cm^2.

**Comment by foreachthing** [comment]
Hanne, I did notice the 'f' but did ignore it.
Well, sorry to bother you with this non-issue! If I do as you say, it works! That's all I need :-)
Thanks a lot!!
