### ISSUE TITLE
Problems with negative expressions and fractional exponents

### ISSUE THREAD

**Issue by RGB-es** [Qalculate/libqalculate#154]
The expression

`((2/3)×sqrt(7/3)+1)^(1/3)−((2/3)×sqrt(7/3)−1)^(1/3)`

gives 1, which is the right result, but

`((2/3)×sqrt(7/3)+1)^(1/3)+(−(2/3)×sqrt(7/3)+1)^(1/3)`

(moving the minus "inside" the cubic root) gives a complex number

`1,3956439 + 0,22842513i`

which is unexpected: both expressions are equivalent.

If I use instead

`((2/3)×sqrt(7/3)+1)^(1/3)+cbrt(−(2/3)×sqrt(7/3)+1)`

I get the right answer. That means that two equivalent operations (taking the cubic root and rising to a `1/3` power) provide different results when the expression is negative.

**Comment by hanna-kn** [comment]
Fractional exponents always returns the principal root, while cbrt (and root) returns the real root. Matlab and Wolfram Alpha behaves in a similar way.

**Comment by RGB-es** [comment]
> Fractional exponents always returns the principal root, while cbrt (and root) returns the real root. Matlab and Wolfram Alpha behaves in a similar way.

Thanks! I can see that Octave does that too. Sorry for the noise!
