### ISSUE TITLE
warning: Misplaced decimal separator ignored

### ISSUE THREAD

**Issue by peterzuger** [Qalculate/libqalculate#155]
After upgrading to libqalculate 3.4.0 today,
when using the `uptime` variable I get the warning:

    > uptime
    
    warning: Misplaced decimal separator ignored
    uptime = approx. 9 h + 5 min + 40.246353 s

this issue does not occur with any other variable (now, tomorrow, yesterday ...)

**Comment by hanna-kn** [comment]
Fixed.

There warning was correct since the two values (uptime and idle seconds) from /proc/uptime was mistakenly concatenated.

**Comment by peterzuger** [comment]
Thank you for the fast response :)
 
compiled and tested works perfectly
