### ISSUE TITLE
Update popup every time app opens

### ISSUE THREAD

**Issue by gabe117** [Qalculate/libqalculate#157]
It would be nice if there's a way to stop the updated version popup from coming up every time the app opens. I can't find a way to do it, but maybe I'm missing the option.

It would be okay if it popped up once if there was a way to check off don't ask again until next update.

It's a calculator, so I really don't need to go to the hassle of updating every time, but that popup is so annoying when I'm trying to do a simple calculation. It makes the app almost unusable.

**Comment by hanna-kn** [comment]
The normally behaviour is that the application checks for a new version every other week. The user will only be notified once for each new version.

Which version and operating system are you using?
Is the settings and state saved properly after exit (e.g. is mode changes and history preserved when the application is opened again)?

**Comment by hanna-kn** [comment]
I found a bug which causes the application to potentially segfault, and not save mode/settings properly, on exit when history is empty. This would cause the update popup to be shown on each start. This has now been solved and is for the released versions easily avoided by calculating an expression at least once (and after each time the history is manually cleared). I will search for other bugs which might cause the application to not exit properly (this is also related to https://github.com/Qalculate/qalculate-gtk/issues/114).

**Comment by gabe117** [comment]
Thanks for looking into it. I'm now on the most up to date with Windows 10, but I was on the version just before current, so I can't confirm presently. I have history enabled in the sense that I can see the tape history every time I open the app.
