### ISSUE TITLE
Option to set automatic prefix type to binary?

### ISSUE THREAD

**Issue by sta-c0000** [Qalculate/libqalculate#158]
Hello, qalc is wonderful, thank you.

Would it be possible to have an option to set automatic prefix type to binary instead of decimal?

I often wish for binary prefixes for human readable programming / computing results; binary prefixes can be manually specified, but automatic binary prefixing would be great for times where the byte or bit sizes are unknown.

```sh
# To keep it simple, automatic prefixing right now does this:
qalc 2^32 bytes  # = approx. 4.2949673 gigabytes
qalc 2^17 bytes to ?bits  # = 1.048576 megabits
# With an automatic binary prefix setting, the results would be similar to...
# If we know the size in advance we can ask for binary prefix results:
qalc 2^32 bytes to gibibytes  # = 4 gibibytes
qalc 2^17 bytes to mebibits  # = 1 mebibit
# Would be useful for calculations with unknown binary prefix:
qalc "2^rand(64) bytes to ?bits" # with binary prefix option, result would always be integer
echo "Reserved RAM = $(qalc $(lsmem -b | awk '/Total online/ { print $NF }') bytes - $(free -b | awk '/Mem/ { print $2 }') bytes )"
# Perhaps some sort of set option?:
qalc -set "pref binary" -t "($(paste -d+ /sys/class/net/*/statistics/rx_bytes)) bytes"
# Or perhaps a convert prepend char (i) for optimal binary prefix?:
qalc -t "10Mibits/s * 10min to ibytes"
```
Apologies if this option already exists, or has already been dismissed.

Otherwise, alternative is to turn off prefixing and feed output to `numfmt --to=iec-i`

Thank you.

**Comment by hanna-kn** [comment]
I will try to come up with a suitable syntax for conversion to optimal binary prefix (I do not like _ibytes_). If I'm unable to do that, I will at least add an option to use binary prefixes by default for information units.

**Comment by hanna-kn** [comment]
The following syntax has now been implemented (with "b?" for optimal binary prefix and "binary prefixes" / "binpref" option):
```
qalc -set "binpref" -t "($(paste -d+ /sys/class/net/*/statistics/rx_bytes)) bytes"
qalc -t "10Mibits/s * 10min to b?bytes"
```

**Comment by sta-c0000** [comment]
Wow, that was fast!
Tried them, works well both ways, and you've already added them to `help to`/`help set`, that's great.
Thank you very much.
