### ISSUE TITLE
Poisson distribution to be added under Functions/Statistics/Distribution

### ISSUE THREAD

**Issue by conradOU** [Qalculate/libqalculate#159]
Explanation of significance and real-life examples: https://brilliant.org/wiki/poisson-distribution/

Excel has it, I think many users would like to see it implemented in the calculator.

Thanks in advance.

**Comment by hanna-kn** [comment]
Poisson distribution function has now been added using the expression `if(\Z{0},sum((\y^"k"*e^(-\y))/("k"!),0,\x,"k"),(\y^\x*e^(-\y))/(\x!))`.
