### ISSUE TITLE
Eats all RAM with calculation with huge result

### ISSUE THREAD

**Issue by kbroulik** [Qalculate/libqalculate#16]
When I try to calculate the following
```
2^2^2^2^2^2^2
```
it starts to eat all RAM until the application is killed. (Using libqalculate 0.9.7-9.1)

Downstream bug report: https://bugs.kde.org/show_bug.cgi?id=277011

**Comment by hanna-kn** [comment]
I consider it foremost an issue (there are multiple others) with how krunner uses libqalculate. The calculator runner should use the libqalculate functions the stops slow RAM-eating calculations after a specified amount of time.

**Comment by numsim1415** [comment]
Firstly: I agree with @hanna-kn that krunner should terminate libqalculate calls after a timeout.

Yet, Note:
This memory consuming bug occurs **even with simple,** everyday **calculations**!
`2^0.333333333`
The memory issue triggers only when using **at least 9 digits** after the comma.
Such calculations are not extraordinary and no user would expect this to freeze his system.

@hanna-kn 
Can you confirm that the latest version of libqalculate has an issue with `2^0.333333333` ?

**Comment by hanna-kn** [comment]
If exact or 'try exact' mode is used 2^0.333333333 is calculated as (2^333333333)^(1/1E9), which for obvious reasons is slow (although the result is returned after less then four seconds on my computer). In approximate mode (perhaps most appropriate for krunner) the result is returned practically instantaneously.

**Comment by hanna-kn** [comment]
I have now fixed slow calculation of exponentiations in exact and "try exact" modes. When exact calculation fails the exponent is now no longer split up in numerator and denominator if the numerator is larger than 10 000 (or smaller than -10 000).

**Comment by numsim1415** [comment]
@hanna-kn 
Just tested the change.
Still takes very long with `2^0.3333333333`. Is this expected/intended?

**Comment by hanna-kn** [comment]
@numsim1415 
No, that is not expected. With the change, no matter how many 3's I enter the result is returned 
instantaneously.

**Comment by hanna-kn** [comment]
Qalculate! will now realize that 2^2^2^2^2^2^2 (= 2^(2^(2^(2^(2^(2^2)))) = 2^(2^2,0035299E19728)) is ridiculous and not try to calculate it.
