### ISSUE TITLE
Incorrectly evaluated integral abs cos

### ISSUE THREAD

**Issue by polygonalenippel** [Qalculate/libqalculate#160]
Try this: `integrate( abs(cos(x)); x; 0; 3pi/2 )`

The evaluated answer is -1 while the correct answer is 3 (calculated with hand, confirmed by Casio fx-991EX and WolframAlpha).

It's quite trivial, not going to work it out, but it surprised me it gave me this answer because if you request just the integral of abs(cos(x)), it seems to know how it should be done.

Using 3.4.0-1 (gtk same version) packaged for Arch, on a i5-6300U

**Comment by hanna-kn** [comment]
The problem is that the integral of `abs(cos(x))` is calculated to `sin(x)*sgn(cos(x))` (as WolframAlpha), which is not strictly correct (discontinuous where cos(x) is zero) and results in an incorrect result for the definitive integral (`sin(3pi/2)*sgn(cos(3pi/2) - sin(0)*sgn(cos(0))`).
