### ISSUE TITLE
Request: option to choose j as imaginary unit

### ISSUE THREAD

**Issue by polygonalenippel** [Qalculate/libqalculate#161]
**Suggestion**: An an option to be able to choose j as the imaginary unit, contrary to the default unit i. At the moment, j is not used as a default unit so there shouldn't be conflicts.

**Motivation**: In the field of electrical engineering (and some other closely related ones), i is typically the symbol reserved for current. Furthermore, complex analysis is riddled everywhere in this field, e.g. for aiding in calculations of _transfer functions_ and such.

Also, contrary to more purely mathematical fields, j is typically syntactically put in front of the imaginary term, to be able to better distinguish the fact that a _phase shift_ has occurred.

Thus, instead of results like `a + b*i`, a result in the form of `a + j*b` is desired.

I think I can speak on behalf of the engineers using your beautiful software that this addition would be very appreciated if it were to be added.

**Comment by hanna-kn** [comment]
Done. When the new option is activated, j will be default symbol for input and display of the imaginary unit (placed in front of the digits), but _i_ will still also be interpreted as the imaginary unit (for compatibility reasons).

**Comment by polygonalenippel** [comment]
Thanks! Looking forward to the next release!
