### ISSUE TITLE
Solving equation on Windows gives multiple possibilites, one of which is incorrect.

### ISSUE THREAD

**Issue by lauritzt** [Qalculate/libqalculate#166]
The equation `2 - sqrt(6 - x) = 2x` should give `x = -0,25`.

Running

    solve(2 - sqrt(6 - x) = 2x; x)

on Windows, with the GTK+ 64-bit version of 3.5.0 gives

    (-0,25; 2)

and on Linux, terminal version 3.5.0 it gives:

    -0,25

The result from the Windows version is incorrect. Running:

    x := 2
    2 - sqrt(6 - x) = 2x

gives `0` on both Windows and Linux.

**Comment by hanna-kn** [comment]
Fixed (I accidentally typed `||` instead of `&&`).
