### ISSUE TITLE
Complex exponential form not always enforced

### ISSUE THREAD

**Issue by polygonalenippel** [Qalculate/libqalculate#170]
Using the latest version available for Arch Linux, 3.6.0-1

When complex exponential form is chosen, results often get much more complex (no pun intended) than they need to be.

Something like `exp(j(pi×x)) × exp(j(−pi/3))` first yields some stacked natural exps: `e^(e^((j0.5) × π) × πx) × (√(3)(0.5e^((j × −0.5) × π)) + 0.5)`. Upon hitting Simplify, we get closer to the preferred result, though this still contains a complex factor outside the exponent: `(e^(jπx) × (1 − j × √(3))) ∕ 2`.

The preferred result would be `exp(j * (pi*x - pi/3))`. Is this easy to accomplish?

**Comment by polygonalenippel** [comment]
I practically applied the rule of exponents, but perhaps it's getting confused by the Eulerism?

**Comment by hanna-kn** [comment]
The following happens: 
The expression is first calculated/simplified to `(e^(i * pi * x) * (1 - i * sqrt(3))) / 2`.
Complex numbers in the resulting expression are then converted to the selected form (the result is not modified when using the default rectangular form). Only purely numerical values are handled (e.g. e, pi, x, as well as exponentiation, multiplication, etc. are ignored), which means that the two imaginary units are separately transformed to `e^(i*pi/2)`.

I have now made a (very simple) modification to ignore complex numbers in exponentiations, which will improve the output somewhat (`(e^(i * pi * x) * (1 + sqrt(3) / e^((i * pi) / 2))) / 2`).

**Comment by polygonalenippel** [comment]
Thanks, I think this issue can be closed?
