### ISSUE TITLE
[source tarball] 3.7.0 release contains pre-built documentation

### ISSUE THREAD

**Issue by RogueScholar** [Qalculate/libqalculate#174]
Hi Hanna,

Congratulations on another solid release, I always get a smile on my face when I open up Qalculate for the first time that day and the notification pops up that a new version was released as it did this morning. :+1: I'm hard at work already doing the Debian packaging for it (though sadly not for their official package archive, which remains at v2.8.2 with few signs of moving, but that's a whole other story) and wanted to pass along the issues that I encountered thus far so you could address them here if you desired.

- As the title of the issue indicates, this version's release tarball ended up with all of the Doxygen-generated documentation present in `docs/reference/html`. I'm not sure if that was intentional on your part, but to comply with the Debian Standards for source packages I had to write a little repack function to extract the tar file and zap them out before re-compressing to commence the build. If that was just an oversight and you decide to upload new tarballs without those files, please ping me here so I can upload a package without them.
- The package linter (lintian) reported a spelling error inside the compiled libqalculate.so.21.6.0, specifically it found an instance of the word 'addD' which looked to me like a simple case of missing the space bar between words somewhere. When I went back and grepped the source tree though, and then the build directory after that, and I couldn't find a single instance of it in either location. The whole thing struck me as odd and I'm chalking it up to a false positive but mentioning it here as you might know what's behind it, if it's not in fact just a fussy linter being fussy.
- Debian is trying to coerce its packagers to start carrying symbols files for packages containing C/C++ libraries that establish some sort of provenance for the entrance and exit of the symbols from the library and in which versions they occurred. I've made no end of attempts to accomplish that task for libqalculate but have been utterly stymied when it comes to arriving at a reproducible result. I'm fairly certain that I'm simply lacking the code monkey bona fides to see the path forward and that's not at all your issue. I'm attaching the file containing what progress I've made thus far though in case you have any interest in the issue or any casual advice on where I might be getting stuck and why. Put succinctly I'm getting minor variances in the reported symbols post-build that seem influenced by both the architecture of the build platform and the version of compiler used. Any thoughts you have will be most gratefully heeded.

That's it for me right now. As always, my hat's off to you for always finding new things to improve and features to introduce, it's a pleasure not only to use Qalculate but also to bear witness to your work on it. I hope this note finds you well in body, mind and spirit.

Warmly,
Peter

P.S. I believe I've shared the location of the package repository with my libqalc efforts before, but in the event I haven't yet, you can find it [here](https://launchpad.net/~plasma-applet-qalculate/+archive/ubuntu/ppa).

Attempt at a symbols file to satisfy [Debian Policy v.4.5.0, §8.6.2](https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#shared-library-abi-changes): [libqalculate21.symbols.amd64.tar.gz](https://github.com/Qalculate/libqalculate/files/4094737/libqalculate21.symbols.amd64.tar.gz)

**Comment by hanna-kn** [comment]
The doxygen-generated documentation has been included in the source package since the first versions of libqalculate. It was probably more convenient to generate it separately than figure out an appropriate automake solution.

I have now created a source package without pregenerated documentation:
https://github.com/Qalculate/libqalculate/releases/download/v3.7.0/libqalculate-3.7.0-nodocs.tar.gz
