### ISSUE TITLE
Parallel resistance fails when using prefix

### ISSUE THREAD

**Issue by Wastus** [Qalculate/libqalculate#175]
The expression:
1kOhm || 1 kOhm results in 1 instead of 500 Ohm
1kOhm || 1000 Ohm results in 1.
1000 Ohm || 1000 Ohm results in 500 Ohm. (fine)
1kOhm || 10 kOhm results in 909 Ohm (fine)

This works with other numbers in the same way (9,5 kOhm or something).

So something is going wrong when I try to parallel resistances of same size (well it's kind of trivial, but nonetheless) with using a prefix.

**Comment by hanna-kn** [comment]
Fixed.
