### ISSUE TITLE
make gnuplot persistent when run in noninteractive mode

### ISSUE THREAD

**Issue by nonchip** [Qalculate/libqalculate#176]
currently in [`PlotFunction::calculate`](https://github.com/Qalculate/libqalculate/blob/64a6f5de3127d97081cf37c2992b1fd8a177a644/libqalculate/BuiltinFunctions-util.cc#L909) `Calculator::plotVectors` is called with hardcoded `persistent=false`.

this results in commands like `qalc "plot(x^2)"` to immediately exit (since it's noninteractive and `plot` returns 0 immediately) and kill its `gnuplot` child.

this is obviously very unlikely to be intended by the user, especially since there doesn't seem to be a way for the `qalc plot` builtin to specify an output file, so the interactive gnuplot window is the only thing we can get anyway.

i propose for a change to detect whether this was called from a noninteractive `qalc` process (e.g. by exposing a `persistent=false` parameter, which shouldn't mess up the API since it's defaulted to do the same as before, that's then set to `true` by said process).

see also https://github.com/svenstaro/rofi-calc/issues/40 for why this is an issue (plus my hacky `LD_PRELOAD` solution overriding the parameter to "fix" it, but it's obviously better if `qalc` includes this functionality to begin with).

**Comment by hanna-kn** [comment]
Done (I've added a persistent parameter, which defaults to true if qalc is started in noninteractive mode, to plot() function).
