### ISSUE TITLE
RPN syntax is broken in CLI

### ISSUE THREAD

**Issue by vvs-** [Qalculate/libqalculate#18]
Try an example from manual: "5 2 +". 

```
  warning: RPN syntax error. Operator ignored as there where only one stack value.
  52 = 52
```

The GUI version works, though.

**Comment by hanna-kn** [comment]
Fixed. 

It was equally broken in the GUI version.

**Comment by vvs-** [comment]
Thanks. The GUI version which I've tested was not compiled by me and actually was older than CLI. Seems that I shouldn't be that lazy after all 😉
