### ISSUE TITLE
Localization ?

### ISSUE THREAD

**Issue by ghost** [Qalculate/libqalculate#181]
Hello, i want to contribute a Polish translation for qualculate, how can i do that ?

**Comment by hanna-kn** [comment]
Qalculate uses gettext for localization.

A full translation of Qalculate requires that you translate the following files:
https://raw.githubusercontent.com/Qalculate/libqalculate/master/po/libqalculate.pot,
https://raw.githubusercontent.com/Qalculate/qalculate-gtk/master/po/qalculate-gtk.pot, and 
https://raw.githubusercontent.com/Qalculate/libqalculate/master/po-defs/libqalculate.pot

You should read https://raw.githubusercontent.com/Qalculate/libqalculate/master/README.translate first (at least before attempting to translate the variable, unit, and function definitions in po-defs/libqalculate.pot).

The Swedish translation (in sv.po files) is complete and should serve as a good example.

**Comment by Qik000** [comment]
Oh wow, thats a LOT, will look into it and translate bit by bit, is there any chance for qalculate to make an account on an onlien translating service ? Sorta like Telegram did ?
