### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by ghost** [Qalculate/libqalculate#182]
The current icon looks dated, i made a new one, would be awesome if it became the official one !

![image](https://github.com/Qik000/icons/blob/master/qalculate_logo.svg)

**Comment by hanna-kn** [comment]
The icon looks nice, but unfortunately falls short in some aspects.

Apart from appearing simple and modern, the icon should preferably indicate the functionality of the associated application (the current icon fails completely in small sizes) and/or be associated with the name of the application (the current icon clearly consists of the Q and ! of the application title). (Bonus points are awarded for hinting at Q meaning queer.)

Your icon is a good start. I like that you kept the colour (although I prefer it a bit brighter) and that it is still possible to read it as a Q. The equals sign is nice touch, even though it is not obvious enough to help identifying the application as a calculator, but I do not understand the triangle in the middle.

**Comment by apelly** [comment]
And all I was thinking... "Please be an adding duck!"

**Comment by Qik000** [comment]
> The icon looks nice, but unfortunately falls short in some aspects.
> 
> Apart from appearing simple and modern, the icon should preferably indicate the functionality of the associated application (the current icon fails completely in small sizes) and/or be associated with the name of the application (the current icon clearly consists of the Q and ! of the application title). (Bonus points are awarded for hinting at Q meaning queer.)
> 
> Your icon is a good start. I like that you kept the colour (although I prefer it a bit brighter) and that it is still possible to read it as a Q. The equals sign is nice touch, even though it is not obvious enough to help identifying the application as a calculator, but I do not understand the triangle in the middle.

The triangle is a delta character

**Comment by Qik000** [comment]
> The icon looks nice, but unfortunately falls short in some aspects.
> 
> Apart from appearing simple and modern, the icon should preferably indicate the functionality of the associated application (the current icon fails completely in small sizes) and/or be associated with the name of the application (the current icon clearly consists of the Q and ! of the application title). (Bonus points are awarded for hinting at Q meaning queer.)
> 
> Your icon is a good start. I like that you kept the colour (although I prefer it a bit brighter) and that it is still possible to read it as a Q. The equals sign is nice touch, even though it is not obvious enough to help identifying the application as a calculator, but I do not understand the triangle in the middle.

Also, to be fair, the current icon also doesnt hint anything calculator-related (asked my mom who has seen it for the 1st time), she thought its for some sort of cam-mirror or text editor program, first because it kinda looks like a mirror and second because of the ! And a LOT of programs have icons that dont hint anything about what they do, Blender, Steam, Chromium, VS-Codium are good examples

**Comment by hanna-kn** [comment]
> The triangle is a delta character, i can remove it if You think it will look better without it

I would prefer to replace the delta character without something more clearly mathematical.

Here is one simple variant (although someone might associate it with the word cutie-pie; the Planck constant would be preferable but not as recognizable):
![qalculate_logo](https://user-images.githubusercontent.com/19703699/78812508-ce055780-79cb-11ea-81c1-d7af4810bcba.png)

I might be persuaded to accept a rabbit or mouse in the icon instead...

> Also, to be fair, the current icon also doesnt hint anything calculator-related (asked my mom who has seen it for the 1st time)

As I clearly admitted. The big version (https://github.com/Qalculate/qalculate-gtk/blob/master/data/icons/scalable/qalculate256.svg) does however contain elements that are at least highly related to the functionality.

> And a LOT of programs have icons that dont hint anything about what they do, Blender, Steam, Chromium, VS-Codium are good examples

Icons/logos that don't hint anything works best for strong brands (or if normally combined with the name). Some icons (including the Blender logo) that seem random today has evolved from versions with more apparent thought processes.

**Comment by Qik000** [comment]
So what do you suggest ?
π is out because of qt3.14 meme, Planck constant wont be neary as recognized, maybe a # ? or division by zero (1/0 in a fraction) ? Or maybe just leave it blank ?

> The big version (https://github.com/Qalculate/qalculate-gtk/blob/master/data/icons/scalable/qalculate256.svg) does however contain elements that are at least highly related to the functionality.

Yes but an icon is mostly seen at small or very small sizes.

Maybe the best solution is to leave it blank ? Or i can make several versions and we could create a poll and let people decide ?

**Comment by hanna-kn** [comment]
> So what do you suggest ?
> π is out because of qt3.14 meme, Planck constant wont be neary as recognized, maybe a # ? or division by zero (1/0 in a fraction) ? Or maybe just leave it blank ?

My suggestion is that we try to come up with a better solution.

When left blank, the circle (or C) looks oversized somehow. It is nevertheless probably best to leave it blank for the smallest sizes.

Here are some other variants:
![qalculate_logo2](https://user-images.githubusercontent.com/19703699/78862531-e3b06680-7a37-11ea-9e6d-88245b1d15b2.png) ![qalculate_logo3](https://user-images.githubusercontent.com/19703699/78862547-e8751a80-7a37-11ea-89bd-a29e79af8701.png) ![qalculate_logo4](https://user-images.githubusercontent.com/19703699/78862555-eca13800-7a37-11ea-9937-b0de92b02a37.png) ![qalculate_logo5](https://user-images.githubusercontent.com/19703699/78862560-ef039200-7a37-11ea-8496-346da6df2a95.png)

**Comment by hanna-kn** [comment]
I tested the new icon and I was less pleased with it against dark backgrounds (particularly in small sizes).

**Comment by Qik000** [comment]
I think this one: https://user-images.githubusercontent.com/19703699/78866925-9258a500-7a40-11ea-90e7-e687dbef3f07.png is the best out of the 4. And as for the color.


![qalculate_logo svg](https://user-images.githubusercontent.com/32220535/78893301-6a326b80-7a6b-11ea-8d34-8020d44716cd.png)

I added a bit of gradient to improve visibility on dark backgrounds

**Comment by Qik000** [comment]
![qalculate_logo svg](https://user-images.githubusercontent.com/32220535/78901441-9f918600-7a78-11ea-91ca-67a8405a4bbf.png)
I also made a diffrent gradient version targeted specifically at dark backgrounds, and i think it looks WAY better than purple-white gradient, its way more modern

**Comment by Qik000** [comment]
Any news ? @hanna-kn

**Comment by hanna-kn** [comment]
- I will keep the current icon in version 3.9 (will soon be released).
- The Qalculate! colour is pink. This will not change.
- I'm still not pleased with the legibility of the new icon in the smallest sizes (< 32 px) regardless of background (it just looks like a plain circle).
- It's unfortunately not possible the specify a different icon for dark backgrounds.

**Comment by Qik000** [comment]
>     * I will keep the current icon in version 3.9 (will soon be released).
> 
>     * The Qalculate! colour is pink. This will not change.
> 
>     * I'm still not pleased with the legibility of the new icon in the smallest sizes (< 32 px) regardless of background (it just looks like a plain circle).
> 
>     * It's unfortunately not possible the specify a different icon for dark backgrounds.

So what do you suggest ? The current icon looks terrible imho, it looks like it was made in 1990 :/
And such an awesome program needs a modern icon.
If you tell me what should i do with this i will make a new one

**Comment by hanna-kn** [comment]
Maybe you should tell what the main problems with the current icon are. It's just the characters Q (using DejaVu Sans) and ! with a gradient, and a semitransparent background to improve legibility and, in sizes > 32 px, some text to indicate the functionality, in the circle of the Q.

Your icon looks better than mine as a logo, but as an icon I prefer the current one, which I think appears more distinct. I would prefer to move in a different direction and not follow in the footsteps of software such as Maxima and R, and instead achieve an icon in between Matlab (or Mathematica) and gnome-calculator (the icon is basically a generic calculator keypad).

The icon can quite easily be changed be the user, so there is at least no need for you to see the default icon regularly.

**Comment by Qik000** [comment]
It looks dated, especially teh gradient from purple to white, its complex, and its esthetics are straight from 1990 imho. Just look at the old Firefox icon and comapre to the modern one, night and day !
Same here, it needs to be modernized.

> Your icon looks better than mine as a logo, but as an icon I prefer the current one, which I think appears more distinct.

My friends think my design works better as an icon, guess its subjective, cant make everyone happy.

And if you want to move towards abstract icons then i would need a direction to face towards, a graph ? log scale ? I need something to hook onto

**Comment by hanna-kn** [comment]
> It looks dated, especially teh gradient from purple to white, its complex, and its esthetics are straight from 1990 imho. Just look at the old Firefox icon and comapre to the modern one, night and day !

I would be happy if the Qalculate! looked half as good as the old Firefox icon. I do not remember that gradients were popular at all in 1990 and not even Netscape existed at that time (by the way, the Netscape icon also used the initial letter as the main element in the icon). It might actually be nice with a retro chic design...

Below are two screenshots which illustrate my main issue with the icon (that it looks like a nondescript circle in small sizes).
![1](https://user-images.githubusercontent.com/19703699/79230653-3c7f6500-7e65-11ea-940e-b4e31621c9ab.png) ![2](https://user-images.githubusercontent.com/19703699/79230666-3f7a5580-7e65-11ea-82a2-503a35131c98.png)

> And if you want to move towards abstract icons then i would need a direction to face towards, a graph ? log scale ? I need something to hook onto

If I had any good ideas the icon would already look different.
_Maybe I should use the Praat icon as inspiration (at least the concept is clear)..._ ![Praat icon](http://www.fon.hum.uva.nl/praat/praat_white.gif)

**Comment by Qik000** [comment]
![qalculate_logo svg](https://user-images.githubusercontent.com/32220535/79244922-b882a880-7e77-11ea-82df-6ff6e925bb15.png)
What about this one ?

**Comment by hanna-kn** [comment]
> What about this one ?

I do not understand it (what does it represent?).

How about something along these lines (but better looking):
![qalculate](https://user-images.githubusercontent.com/19703699/79256871-06ec7300-7e89-11ea-8ef1-90d808cf333d.png)
(probably not legible enough in small sizes...)

**Comment by foreachthing** [comment]
I changed my shortcut icon to a simple calculator icon (square with few keys). So I know what to look for. Already got plenty of "circle" icons from other programs... 

I like the last suggestion best. Maybe a bit more contrast?

**Comment by Qik000** [comment]
> I do not understand it (what does it represent?).

A book, with a Q logo, i checked with 32x32 sizes and it looks alright

![reply](https://user-images.githubusercontent.com/19703699/79256871-06ec7300-7e89-11ea-8ef1-90d808cf333d.png)

I will try to do something like this, but maybe with only 1 panel ? To satisfy the small icon requirement more ?

**Comment by hanna-kn** [comment]
A new variant based on the calculator icon from the Ubuntu icon theme Yaru:
![qalculate](https://user-images.githubusercontent.com/19703699/79310457-486a3600-7efc-11ea-9a71-05fdd4cbfe09.png)

**Comment by Qik000** [comment]
Looks nice but i would replace pink with violet and add a slight gradient to a red`ish color, and make the = bolder because it sinks in the background on smaller sizes

**Comment by foreachthing** [comment]
> A new variant based on the calculator icon from the Yaru icon theme

I miss the Q (in some way). With or without "!".

**Comment by hanna-kn** [comment]
Updated icons:
![qalculate](https://user-images.githubusercontent.com/19703699/79340719-086e7780-7f2b-11ea-841a-c185af850436.png)

> I miss the Q (in some way). With or without "!".

At least I avoid association with some despicable elements of the American society...

**Comment by Qik000** [comment]
![qalculate_logo svg](https://user-images.githubusercontent.com/32220535/79362389-d4a14b00-7f46-11ea-9482-4e582f9406b7.png)
How about that ?

**Comment by hanna-kn** [comment]
> How about that?

- As I've said before, I will preserve the pinkish colour of the icon.
- Omega (ohm), in contrast to pi, is a symbol that represents one of the core distinguishing features of Qalculate!. (The _x_ represents the CAS functionality.)
- The equals sign makes it clear that the application is a calculator and has good legibility, The Q might improve branding, but does not in any way show the application function and has poor legibility in small icon sizes.
