### ISSUE TITLE
Segmentation fault since 3.9.0 release

### ISSUE THREAD

**Issue by maximbaz** [Qalculate/libqalculate#184]
```
$ qalc -t '2*2'
[1]    424079 segmentation fault (core dumped)  qalc -t '2*2'
```

Looking into `$ coredumpctl gdb` I can see this:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5c48fc9930 in MathFunction::setDefaultValue(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /usr/lib/libqalculate.so.21
```

Reproduced on Arch Linux package first, and then by downloading `libqalculate-3.9.0.tar.gz`, unpacking, running `./configure` and `make` in the folder.

Let me know if you need more details! 🙂

**Comment by hanna-kn** [comment]
Fixed.
(When running qalc in non-interactive mode setDefaultValue() was called for plot function which is missing when gnuplot cannot be found.)

**Comment by maximbaz** [comment]
Fix confirmed, thank you very much! 🙂
