### ISSUE TITLE
parsing inconsistency with a conversion expression with a prefixed base

### ISSUE THREAD

**Issue by bsdf** [Qalculate/libqalculate#185]
first, let me just start by saying how much i appreciate your hard work on this application. even though i only use a tiny fraction of its functionality, i'm constantly in awe of how deep and featureful it is.

the issue i'm seeing is related to parsing a conversion expression with a prefixed number base.

i'm often jumping between base 10 and 16 and find the prefixed base functionality very useful. the issue is with input base 10 set, entering `0x400 bytes to kibibytes` is parsed as `16395 * yoctotonne * e to kibibyte` while entering `1024 bytes to kibibytes` properly parses the input as `1024 * byte to kibibyte`.

both of the following work and are acceptable workarounds, but it would be nice to be able to input as described above:
`(0x400) bytes to kibibytes`
`byte 0x400 to kibibytes`

please let me know if i'm simply missing a configuration setting.

running qalculate-gtk-3.8.0 compiled from source on Debian sid

**Comment by hanna-kn** [comment]
Fixed (0x400 bytes will work as expected, but not without whitespace).

**Comment by bsdf** [comment]
works great, thanks!
