### ISSUE TITLE
Inconsistent parsing of single argument functions in RPN syntax expressions

### ISSUE THREAD

**Issue by vvs-** [Qalculate/libqalculate#19]
The parsing of an argument expression for a single argument functions is very surprising when using RPN syntax. When there is exactly one object preceding such function, then everything is working as expected. But if there are any calculations involved - everything breaks apart. So, `9 √` returns 3, but `3 3*√` raises error even if stack is not empty. To make things even more confusing, `3 3*.5^` works just fine. That's definitely a limitation of the parser. BTW, I don't seem to find any way to swap top of the stack. Am I missing something?

To put things into context. I'm trying to find a drop-in replacement for `dc`. I find it's usage of RPN just perfect for my needs, but it has a very limited set of operations. `Qalculate!` looks very advanced but sometimes it lacks some very basic conveniences of a decent RPN calculator. If only Qalculate! was on par with it's RPN parsing abilities, nobody would ever need to use that old and rusty `dc` again.

That's not a complain, actually. Qalculate! has the best balance between a desktop calculator and a general algebra system. I just think that Qalculate! is missing a few important pieces that make it not as well known as it really deserves. Thanks for your continuing work on a very useful application.

**Comment by hanna-kn** [comment]
There are obviously problems with single argument functions (not attempts are made at all to use RPN with multiple arguments) in RPN syntax. I think I know how to solve them but it will require a greater effort than the previous bug. `sqrt(3 3*)` will return the expected result but I understand that such a hybrid syntax might not be satisfactory.

What behaviour and syntax do you expect for swapping top of the stack?

Since I have never used RPN myself, and I am the only developer of Qalculate!, RPN mode and syntax do not receive enough testing and might be missing important functionality.

Note that RPN mode and RPN syntax are currently completely separated. RPN syntax (used in separate expressions) does not use the stack of the RPN mode.

**Comment by vvs-** [comment]
> What behaviour and syntax do you expect for swapping top of the stack?

Well, possibly there should be enough to implement just two operations: swap two top stack values and copy/push top stack value. As for the syntax, I'm used to desktop calculators which use just one keypress for that. Also, `dc` has a very concise syntax: it uses only one symbol for each operation and every argument. But Qalculate! could have its own specifics, of course.

> Since I have never used RPN myself, and I am the only developer of Qalculate!, RPN mode and syntax do not receive enough testing and might be missing important functionality.

Surprisingly, it's good enough, but some pieces are still missing. And using both algebraic infix and RPN syntaxes simultaneously, provides unique advantages. You can enter expressions very quickly and straightforward and immediately see expanded pretty printed results. I wouldn't want to return to `dc` anymore, if only the current small deficiencies would be fixed. From what I've seen, Qalculate! is the only advanced calculator which provides powerful arithmetic and algebraic instruments and has CLI and GUI version as well.

> Note that RPN mode and RPN syntax are currently completely separated. RPN syntax (used in separate expressions) does not use the stack of the RPN mode.

Yes, I've seen that. Actually the syntax could be enough in many cases, but having the values that could persist on stack is even better, of course.

All in all, I think that fixing those loose ends is enough for now. I don't have enough experience with Qalculate!'s powerful features and can't suggest something more useful yet. Perhaps, with time me and other users could develop some more taste for Qalculate!'s abilities. Thanks for working on it. Calculators don't seem to be in much favor nowadays, despite being the only option to quickly and easily evaluate mathematical expressions in everyday activities. There are not much people left who could still know how and why to use them.

**Comment by hanna-kn** [comment]
I think I've now managed to fix the parsing of single argument functions when using RPN syntax.

**Comment by vvs-** [comment]
Thanks. Stack manipulation is still missing, but it's another issue.
