### ISSUE TITLE
Cannot plot a function

### ISSUE THREAD

**Issue by Qik000** [Qalculate/libqalculate#191]
So i was trying to plot a Fourier series using Sigma, but i cannot, heres the expression:

`sum((1/1+2n)*sin((2n+1)*x);0;10;x)`

Desmos online plots this corectly.
can this be fixed ?

**Comment by Qik000** [comment]
An image showing how this should look like:
![Imgur](https://i.imgur.com/Tajh19j.png)

**Comment by hanna-kn** [comment]
This is the correct expression for the function in the image:
`sum(1/(1+2n)*sin((2n+1)*x);0;50;n)`
`1/(1+2n)` instead of `(1/1+2n)`, and `n` instead of _x_ as variable for summation index.

**Comment by Qik000** [comment]
> This is the correct expression for the function in the image:
> `sum(1/(1+2n)*sin((2n+1)*x);0;50;n)`
> (`1/(1+2n)` instead of `(1/1+2n)`, and _n_ instead of _x_ as variable for summation index)

I still get an error while trying to plot this

**Comment by hanna-kn** [comment]
> I still get an error while trying to plot this

What kind of error? 

If you are using the GUI and get the "It took too long to generate the plot data.", then you should either lower the sampling rate, decrease _a_, or use the plot() function (e.g. plot(sum(1/(1+2n)*sin((2n+1)*x);0;50;n)) which does have any time limit.

**Comment by Qik000** [comment]
> > I still get an error while trying to plot this
> 
> What kind of error?
> 
> If you are using the GUI and get the "It took too long to generate the plot data.", then you should either lower the sampling rate, decrease _a_, or use the plot() function (e.g. plot(sum(1/(1+2n)*sin((2n+1)*x);0;50;n)) which does have any time limit.

![Imgur](https://i.imgur.com/SNIUy2X.png)

**Comment by hanna-kn** [comment]
Which version are you using?
If you are using a version before _n_ was introduced, I suggest that you use `\n` (or `'n'` if version too old for this syntax) or _y_ (e.g. sum(1/(1+2y)*sin((2y+1)*x);0;50;y).

**Comment by Qik000** [comment]
> Which version are you using?
> If you are using a version before _n_ was introduced, I suggest that you use `\n` (or `'n'` if version too old for this syntax) or _y_ (e.g. sum(1/(1+2y)*sin((2y+1)*x);0;50;y).

This works, thanks !
i am on 0.9.9
