### ISSUE TITLE
single instance broken since 3.8 / win32 portable

### ISSUE THREAD

**Issue by ritmation** [Qalculate/libqalculate#195]
It seems that since version 3.8 (version 3.7 worked correctly), Qalculate for Windows (32 bit portable) does not respect single instance setting (Allow multiple instances=Off).
With the setting set to off, I'm able to start another Qalculate instance even if I have the program already running.

**Comment by foreachthing** [comment]
Same for installer on Windows 10 x64.

**Comment by hanna-kn** [comment]
Fixed (I updated the MinGW libraries and added gdbus.exe).

The binaries has been updated.
