### ISSUE TITLE
syntax highlighting in cli qalc

### ISSUE THREAD

**Issue by nycex** [Qalculate/libqalculate#198]
qalc is the best cli calculator I have seen so far :+1:, but there is one feature other ones (like [insect](https://github.com/sharkdp/insect)) have, which I miss in qalc: syntax highlighting. It would be great if something like that could also be added to qalc.

**Comment by hanna-kn** [comment]
Done.

**Comment by nycex** [comment]
is there a reason you didn't close this though or should I just close it?
