### ISSUE TITLE
error: use of undeclared identifier 'VERSION'

### ISSUE THREAD

**Issue by tpgxyz** [Qalculate/libqalculate#2]
Hi,

i can not build 0.9.8 version Logs can be find here http://file-store.openmandriva.org/api/v1/file_stores/fd65f91fd4726f4705451b0374ef0d5cb6b35a2f.log?show=true

Compiled with LLVM/clang 3.8.1

In file included from ./DataSet.h:15:
../libqalculate/includes.h:18:17: warning: using directive refers to implicitly-defined namespace 'std'
using namespace std;
                ^
DataSet.cc:754:61: error: use of undeclared identifier 'VERSION'
        xmlNewProp(doc->children, (xmlChar_) "version", (xmlChar_) VERSION);
                                                                   ^
1 warning and 1 error generated.
make[2]: **\* [Makefile:529: DataSet.lo] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[2]: Entering directory '/builddir/build/BUILD/libqalculate-0.9.8/libqalculate'

Calculator.cc:384:2: warning: ignoring return value of function declared with warn_unused_result attribute [-Wunused-result]
        pipe(pipe_wr);
        ^~~~ ~~~~~~~
Calculator.cc:7589:61: error: use of undeclared identifier 'VERSION'
        xmlNewProp(doc->children, (xmlChar_) "version", (xmlChar_) VERSION);
                                                                   ^
Calculator.cc:7667:61: error: use of undeclared identifier 'VERSION'
        xmlNewProp(doc->children, (xmlChar_) "version", (xmlChar_) VERSION);
                                                                   ^
Calculator.cc:7835:61: error: use of undeclared identifier 'VERSION'
        xmlNewProp(doc->children, (xmlChar_) "version", (xmlChar_) VERSION);
                                                                   ^
Calculator.cc:7996:61: error: use of undeclared identifier 'VERSION'
        xmlNewProp(doc->children, (xmlChar_) "version", (xmlChar_) VERSION);
                                                                   ^
Calculator.cc:8200:61: error: use of undeclared identifier 'VERSION'
        xmlNewProp(doc->children, (xmlChar_) "version", (xmlChar_) VERSION);
                                                                   ^
4 warnings and 5 errors generated.
make[2]: **\* [Makefile:529: Calculator.lo] Error 1

**Comment by hanna-kn** [comment]
I am not able to reproduce this error. 

For some reason VERSION seems not be defined in config.h by the configure process. If that is the case, running `echo '#define VERSION "0.9.8"' >> config.h` after configure should solve the issue (obviously not a proper solution).
