### ISSUE TITLE
Syntax highlighting broken with regards to powers

### ISSUE THREAD

**Issue by frozolotl** [Qalculate/libqalculate#200]
Left to the `=` , powers of units are not properly highlighted.
I'd expect it to be either highlighted like on the right side where everything is tinted green,
or like powers of variables are highlighted (see second screenshot).

![](https://i.axo.im/iQOTKw4h5nuoIdsQ2YT43rzfzoGpznXO/qQZmg5VZ.png)
![](https://i.axo.im/E1hjSD7HBTUyptn7YO7Bf2EKA8UIO4SW/7Vybi41j.png)

**Comment by hanna-kn** [comment]
Fixed (if you find more issues relating to the syntax highlighting I suggest that you add a comment to issue #198 instead creating a new issue, for now until the code has stabilized).
