### ISSUE TITLE
Square degree to steradian conversion

### ISSUE THREAD

**Issue by knservis** [Qalculate/libqalculate#202]
Converting the result of the multiplication of 1 degree x 1 degree (plane angle) which is 1 degree squared to steradians gives 0.00030461742 sr^2. The magnitude is correct but the unit should be steradian, not steradian squared. This happened in qalculate-gtk so I am not sure where the error is and where the bug report belongs.

**Comment by hanna-kn** [comment]
Which version are you using?  This issue should be fixed as of version 3.5.

**Comment by knservis** [comment]
Oh ok. I used the default for Ubuntu 20.04  which is 2.8.2 (via apt). I can confirm that the snap version (3.10.0) is fixed.. Thanks for the awesome tool BTW!
