### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by kitterhuff** [Qalculate/libqalculate#203]
Hey there, I'm having a mall problem with Qalculate! GTK, every time I type dam3 it crashes, but if I type dam^3 it works just fine, it is a small problem that isn't high priority but it is a minimum inconvenience, hope you can fix it quick and easy! :) Hope anyone who reads this has a great day. Bye.

**Comment by hanna-kn** [comment]
Fixed. (It's surprising that this bug hadn't been found before.)

**Comment by kitterhuff** [comment]
The only thing surprising is that god speed thanks for your service (T.T)7
