### ISSUE TITLE
Not a bug. Just wanted to say thanks.

### ISSUE THREAD

**Issue by ernstki** [Qalculate/libqalculate#207]
Hi Hanna,

This is not a bug report. I just wanted to say thanks for `qalc`. First and foremost because it's the human-oriented time calculator I had hoped for years that someone in the world would create. I'd been relying on Wolfram Alpha in the past, and for someone who works full-time in the command line, that's just unpleasant.

My favorite way to use `qalc` goes something like

```
qalc -t <<< "10:31 + 8:30 to time"
```

I'm just thrilled I don't have to do the "minutes over sixty" math myself, nor use degrees, minutes, seconds notation. I put it in basically just like humans write it. I didn't even have to check the docs, I just tried what made sense and it worked, and it's a relief when that happens. <tt>:)</tt>

If the email address in your GitHub profile is OK to send PayPal payments to (or a payment processor of your choice), I'm happy to make a monetary donation that can be used for your preferred coding fuel: coffee, tea, beer, Club Mate, DI.FM subscription, whatever. Since I use `qalc` basically every workday, I would also be amenable to sponsoring the project through GitHub Sponsors or something like that.

Cheers.

**Comment by hanna-kn** [comment]
Thanks.

Please do not hesitate to make any suggestions for improving qalc (especially since the GUI is my main focus). Requests and suggestions (and bug reports) are primarily what drives the development of Qalculate forward.

> If the email address in your GitHub profile is OK to send PayPal payments to

It is. There is also a (PayPal) donation link at the website (https://qalculate.github.io/).

**Comment by data-man** [comment]
> Please do not hesitate to make any suggestions for improving qalc (especially since the GUI is my main focus).

Any plans for other GUI backends? E.g. ImGui or Nuklear.
Maybe in new repository, e.g. qalculate-imgui.

>- Plotting:
>- Uses Gnuplot
>- Can plot functions or data (matrices and vectors)

There is awesome [implot](https://github.com/epezent/implot) for ImGui.

**Comment by ernstki** [comment]
@hanna-kn Thanks. Will do.
