### ISSUE TITLE
Aborting long computations can crash

### ISSUE THREAD

**Issue by vvs-** [Qalculate/libqalculate#21]
Try e.g. to factor Mersenne prime 2^61-1 and then press enter to abort it. The result is a crash with this message: `terminate called without an active exception`.

**Comment by hanna-kn** [comment]
It is a known issue that the calculation thread cannot always be terminated without crashing. When this will happen is not easy to predict. A better method for terminating the display of the result has recently been implemented and something similar is planned for the actual calculation, but it will be difficult to handle all cases (factorization is however not such a case).

**Comment by hanna-kn** [comment]
Fixed.
