### ISSUE TITLE
libqalculate 3.12.0 decrements soname

### ISSUE THREAD

**Issue by ashpooljh** [Qalculate/libqalculate#211]
Apparently we have somehow transitioned from `libqalculate.so.21` in 3.11.0 to `libqalculate.so.20` in 3.12.0.
See https://travis-ci.org/github/void-linux/void-packages/jobs/712258919

As far as I understand, this might be caused by [simultaneously increasing](https://github.com/Qalculate/libqalculate/commit/d12372ebba859ff46bc0cfbea6f8edbb063166e8#diff-67e997bcfdac55191033d57a16d1408a) both revision and age.

**Comment by hanna-kn** [comment]
Oops. I forgot that current must be increased when age is increased. I realized that there actually where no interface changes and incremented revision instead. The libqalculate tarball and the v3.12.0 tag has been updated.
