### ISSUE TITLE
round doesn't behave like in documentation (command-line qalc)

### ISSUE THREAD

**Issue by miernik** [Qalculate/libqalculate#213]
In the documentation, round is supposed to work like this:

round(Value[, Number of decimals][, Round halfway to even])

However in my qalc version 3.3.0 command line, I get:

> round(2.1234,2)

round([2.1234, 2]) = [2, 2]

And I should just get 2.12

**Comment by miernik** [comment]
Actually I get the same with qalculate-gtk, see screenshot:

![qalculate-Screenshot_2020-07-31_10-05-57](https://user-images.githubusercontent.com/4380094/88992287-91ac8d00-d315-11ea-9ae4-dbe6d00389a1.png)

**Comment by miernik** [comment]
Upgraded to version 3.3.0 and its the same.

**Comment by hanna-kn** [comment]
The online manual describes version 3.12.

round(), and related functions, where updated in version 3.8.

Enter `help round` in qalc, or use the local GUI manual, and you will get the correct description for the version you use.
