### ISSUE TITLE
Parsing of commands given with / is flawed

### ISSUE THREAD

**Issue by alxpettit** [Qalculate/libqalculate#216]
When you type `base`, with no arg, it tells you this: 
```
You need at least 2 argument(s) (Number, Base) in function base().
  base() = base()
```

This is good and useful output. However, when you type `/base` instead, all you get is `Unknown command.`.

The `/` does not appear to recognize any command that is meant to have arguments, unless the arguments are provided. Similarly, using an argument where one is not meant to be provided, also prevents it from recognizing the command the user is trying to give it -- e.g. `/exact 4` gives `Unknown command.`.

Allowing `/` to recognize commands with improper args would be very useful for improving discoverability and minimizing user confusion.

**Comment by hanna-kn** [comment]
Done.

New output:
\> /base
**base** requires at least one argument.
\> /exact 4
**exact** does not accept any arguments.

**Comment by alxpettit** [comment]
Cool, thx! ^w^
