### ISSUE TITLE
is it possible to get terse output when piping the result to qalc?

### ISSUE THREAD

**Issue by arrufat** [Qalculate/libqalculate#217]
Hi, first of all, thank you for releasing these software pearl to the world!

I would like to integrate `qalc` into another program and I've managed to make it using `qalc -t` to get directly the output of the input expression.

However, for my workflow it would be better if I could pipe the result into `qalc`, but unfortunately, this is what happens:
``` bash
$ echo "2+2" | qalc -t
> 2+2

  4

>
```
the `-t` option has no effect. Could it be possible to make it respect the terse option, too?

Thanks in advance :)

**Comment by hanna-kn** [comment]
`-t` only affects output, not input. I suggest that you use the `-file` option.
``` sh
$ echo "2+2" | qalc -t -f -
4
```

**Comment by arrufat** [comment]
Perfect, that works flawlessly, thank you so much!!
