### ISSUE TITLE
Column vectors

### ISSUE THREAD

**Issue by Scibuild** [Qalculate/libqalculate#219]
Matrix multiplication between a matrix and a vector does not work as all vectors are by default row vectors:
```
> [[1,2], [3,4]] * [1,2]

  error: The second matrix must have as many rows (was 1) as the first has columns (was 2) for matrix multiplication.
  [[1, 2], [3, 4]] × [1, 2] = [[1, 2], [3, 4]] × [1, 2]
```
You can get around this issue by creating a matrix with only one column but the notation is clunky:
```
> [[1,2], [3,4]] * [[1],[2]]

  [[1, 2], [3, 4]] × [[1], [2]] = [[5], [11]]
```
It would be nice if either by default all vectors were column vectors or at least there were some function `colvector` for example that could do this conversion.

**Comment by hanna-kn** [comment]
It does indeed make more sense to consider the vector a column vector for matrix multiplication.

The matrix function can used instead of square brackets (or parenthesis):
`[[1,2], [3,4]] * [[1],[2]]` = `((1,2),(3,4)) * matrix(2,1,1,2)` = `matrix(2,2,1,2,3,4) * matrix(2,1,1,2)`
