### ISSUE TITLE
Always show fixed point instead of scientific representation for float point numbers

### ISSUE THREAD

**Issue by amosbird** [Qalculate/libqalculate#220]
Hello, is there a way to configure the representation of float-point numbers? I'd like to always view them as xxx.yyy

**Comment by hanna-kn** [comment]
I'm not entirely sure what you mean by fixed point and xxx.yyy in this context.

To disable scientific notation in qalc use the command `set exp 0` (or `set scientific notation off`) or the command line option `-s "exp 0"` (use Mode->Numerical Display->Simple in the GUI and PrintOptions::min_exp in the library API).

For a list of available options in qalc use to command `help set` or read the man page (`man qalc`).

**Comment by amosbird** [comment]
@hanna-kn Cool. Can I configure qalc via `$HOME/.config/qalculate/qalc.cfg` ?

**Comment by hanna-kn** [comment]
> Can I configure qalc via $HOME/.config/qalculate/qalc.cfg ? As I don't see any related settings you mentioned...

The settings in qalc.cfg use option names that are a bit different, e.g. min_exp instead of exp (or "scientific notation"), and min_deci/max_deci and use_min_deci/use_max_deci instead of mindeci/maxdeci ("max decimals"/"min decimals").

**Comment by amosbird** [comment]
Thanks!
