### ISSUE TITLE
Wrong answer to arccot(0)

### ISSUE THREAD

**Issue by donCESAR12345** [Qalculate/libqalculate#223]
The calculator gives a wrong answer to this inverse trigonometric function, it should be 90° or π/2, and it gives (i × ln(−i ∕ 0)) ∕ 2 − (i × ln(i ∕ 0)) ∕ 2, which is obviously a division by zero, please fix it.

![image](https://user-images.githubusercontent.com/64916276/92783431-603ecc80-f36b-11ea-9735-960c37a9fb10.png)

**Comment by hanna-kn** [comment]
Fixed.
