### ISSUE TITLE
Bug with Constants (euler, pi, maybe more) and with the Scientific Notation Symbol (E)

### ISSUE THREAD

**Issue by Rj-mwe** [Qalculate/libqalculate#224]
I use **Qalculate! (GTK +)**
in **version 3.12.1**
on the **GNU / Linux** operating system **Lubuntu 19.10 (Eoan Ermine)**.

- I noticed something strange when typing the following expression: eE2,
where "e = Euler constant" and "E2 = 10 ^ 2". The resulting value is always 0.

- When only the Euler constant is replaced by its value (2.7182818), the calculation is successful and the expected result is achieved: 271.82818

- Also, when only the scientific notation E2 is replaced by its value (100) or expression (10²), the expected result is achieved.

- This also happens with the PI constant.
Even if you put the constant in parentheses, give space, the same happens.

Thanks in advance for your time and consideration. Qalculate! it's great software.
Note: I am new to the field of calculations, I still know very little.

Here are the screen prints:

![Qalculate error 1](https://user-images.githubusercontent.com/62312701/93541426-d1165380-f92c-11ea-9980-ba77c4c63e14.jpg)

![Qalculate error 3](https://user-images.githubusercontent.com/62312701/93541954-328af200-f92e-11ea-8860-08e9ee5a2f25.jpg)

![Qalculate error 2](https://user-images.githubusercontent.com/62312701/93541450-de334280-f92c-11ea-8981-c75f40dca4be.jpg)

**Comment by hanna-kn** [comment]
This has now been fixed. E2, without preceding, will be interpreted as 1E2 (10^2). 
The primary issue was that no error message was shown (E2 was silently interpreted as 0E2)

**Comment by hyiltiz** [comment]
Seemed relevant.

```
~ $ qalc 'pi'
pi = approx. 3.1415927
~ $ qalc 'i'
i = i
~ $ qalc 'i*i'
i * i = -1
~ $ qalc 'e(1)'
e * 1 = approx. 2.7182818
~ $ qalc 'exp(1)'
exp(1) = approx. 2.7182818
~ $ qalc 'exp(pi*i)'
exp(pi * i) = -1
~ $ qalc 'e(pi*i)'
e * (pi * i) = approx. 8.5397342i
~ $ qalc --version
2.8.2
```

**Comment by hanna-kn** [comment]
> Seemed relevant.

How?

exp(x) is equivalent to e^x (natural exponential function).
e(x) is equivalent to e × x.
e is case sensitive (lower-case e surrounded by digits is however interpreted as scientific notation, as upper-case E).

**Comment by hyiltiz** [comment]
Oh no! I did not realize `e` is a constant and `e(1)` is just multiplication, not function application. Sorry about the false alarm.
