### ISSUE TITLE
Lumen converts to Candela?

### ISSUE THREAD

**Issue by davidfg4** [Qalculate/libqalculate#226]
Consider this output:
```
$ ./qalc --version
3.13.0
$ ./qalc          
> lm * m / m      

  (lumen × meter) / meter = 1 cd

> lm * m / m to lm

  (lumen × meter) / meter = 1 lm/sr

> lm * (m / m)    

  lumen × (meter / meter) = 1 lm
```
For all of these equations, I would expect the result to be 1 lumen. It seems incorrect to get a candela, but is this somehow the expected result?
From the info a lumen is defined as a `cd·sr`, a sr/steradian is a `rad^2`, and a radian is defined as `m/m`. I'm guessing something about how radian is defined is throwing it off?

As a more complete example, I am trying to calculate the total lumen output of a light which has a circular beam with an angle of 25 degrees, and 4500 lux at 1 meter. In this example I would also expect to get lumens not candela:
```
> pi*(tan(25 degrees / 2)*meter)^2*(4500 lux)   

  pi × ((tan((25 × degree) / 2) × meter)^2) × (4500 × lux) ≈ 694.8208808 cd

```

**Comment by hanna-kn** [comment]
Radians and other dimensionless units are causing a lot of problems.

I will define rad as a base unit for now and add special case for conversion of rad and related units to length ratios (e.g. m/m).

**Comment by davidfg4** [comment]
After a manual build and install, I can verify that this works for me, at least in this case:
```
» ~/libqalculate (master) /usr/local/bin/qalc --version
3.13.0
» ~/libqalculate (master) /usr/local/bin/qalc          
> info rad

Unit:				Radian
Names:				rad / radian / radians

> lm * m / m

  (lumen × meter) / meter = 1 lm

> pi*(tan(25 degrees / 2)*meter)^2*(4500 lux)

  pi × ((tan((25 × degree) / 2) × meter)^2) × (4500 × lux) ≈ 694.8208808 lm

> 
```
Amazing, thanks for looking at this!
