### ISSUE TITLE
Discrepancies between try exact and approximate

### ISSUE THREAD

**Issue by vvs-** [Qalculate/libqalculate#23]
I'm not sure if this was intended or an oversight. The display of a result in `try exact` and `approximate` mode is different for calculations with approximate numbers. Try e.g.:
```
set approximation approximate
pi/2
save v
cos(v*rad)
approximate
```

**Comment by hanna-kn** [comment]
It is partly intentional. It is caused by a workaround to avoid `cos(pi/2) ≈ 5,4845872E-78` in approximate mode.

**Comment by vvs-** [comment]
That's the reason why I'm asking. This issue is about a possible bug, so if it's intentional the issue should be probably documented and closed. I leave that to your discretion.
