### ISSUE TITLE
Problem with Power and Chain Rule

### ISSUE THREAD

**Issue by Besnn** [Qalculate/libqalculate#232]
Pretty sure the program can't handle expressions like d/dx (sec(5x))^3 or d/dx (tan(9x^2))^5.

**Comment by hanna-kn** [comment]
What's wrong with
```
> diff(sec(5x)^3)
= (15 × tan(5x)) / cos(5x)^3

> diff(tan(9x^2)^5)
= 90x × tan(9x^2)^6 + 90x × tan(9x^2)^4

> integrate(90x × tan(9x^2)^4×sec(9x^2)^2)
= tan(9x^2)^5 + C
```

The program does however not understand the d/dx syntax.

**Comment by Besnn** [comment]
I always use the diff() syntax but you're right: it seems to do some conversions of its own but the result is correct nonetheless. Great job btw.
