### ISSUE TITLE
[Feature request] Approximation dual mode (exact and approximated result)

### ISSUE THREAD

**Issue by Nudin** [Qalculate/libqalculate#233]
Currently, you can switch how the results should be shown by setting the mode to "approximate", "exact" or "try exact". It would however be great to have a hybrid/dual mode, in which both the exact result and the approximate solution is shown. Here is how I would imagine that to work:
```
> 1/6+3/7

  (1 / 6) + (3 / 7) = 25/42 ≈ 0,5952380952
```
This way it would not be necessary to switch for and back between the modes, but one would always have all the information one needs.

**Comment by hanna-kn** [comment]
I have considered implementing a default mode where multiple results/formats which might be of interest to the user (depending on the format of the original expression) are returned. I've however primarily tinkered with this in GUI, where size constraints is a factor and toggle buttons easily can be used for quick format changes.

The difference between 25/42 and 0,5952380... is actually not approximate or exact mode, but the rational number format. Exact mode by default activates exact decimal fractions.

In the example it is obvious that 25/42 might be of interest to the user, but in other cases it might be less relevant.

When the result does not differ from the original expression only the opposite format should be returned (e.g. 1/4=0,25, 0,25=1/4), if the expression contains decimals only decimal fractions should be returned (e.g. 1,25/3=0,45), if the result contains units only decimal fractions are likely of interest (with some exceptions, e.g. 3/8 inches), etc.

In cases where the numerator is higher than the denominator mixed fractions might also be relevant (e.g. 4/6+3/7=1+2/21=23/21≈1.095 238).

Exact mode might also return answers with functions and variables (e.g. ln(25)=2\*ln(5), sqrt(52)=2\*sqrt(13), asin(1)=0,5pi). These might become quite convoluted and possibly distracting for the average user.

**Comment by hanna-kn** [comment]
The dual/automatic fraction mode is finished. A dual approximation mode will however require considerably more thought. I've however added a keyboard shortcut for exact/approximate mode (Ctrl+E) which should improve efficiency.

**Comment by hanna-kn** [comment]
Dual and automatic approximation are now also finished. Auto fraction mode and approximation are now default settings.

**Comment by NPN** [comment]
For me, Ctrl-E is always handy for editing long lines, so I was surprised by the recent change. Personally, I think it could be good to change to a different keybinding or make this configurable.

That being said, the default readline keybindings have something assigned to almost every Ctrl combination, so any default could impact somebody (e.g. I never use Ctrl-B, so I'd suggest that, but someone else might use it all the time). A configurable keybinding is the most flexible, but that is extra work.

Overall, it's not a big deal (I can patch it out), but I just wanted to leave a note in case other people feel the same way.

**Comment by hanna-kn** [comment]
> For me, Ctrl-E is always handy for editing long lines, so I was surprised by the recent change. Personally, I think it could be good to change to a different keybinding or make this configurable.

I've now changed the behaviour so that the new keybindings are only used if the current input is empty (otherwise Ctrl+E moves the cursor to the end of the line).

Some key combinations are not possible to override (e.g. if Ctrl+S is bound in readline, it will still freeze the terminal).
