### ISSUE TITLE
Matrix multiplication does not execute with variables

### ISSUE THREAD

**Issue by Scarabytes** [Qalculate/libqalculate#235]
I tried doing matrix multiplication, but qalculate executed element-wise multiplication instead. Maybe I did something wrong, but I'm pretty sure this is a bug.

**How to reproduce:**
- Qalculate Version 3.14.0 with default settings
- Create a Matrix and store it in a variable (Apparently, non-rational numbers are needed to reproduce this. Rotation matrices caused the error for me. It works fine with an identity matrix)
  `T:=[[cos(30);-sin(30);0];[sin(30);cos(30);0];[0;0;1]]`
- Create a vector and store it in a variable
  `v := [[4];[0];[10]]`
- Attempt to multiply said matrix and vector
  `T⋅v`

The **result** is a vector of matrices instead of a vector of numbers:
  `≈ [[[[3,464102; −2; 0]; [2; 3,464102; 0]; [0; 0; 4]]]; [[[0; 0; 0]; [0; 0; 0]; [0; 0; 0]]]; [[[8,660254; −5; 0]; [5; 8,660254; 0]; [0; 0; 10]]]]`
  instead of the **expected** correct result acquired by not using variables:
  `[[cos(30); -sin(30); 0]; [sin(30); cos(30); 0]; [0; 0; 0]]⋅[[4]; [0]; [10]]
  ≈ [[3,464102]; [2]; [0]]`

**Comment by hanna-kn** [comment]
Fixed.

This issue only affects matrix multiplication with approximate variables and a possible workaround is thus to store the corresponding exact value.

**Comment by Scarabytes** [comment]
Ok, how would I do that? I thought, simply typing the equations in used the exact value internally automatically.

**Comment by hanna-kn** [comment]
> Ok, how would I do that? I thought, simply typing the equations in used the exact value internally automatically.

The ":=" syntax calculates the value (using the current approximation mode) before saving it (I'm unsure if this behaviour is optimal, but it avoids possible efficiency issues). The simplest alternative is to activate exact mode before storing the value (using "Exact" button in GUI, or "exact" command in qalc).

**Comment by Scarabytes** [comment]
Alright, that makes sense.
Thanks a lot for the explanation!

**Comment by hanna-kn** [comment]
I've now changed the behaviour of the save() function and consequently also of `:=` (the value will not be evaluated).
