### ISSUE TITLE
The degree sign (°) in matrix expressions messes up parsing

### ISSUE THREAD

**Issue by Scarabytes** [Qalculate/libqalculate#236]
When entering the degree sign, matrix expressions receive additional brackets or are otherwise parsed incorrectly.

**How to reproduce:**
- Qalculate 3.14.0, default settings
- `cos(30°)` is parsed correctly as `cos(30 ⋅ degree)`
- `[cos(30°); -sin(30°)]` is also interpreted correctly as `[cos(30 ⋅ degree); −sin(30 ⋅ degree)]`
- However, `[[cos(30°); -sin(30°)]; [sin(30°); cos(30°)]]` receives one additional pair of brackets and is therefore interpreted incorrectly: `[[[cos(30 ⋅ degree); −sin(30 ⋅ degree)]; [sin(30 ⋅ degree); cos(30 ⋅ degree)]]]`  
  This especially causes problems when trying to store the matrix to local variables, as the save function is called incorrectly:
  `M := [[cos(30°); -sin(30°)]; [sin(30°); cos(30°)]]` is parsed as `save([[[[cos(30 ⋅ degree); −sin(30 ⋅ degree)]; [sin(30 ⋅ degree); cos(30 ⋅ degree)]]]; 0])` and subsequently causes the error `You need at least 2 argument(s) (Value; Name) in function save().`

If I did anything wrong, please let me know; otherwise I'd be glad if this bug gets fixed. Thank you!

**Comment by hanna-kn** [comment]
Fixed.

**Comment by Scarabytes** [comment]
Thank you!
