### ISSUE TITLE
"now" variable is incorrect

### ISSUE THREAD

**Issue by circcc** [Qalculate/libqalculate#237]
"now" variable is incorrect.
This is Korea(GMT+9), but it is displayed in GMT.
by the way, "today","tomorrow","yesterday" variable is correct.
my os is windows 7 korean x86.
![2020-11-07_044837](https://user-images.githubusercontent.com/72944033/98409138-a7201880-20b5-11eb-81e3-e7c4c0975939.png)

**Comment by hanna-kn** [comment]
Fixed.
