### ISSUE TITLE
Defining functions in qalc

### ISSUE THREAD

**Issue by belanger** [Qalculate/libqalculate#24]
I'm just starting to use it, and qalc is utterly fantastic.  

The documentation seems a bit lacking, though.  The documentation for qalculate is complete, but it doesn't always say how to do something in qalc.  For example, I found out that a variable can be given a value with the := operator, but the qalculate manual only mentions using the menus.   
I haven't figured out how to define a function, though.  Is it possible to do that in qalc?

**Comment by hanna-kn** [comment]
It is not possible at the moment (unless you count `function()`). You can however define a function in the GUI (qalculate-gtk) and use it in qalc. It should however be easy for me to implement a simple `function NAME EXPRESSION` command without the ability to define argument types, conditions, sub-functions, etc.

qalc is not documented specifically in the manual at all.  `help` and `help COMMAND` should however give enough information in most cases.

**Comment by hanna-kn** [comment]
`function NAME EXPRESSION` (and `variable NAME EXPRESSION`) command has now been added to qalc.

**Comment by belanger** [comment]
Wow; that's fantastic.  Thanks!
