### ISSUE TITLE
Gui filled with placeholder text (version 3.16.1)

### ISSUE THREAD

**Issue by Burntninjas** [Qalculate/libqalculate#248]
![image](https://user-images.githubusercontent.com/59216157/106937279-305de000-66e3-11eb-8511-b82f25ecf107.png)

**Comment by Burntninjas** [comment]
It happened after installing it, possibly a hardware issue on my side.

**Comment by hanna-kn** [comment]
How and on what operating system/distribution did you install it?

**Comment by Burntninjas** [comment]
I installed it on Windows 10 20h2, my computers hard-drive died not long after. I've been having issues with it for a while.
