### ISSUE TITLE
Don't die on ctrl-c (SIGINT)

### ISSUE THREAD

**Issue by baltitenger** [Qalculate/libqalculate#249]
In bash I usually press ctrl-c if I want to abort a line, but `qalc` just dies if I press ctrl-c, not even storing the history for that session.

**Comment by hanna-kn** [comment]
SIGINT (Ctrl+C) is currently not catched. I am unsure how the signal should be handled in qalc.

I personally find it quite useful to use Ctrl+C to immediately close qalc immediately, without saving preferences.

Many REPLs does not even exit on SIGINT and instead terminate the current line/command.

The usage of Ctrl+D is much more consistent.

**Comment by alexmo1997** [comment]
Thanks, that's great!
