### ISSUE TITLE
Trashed parser response

### ISSUE THREAD

**Issue by vvs-** [Qalculate/libqalculate#25]
Try
```
set unknowns off
xyz
set base 10
set angle unit rad
```
The response from a previous error is repeated every time.

**Comment by hanna-kn** [comment]
I do not see anything strange. 

If you get an error when calculating `xyz` (which means that are other settings that are non-default as `set unknowns off` only affect _automatic_ unknown variables and not those that are predefined), than it should not be repeated with `set base 10` which repeats the display of the result, but it should be repeated `set angle unit rad` which changes the way the expression is interpreted/calculated and thus triggers reparsing and recalculation of `xyz`.

**Comment by vvs-** [comment]
Technically speaking, yes, that's true. But for an ordinary user it looks confusing, superfluous and inconsistent. Similar problem occurs when syntax is changed between infix and RPN. Maybe it'd be better to clear expression buffer after reporting such error. That's merely cosmetic and not a serious issue, of course.

**Comment by hanna-kn** [comment]
I do not think it's a good to change the behaviour after an error. The main problem is that the previous expression is always reparsed and recalculated. In the GUI when for example the syntax is changed between infix and RPN the expression, the expression is not automatically reparsed or recalculated. Instead the result is cleared (which should not be necessary in qalc). It is probably also a good idea to avoid unnecessary reparsing when only calculation settings have changed. These changes will unfortunately not fix the repeated error when the angle unit is changed.

**Comment by hanna-kn** [comment]
I think I've managed to fix this issue.

The expression is now not always reparsed and recalculated when parsing options are changed, and parsing errors/warnings are hidden when options only affecting calculation or angle unit have changed.

**Comment by vvs-** [comment]
Thanks.
