### ISSUE TITLE
Feature request: variables (and/or numbers) in unit expressions

### ISSUE THREAD

**Issue by renyhp** [Qalculate/libqalculate#251]
This would allow conversions like `electron_mass to GeV/c^2` to work.

**Comment by hanna-kn** [comment]
Variables with corresponding units should work in unit expressions (including your example), in recent versions.
```
> electron_mass to GeV/c^2

  electron_mass ≈ 0.000510998950 GeV/c²
```

Numbers are currently not supported and other variables are only supported when alone. For unsupported cases plain division always works (e.g. `(2.2 us)/(planck/(2*pi*GeV)) ≈ 3.342388385E18`)

**Comment by renyhp** [comment]
Oh! My bad. I had installed qalc through apt, and it looks like it's some two years old... Is there no up-to-date ppa? I'm staying away from snap, and after installing the flatpak I couldn't run qalc on the command line; I had to install the binary, but it looks like I'll have to update manually...
