### ISSUE TITLE
Hidden (?) prime factorization function

### ISSUE THREAD

**Issue by tethragon** [Qalculate/libqalculate#252]
Hi and congratulation for the best calculator EVER! I mean it!!!

I use version qalculate! 3.17.0 (Linux Mint) and I was looking for a function for prime factorization. I wasn't able to find one and when I tried to type "factor", autocomplete function was only showing "factorials" functions as available. 

However if I continue and type "factor(126)" and press enter then the program outputs the correct answer "2x3^2x7". This means that even though there is a factorize function available it is not shown by autocomplete. This may confuse some users who try to factorize a number. 

Please see attached video.

https://user-images.githubusercontent.com/39238674/108590468-6d290880-736c-11eb-9431-325cacd1d0ab.mp4

**Comment by hanna-kn** [comment]
`factor [expression]` is an alternative to the recommended syntax `[expression] to factors` (or `[expression]->factors`). `factor`is not a function (a factorization function would return a vector/array of factors). The result can also be factorized using various menu items and buttons.

**Comment by tethragon** [comment]
thank you! Apparently I didn't know the proper syntax

**Comment by rickhg12hs** [comment]
> `factor [expression]` is an alternative to the recommended syntax `[expression] to factors` (or `[expression]->factors`). `factor`is not a function (a factorization function would return a vector/array of factors). The result can also be factorized using various menu items and buttons.

Is there a function that would return a vector/array of factors with multiplicity?
