### ISSUE TITLE
CLI: interactively ask for unknown variables

### ISSUE THREAD

**Issue by eadmaster** [Qalculate/libqalculate#255]
e.g.:
````
$ qalc "gcd(n1, n2)"
error: "n1" is not a valid variable/function/unit.
error: "n2" is not a valid variable/function/unit.
error: Argument 1, 1st value, in gcd() must be a free value that is rational (polynomial).
gcd(0, 0) = gcd(0, 0)
````

With interactive prompts:
````
$ qalc "gcd(n1, n2)"
n1? 4 <user type a value here>
n2? 6 <user type a value here>
gcd(4, 6) = 2
````

**Comment by hanna-kn** [comment]
I do not think that it is good idea to do this by default. A more likely implementation would require the user to enter a command in qalc.

You can already use `qalc "gcd('n1', 'n2') where 'n1'=4 and 'n2'=6"` (more efficient variants are `qalc "gcd(\n, \m) where \n=4 and \m=6"` and `qalc "gcd(x,y)/.x=4,y=6"`).

With default settings `qalc "gcd(n1, n2)"` currently returns `gcd(n × 1, n × 2) = n`.

**Comment by eadmaster** [comment]
thank you for your tips, i'll just use the [`read` command](https://en.wikipedia.org/wiki/Read_(Unix)) in my scripts for this.
