### ISSUE TITLE
In results, use "kg" instead of "mt"

### ISSUE THREAD

**Issue by genodeftest** [Qalculate/libqalculate#256]
Steps to reproduce:
1. execute `$ qalc "(700t/1ha)×(1m^2)"`
2. watch result

Observed result:
```
((700 × tonne) / (1 × hectare)) × (1 × (meter^2)) = 70 mt
```

Expected result:
```
((700 × tonne) / (1 × hectare)) × (1 × (meter^2)) = 70 kg
```

`kg` is more conventional than `mt`.

Version info:
`libqalculate-3.17.0-1.fc33.x86_64`

**Comment by hanna-kn** [comment]
By default units are not converted if a less complex unit expression is not available. You can currently change this either by explicitly conversion (e.g qalc "(700t/1ha)×(1m^2)->kg"), or change the "autoconversion" (or "conv") setting to "optimalsi" (3).

I do however agree that milli is a very odd prefix for tonne, and I should implement a specific solution for this case.
