### ISSUE TITLE
Allow shortening currency units with k

### ISSUE THREAD

**Issue by arthurk** [Qalculate/libqalculate#258]
Instead of entering "200000 THB to USD" it would be great to just enter "200k THB to USD", it would make it easier to double-check the number instead of counting zeros

Current behaviour:
```
qalc "200k THB to USD"
error: Trailing characters "k" (not a valid variable/function/unit) in number "200k" was ignored.
200 × THB ≈ $6.395861693
```

**Comment by hanna-kn** [comment]
It works if you remove the space between k and THB (e.g. `qalc "200 kTHB to USD"`).

**Comment by arthurk** [comment]
I just tried this out in 3.18 and it works great. thanks a lot for fixing this
