### ISSUE TITLE
[Feature] Weighted Averages

### ISSUE THREAD

**Issue by solonovamax** [Qalculate/libqalculate#259]
## Feature Description
Calculation of weighted averages.

### What Problem Does This Solve?
There currently exists the `mean()`/`average()` function which can be used to calculate the unweighted average of something.
But sometimes you want to calculate a weighted average of some elements, and it's inconvenient to have to open up excel and paste your data in.

### A Solution You'd Like
So, access to a `weightedmean()`, `wmean()`, `weightedaverage()`, or `waverage()` function would be nice.

---

### Ways this could be implemented
So there's a few ways this could be implemented. I'll list out each one and discuss advantages/disadvantages
#### 1. Input is a vector of vectors. Each subvector has 2 elements. The first is the value, the second is the weight.
   So if you had the input `[[1;10];[2;5]]`, then you would have the elements: `1` with a weight of `10` and `2` with a weight of `5`. (Optionally, remove the outer vector so the input is just `[1;10];[2;5]` and the function takes a vararg.)
   - Advantages:
      - Simple to understand
   - Disadvantages:
      - Not intuitive (you might not do it right without reading the docs)
      - Easy to mess up (by have 3 elements in one of the sub vectors/having only 1 element in one of the sub vectors/etc.)
      - Looks like shit
      - Difficult to explain in the ""function preview"" thing in Qalculate-gtk. ([The "Parsed expression" box](https://qalculate.github.io/manual/qalculate-user-interface.html#qalculate-main-window))
#### 2. Input is 2 vectors of the same length. The indexes are used to tie values to weights.
   So if you had the input `[1;2]` and `[3;7]`, then you'd have the elements: `1` with a weight of `3` and `2` with a weight of `7`.
   - Advantages:
      - Simple to understand
      - Easy to explain in the ""function preview"" thing in Qalculate-gtk. ([The "Parsed expression" box](https://qalculate.github.io/manual/qalculate-user-interface.html#qalculate-main-window))
   - Disadvantages:
      - Hard to keep track of which value has which weight.
         - If you add a value/weight, you could accidentally offset all of them.
      - Not intuitive (you might not do it right without reading the docs)
#### 3. Input is a vector of vectors. Each subvector as 2 elements, first is value and second is weight. BUT a custom keyword `to` is introduced which allows you to construct key-value pairs/vectors of length 2 in simpler way.
   So if you had the input `[1 to 7; 2 to 8]` (it would be functionally equivalent to `[[1;7];[2;8]]` in implementation. This would just be a shorthand for constructing vectors of length 2.), then you would have the elements: `1` with a weight of `7` and `2` with a weight of `8`. (Optionally, remove the outer vector so the input is just `1 to 7; 2 to 8` and the function takes a vararg.)
   - Advantages:
      - Simple to understand
      - Intuitive
      - Easy to diffrentiate & pair values/wieghts together.
   - Disadvantages:
      - Requires adding a new keyword/function.
      - Might be difficult to explain in the ""function preview"" thing in Qalculate-gtk. ([The "Parsed expression" box](https://qalculate.github.io/manual/qalculate-user-interface.html#qalculate-main-window))
#### 4. Input is a list of mixed key and value pairs, with no determined length. The only requirement is that the length must be a multiple of 2. The first element is the value, second is the weight. This pattern is repeated infinitely.
   So if you had the input `1;4;2;3`, then you would have the elements: `1` with a weight of `4` and `2` with a weight of `3`.
   - Advantages
      - Simple to understand
      - Semi intuitive
   - Disadvantages:
     - Not fully intuitive
     - If it's long enough, then you can lose track if which number is a weight/value.

If you have any other/better suggestions, feel free to add on.
But what I'm noticing so far is that it's less of choosing one with the best advantages and more of choosing the one with the least disadvantages.

**Comment by hanna-kn** [comment]
There already is a weighmean() function (I do not remember why this name was chosen) with 2 vectors as input (e.g. (weighmean([1;2];[3;7]) = 1.7).

Variants 1, 2, 4 are easily implemented using the sum() function (e.g. `sum(element(\x;\i×2−1)×element(\x;\i×2);1;elements(\x)/2;\i)/sum(element(\x;\i×2);1;elements(\x)/2;\i)` for variant 4).

**Comment by solonovamax** [comment]
Ah, I completely missed it when I was looking lmao

gg moment
