### ISSUE TITLE
Missing functions for manupulating stack in RPN mode

### ISSUE THREAD

**Issue by vvs-** [Qalculate/libqalculate#26]
Every RPN calculator should have at least swap and duplicate top operations. Some provide rotate stack as well. Without such functions it's very difficult to arrange ordinary calculations without resorting to memory variables. But these are not part of a stack machine.

**Comment by hanna-kn** [comment]
Swap command (swaps values on the top of stack or values with the specified indices) has now been added. More will follow.

**Comment by hanna-kn** [comment]
"Pop", "copy", "rotate", "move" commands have not also been added. 

Next on the task list are enhanced stack manipulation in the GUI and integration of the stack and syntax.
