### ISSUE TITLE
Plural forms in translations

### ISSUE THREAD

**Issue by idamir** [Qalculate/libqalculate#260]
Hello,

I am working on the Russian translation of the libqalculate and found that plural forms are supported quite weakly buy '(s) forms. As far as gettext supports plural forms, I suggest using them. For example, Russian has 4 plural forms:
- for 21, 31, 41 etc,
- for 2, 3, 4, 22, 23, 24, 32, 33, 34 etc,
- for 5, 6, 7, 8, 9, 10, 11, 12-19, 25-29, 35-39 etc,
- for 1 only.

The patch that add plural forms support is attached. All translations must be reviewed to add plural forms as well.

[use_plural_forms.patch.gz](https://github.com/Qalculate/libqalculate/files/6269383/use_plural_forms.patch.gz)

**Comment by hanna-kn** [comment]
Your patch (with some minor modifications and additions) has been applied.
