### ISSUE TITLE
ENABLE_NLS

### ISSUE THREAD

**Issue by idamir** [Qalculate/libqalculate#261]
In some cases (build in Debian) ENABLE_NLS variable is not defined, and translations do work neither in qalc program nor in libqaclulate library.
I found that the simplest way is defining it in m4 preprosessing.
[define-ENABLE_NLS.patch.gz](https://github.com/Qalculate/libqalculate/files/6269407/define-ENABLE_NLS.patch.gz)

**Comment by hanna-kn** [comment]
I added ENABLE_NLS definition directly to configure.ac instead.
