### ISSUE TITLE
how to change the qalc ouput multiplication/division symbols?

### ISSUE THREAD

**Issue by Anangaya** [Qalculate/libqalculate#262]
I tried "set mulsign 2" option but it didn't do anything. Some help would be really appreciated 🙏

**Comment by hanna-kn** [comment]
Unicode must be enabled (it is enabled by default on all platforms except Windows, where Unicode support is unreliable).

**Comment by Anangaya** [comment]
Thanks 😄

**Comment by SeryiBaran** [comment]
> Unicode must be enabled (it is enabled by default on all platforms except Windows, where Unicode support is unreliable).

Even in powershell+windows terminal?((
