### ISSUE TITLE
save history when closing via SIGINT

### ISSUE THREAD

**Issue by nycex** [Qalculate/libqalculate#263]
I was a bit confused as sometimes when I close qalc, the history doesn't get saved and sometimes is does. So I looked into it and it seems like the history is not saved if you close it via ^C but it is if you close it with ^D.

I think it would be reasonable to save the history, even if ^C is meant for stopping an application, since ^C is very commonly used to close REPLs gracefully.

**Comment by hanna-kn** [comment]
SIGINT (^C) is currently catch. I am unsure how the signal should be handled in qalc.

I personally find it quite useful to use Ctrl+C to immediately close qalc immediately, without saving preferences.

Many REPLs does not even exit on SIGINT and instead terminate the current line/command.

The usage of Ctrl+D is much more consistent.
