### ISSUE TITLE
fixpo/remove-untranslated.cc generates incorrect translate for linearfunction

### ISSUE THREAD

**Issue by idamir** [Qalculate/libqalculate#269]
Output:
`> info linearfunction`
`Функция: Найти линейную функцию`
`линфункция(x1; y1; x2; y2)`
`linearfunction`
`Finds the linear function for the straight line between two distinct points.`
`Аргументы`
`x1: произвольное значение`
`y1: произвольное значение`
`x2: произвольное значение`
`y2: произвольное значение`
`Выражение: (\a-\y)/(\z-\x)*("x"-\x)+\y`

Check po files:
`$ pwd`
build/libqalculate/po-defs

`$ grep -C2 'Finds the linear function for' ./*po`
es.po-#: ../data/functions.xml.in.h:916
es.po-msgid ""
es.po:"Finds the linear function for the straight line between two distinct points."
es.po-msgstr ""
es.po-"Halla la función lineal para la línea recta entre dos puntos distintos."
--
fr.po-#: ../data/functions.xml.in.h:916
fr.po-msgid ""
fr.po:"Finds the linear function for the straight line between two distinct points."
fr.po-msgstr ""
fr.po-"Trouve la fonction affine pour la ligne droite passant entre deux points "
--
nl.po-#: ../data/functions.xml.in.h:916
nl.po-msgid ""
nl.po:"Finds the linear function for the straight line between two distinct points."
nl.po-msgstr ""
nl.po-"Bepaalt de lineaire functie voor de rechte lijn tussen twee verschillende "
--
ru.po-#: ../data/functions.xml.in.h:936
ru.po-msgid ""
ru.po:"Finds the linear function for the straight line between two distinct points."
ru.po-msgstr ""
ru.po-"Находит линейную функцию для прямой линии, проходящую через две разные точки."
--
sv.po-#: ../data/functions.xml.in.h:916
sv.po-msgid ""
sv.po:"Finds the linear function for the straight line between two distinct points."
sv.po-msgstr ""
sv.po-"Finner den linjära funktionen för den räta linjen mellan två distinkta "
--
zh_CN.po-#: ../data/functions.xml.in.h:916
zh_CN.po-msgid ""
zh_CN.po:"Finds the linear function for the straight line between two distinct points."
zh_CN.po-msgstr "寻找过两点的直线的线性函数"
zh_CN.po-

Check fixed po files:
`$ grep -C2 'Finds the linear function for' ./fixed/*po`
./fixed/es.po-#: ../data/functions.xml.in.h:916
./fixed/es.po-msgid ""
./fixed/es.po:"Finds the linear function for the straight line between two distinct points."
./fixed/es.po-msgid ""
./fixed/es.po:"Finds the linear function for the straight line between two distinct points."
./fixed/es.po-"Halla la función lineal para la línea recta entre dos puntos distintos."
./fixed/es.po-
--
./fixed/fr.po-#: ../data/functions.xml.in.h:916
./fixed/fr.po-msgid ""
./fixed/fr.po:"Finds the linear function for the straight line between two distinct points."
./fixed/fr.po-msgid ""
./fixed/fr.po:"Finds the linear function for the straight line between two distinct points."
./fixed/fr.po-"Trouve la fonction affine pour la ligne droite passant entre deux points "
./fixed/fr.po-"distincts."
--
./fixed/nl.po-#: ../data/functions.xml.in.h:916
./fixed/nl.po-msgid ""
./fixed/nl.po:"Finds the linear function for the straight line between two distinct points."
./fixed/nl.po-msgid ""
./fixed/nl.po:"Finds the linear function for the straight line between two distinct points."
./fixed/nl.po-"Bepaalt de lineaire functie voor de rechte lijn tussen twee verschillende "
./fixed/nl.po-"punten."
--
./fixed/ru.po-#: ../data/functions.xml.in.h:936
./fixed/ru.po-msgid ""
./fixed/ru.po:"Finds the linear function for the straight line between two distinct points."
./fixed/ru.po-msgid ""
./fixed/ru.po:"Finds the linear function for the straight line between two distinct points."
./fixed/ru.po-"Находит линейную функцию для прямой линии, проходящую через две разные точки."
./fixed/ru.po-
--
./fixed/sv.po-#: ../data/functions.xml.in.h:916
./fixed/sv.po-msgid ""
./fixed/sv.po:"Finds the linear function for the straight line between two distinct points."
./fixed/sv.po-msgid ""
./fixed/sv.po:"Finds the linear function for the straight line between two distinct points."
./fixed/sv.po-"Finner den linjära funktionen för den räta linjen mellan två distinkta "
./fixed/sv.po-"punkter."
--
./fixed/zh_CN.po-#: ../data/functions.xml.in.h:916
./fixed/zh_CN.po-msgid ""
./fixed/zh_CN.po:"Finds the linear function for the straight line between two distinct points."
./fixed/zh_CN.po-msgid ""
./fixed/zh_CN.po:"Finds the linear function for the straight line between two distinct points."
./fixed/zh_CN.po-
./fixed/zh_CN.po-#: ../data/functions.xml.in.h:917

All *.po files have the same issue: msgid tag is repeated twice, while msgstr one is missing, but takes place in the original translations.
--------------8<--------------
#: ../data/functions.xml.in.h:936
msgid ""
"Finds the linear function for the straight line between two distinct points."
msgid ""
"Finds the linear function for the straight line between two distinct points."
"Находит линейную функцию для прямой линии, проходящую через две разные точки."
-------------->8--------------

**Comment by hanna-kn** [comment]
Fixed (this issue affected translations of definition messages with multiple rows).
