### ISSUE TITLE
libqalculate.so.6 : No such file or directory

### ISSUE THREAD

**Issue by HoracioDos** [Qalculate/libqalculate#27]
Hello!
I've compiled and installed libcalculate 0.9.10 and qalculate-gtk 0.9.9 from source tarball. In both cases I executed:
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure
make
sudo make install

When I try to run qalc or qalculate-gtk a warning message shows up:
"error while loading shared libraries: libqalculate.so.6: cannot open shared object file: No such file or directory"

I guess some link is missing but I don't know where. libqalculate.so.6 is in "/usr/local/lib/"
My system is linux Mint 18.1 Serena Cinnamon Edition. 

Thanks in advance!

**Comment by HoracioDos** [comment]
I created a soft link in /usr/lib/x86_64-linux-gnu and it's working now.
sudo ln /usr/local/lib/libqalculate.so.6.0.0 libqalculate.so.6
is it the correct solution?
Thanks

**Comment by hanna-kn** [comment]
The proper solution is probably to add /usr/local/lib to /etc/ld.so.conf.d/.

**Comment by HoracioDos** [comment]
/usr/local/lib was already added to /etc/ld.so.conf.d/ For some strange reason ldconfig never have benn executed

**Comment by HoracioDos** [comment]
/usr/local/lib was already in /etc/ld.so.conf.d/ and there was some other .conf files too. For some strange reason ldconfig has never been executed.
I removed the softlink and I ran ldconfig as root. Qalculate runs just fine!
Thank you very much
