### ISSUE TITLE
mixed languages for prefixes and units in output

### ISSUE THREAD

**Issue by idamir** [Qalculate/libqalculate#270]
Prefixes are always in English, while Units depend on locale in output.

Reality:
`> 1 cm`
`  1 × сантиметр = 10 mм`

`> 1 cm to mm`
`  1 × сантиметр = 10 mм`

`> 1 cm to m`
`  1 × сантиметр = 0,01 м`

`> 1 cm to dm`
`  1 × сантиметр = 0,1 dм`

Expectations:
`> 1 cm`
`  1 × сантиметр = 10 мм`

`> 1 cm to mm`
`  1 × сантиметр = 10 мм`

`> 1 cm to m`
`  1 × сантиметр = 0,01 м`

`> 1 cm to dm`
`  1 × сантиметр = 0,1 дм`

**Comment by hanna-kn** [comment]
This is only an issue for some languages with non-latin scripts. The Chinese translation specifies the standard symbols as primary abbreviations for SI units. The Russian translation is therefore the first that demonstrates the need for local prefix symbols.

**Comment by idamir** [comment]
Agree, that all Cyrillic languages use non-latin prefixes.
Is it possible to expand prefixes to non-latin langs?
If you have limits in time resource, I can ask an IT student to make his/her diploma to contribute (I am not a programmer, I am a physicist).

**Comment by hanna-kn** [comment]
Prefix names are now translated as names of other kinds of objects (units, functions, etc.).

**Comment by idamir** [comment]
Works fine. I am happy.
