### ISSUE TITLE
Feature request: Troy pound unit

### ISSUE THREAD

**Issue by schuelermine** [Qalculate/libqalculate#273]
Interpret `lbt` and `℔` as troy pound = 144/175lb

**Comment by hanna-kn** [comment]
Currently `lb_t` is used as symbol for troy pound (according to https://en.wikipedia.org/wiki/Pound_(mass)#Troy_pound troy pound is abbreviated as "lb t"). ℔ is used for the international avoirdupois pound.

**Comment by schuelermine** [comment]
OK
