### ISSUE TITLE
Feature request :: new currency :: BTC

### ISSUE THREAD

**Issue by radjaidjah** [Qalculate/libqalculate#28]
Hello, it would be great if Qalculate could make Bitcoin calculations. The BTC/USD and BTC/EUR conversion rates can be retrieved at various places such as Coinbase or Kraken. What do you think?

**Comment by munim** [comment]
@hanna-kn Please consider this feature request. This will help a lot of users.

**Comment by hanna-kn** [comment]
I will likely add support for bitcoin in the next version. It should be easily done, but the large fluctuations are problematic. With the default settings the exchange rates should never be older than one week, but for bitcoins this still means that it can be off  by more than ten percent.

**Comment by hanna-kn** [comment]
Done. (For frequent use manual exchange rate updates are recommended.)
