### ISSUE TITLE
Build failure with clang++/libc++ on Linux

### ISSUE THREAD

**Issue by elkrejzi** [Qalculate/libqalculate#3]
When building with clang++/libc++ on Linux, I get the following error:

    In file included from Function.cc:14:
    In file included from ./Function.h:15:
    In file included from ../libqalculate/ExpressionItem.h:15:
    In file included from ../libqalculate/includes.h:47:
    /usr/bin/../include/c++/v1/ext/hash_map:213:5: warning: Use of the header <ext/hash_map> is deprecated. Migrate to <unordered_map> [-W#warnings]
    #   warning Use of the header <ext/hash_map> is deprecated.  Migrate to <unordered_map>

    In file included from Function.cc:14:
    In file included from ./Function.h:15:
    In file included from ../libqalculate/ExpressionItem.h:15:
    ../libqalculate/includes.h:54:4: error: invalid preprocessing directive
    #               #define unordered_map Sgi::hash_map

    In file included from Function.cc:14:
    ./Function.h:74:2: error: unknown type name 'unordered_map'
            unordered_map<size_t, Argument*> argdefs;

**Comment by elkrejzi** [comment]
This patch fixes it for me

[libqalculate.txt](https://github.com/Qalculate/libqalculate/files/343267/libqalculate.txt)

**Comment by hanna-kn** [comment]
Patch applied.
