### ISSUE TITLE
Portable mode in Linux

### ISSUE THREAD

**Issue by SubhashBose** [Qalculate/libqalculate#300]
The windows portable mode is perfect! However, under Linux I can get the binaries, but I couldn't find any way to make it portable. 

What I can see Qalc uses ~/.local/share/qalculate and  ~/.config/qalculate/ for storing definitions and configs. It will be great to have options to set these paths in runtime, either by (i) environment variables (like $QALC_CONF and $QALC_DEF), which a user can invoke by a script or set in .bashrc (ii) or pass these as startup commandline arguments ( --qalc_conf and --qalc_def) to both qalc and qalc-gtk executables.

Anyways, thanks for such a wonderful program - this is one of the most well-thought programs out there, I like how intuitive this is with so many granular customization options.

**Comment by hanna-kn** [comment]
Support for QALCULATE_USER_DIR environment variable has now been added.

**Comment by SubhashBose** [comment]
thanks, and it works!
