### ISSUE TITLE
Portable mode in Windows

### ISSUE THREAD

**Issue by CrendKing** [Qalculate/libqalculate#301]
Seems the portable mode can only be enabled at compile time: https://github.com/Qalculate/libqalculate/blob/master/libqalculate/util.cc#L467

What about instead to detect the "user" subdirectory in the application directory and automatically switch to use the config inside. This way you don't need to provide a special zip just for portable. 64-bit version can also have portable automatically. Package providers such as Scoop can easily create that "user" directory at installation. Perfect for both worlds.

And if you do that, non-Windows users don't need `QALCULATE_USER_DIR` to just do portable. Of course they can still use that env var to store config in other places.

Thinking about it, why only support `QALCULATE_USER_DIR` for non-Windows? What about:

1. Check `QALCULATE_USER_DIR`. If exist, use it. Otherwise,
2. If on Linux, check `XDG_CONFIG_HOME`. Exist? Use it. Otherwise,
3. Check `${appDir}\user`. Exist? Use it. Otherwise,
4. For Windows, use `%LOCALAPPDATA%\Qalculate`. Otherwise, use `~/.config/qalculate`

**Comment by hanna-kn** [comment]
Support for QALCULATE_USER_DIR and user subdirectory (regardless of compile time options) on Windows has been added.

**Comment by CrendKing** [comment]
Very nice. Thank you!
