### ISSUE TITLE
Improving multisolve()

### ISSUE THREAD

**Issue by SubhashBose** [Qalculate/libqalculate#302]
The multisove() can nicely solve a set of linear equations, but it often fails with higher degree polynomials.

for example: multisolve( [x(7−y)=25; x(8−y)=20], [x,y] )  will fail to solve. However, simple substitution of one equation to another could have easily solved the equation. 

I understand equation solving is a complex algorithm and too demanding for a desktop calculator tool. However, if at least these kinds of equations can be also solved then it will be nice.

**Comment by hanna-kn** [comment]
Fixed.

The first equation returned `x = −25 / (y − 7) and y ≠ 7`. multisolve() could not handle the logical AND. The function will now remove `y ≠ 7` before substitution, and afterwards use it to check if the result is valid.

**Comment by SubhashBose** [comment]
That's no nice. Thanks.
