### ISSUE TITLE
Suggestion: Support any two-argument function as an infix operator

### ISSUE THREAD

**Issue by cousteaulecommandant** [Qalculate/libqalculate#307]
Qalculate! could add support so that `func(x, y)` could be alternatively written as `x func y`, where `func` is a function that takes exactly 2 arguments.  That would make it more natural to type expressions that are normally written using specialized infix operators.
Some examples:
`rem(10,3)` → `10 rem 3` _**(already implemented)**_
`mod(10,3)` → `10 mod 3` _**(already implemented)**_
`perm(10,3)` → `10 perm 3` (sometimes written as <em>n</em>P<em>r</em> and <em>n</em>C<em>r</em>)
`comb(10,3)` → `10 comb 3`
`base(100,2)` → `100 base 2`
`dot([1,2,3],[4,5,6])` → `[1,2,3] dot [4,5,6]` (although there's already `.` for that)
`cross([1,2,3],[4,5,6])` → `[1,2,3] cross [4,5,6]`

I think this would simplify entering some expressions, and would be a generalization of what `mod`, `rem`, `div` already do, so it would be consistent and intuitive.

(Note that this shouldn't apply to functions that may take 1 or 2 arguments; e.g. writing `log(10,2)` as `10 log 2` could be misinterpreted as `10*log(2)`, since the second argument in `log()` is optional.)

What do you think?

**Comment by hanna-kn** [comment]
It seemed like a good idea, but upon closer examination I do not think it would be very useful for most functions beyond your examples. In some cases (root, besselj, Li, etc.) it would potentially cause confusion. There are also issues with order of operations.

All functions requiring exactly two arguments: _addDays, addMonths, addTime, addYears, atan2, besselj, bessely, beta, binomial, bmi, chisqdistinv, column, comb, cone, cone_sa, cor, cov, cross, cylinder, cylinder_sa, div, divide, dollarde, dollarfr, dot, effect, entrywise, expinv, function, gammainc, gcd, hypot, igamma, interval, lcm, Li, lxor, mod, multifactorial, multisolve, nominal, parallelogram, parallelogram_perimeter, pearson, perm, poolvar, pow, pttest, rect, rect_perimeter, rem, root, row, spearman, tdistinv, triangle, trimmean, ttest, weighmean, winsormean, xor_

Functions requiring at least two arguments: _base, bitrot, chisqdist, coeff, days, decile, elasticity, element, expondist, export, limit, logistic, newtonsolve, percentile, poisson, quartile, randbetween, randuniform, rayleigh, save, select, shift, solve2, tdist_ uncertainty, yearfrac

**Comment by cousteaulecommandant** [comment]
On second thought, you're probably right.  Nearly none of those functions you listed make sense as infix operators (maybe `xor` is the only one).  I thought there would be more examples than there actually were.  And it is true that writing ³√8 as `8 root 3` instead of `3 root 8` would be confusing.

Perhaps I was focused on the idea of having a `cross` operator, but I suppose that could be implemented separately (or give it its own operator; I considered using `^` or `××` for that but I'm not sure that's a good idea.)

I guess this can be closed.

**Comment by hanna-kn** [comment]
I've now added support for the suggested notation for perm, comb, dot, and cross. I've also added support for the explicit Unicode cross product symbol (⨯), but it's probably of little practical usefulness.
