### ISSUE TITLE
parsing of "1 W Ohm /K/K"

### ISSUE THREAD

**Issue by Ivo-P** [Qalculate/libqalculate#31]
Why should `1 W Ohm /K/K` be different from `1 W Ohm /K /K`? What's wanted in any case is `1 watt ohm kelvin^-2`. The first form, however, gives `1 W Ohm` and the two kelvins cancel.

**Comment by hanna-kn** [comment]
The "adaptive" parsing mode can be a bit unpredictable in cases such as this. It is an unintended side effect of for example “5 m/5 m/s = (5*m)/(5*(m/s)) = 1 s”. In the adaptive parsing mode handling of implicit multiplication are affected by spaces and unit expressions are handled separately. 

The default "adaptive" parsing mode can certainly be enhanced to try to avoid cases such as this, but if the main priority is predictable parsing, then another parsing mode (or a more strict syntax) should be used (one could argue that one of these should instead be default).

**Comment by Ivo-P** [comment]
Thanks hanna-kn. To my big surprise, the syntax here is completely broken, and the result totally unpredictable. I mean, we have well established rules on how to handle mathematical expressions, so why this? Check how differently this is being parsed `1W/K/cm` vs. `1W/K/cm^1` (and I have no idea why).

**Comment by hanna-kn** [comment]
`1W/K/cm` (parsed as `(1×W)∕(K∕cm)`) is _not_ parsed differently from `1W/K/cm^1` (parsed as `(1×W)∕(K∕(cm^1))`). The only issue here is that unit/unit/unit probably should be parsed as (unit/unit)/unit, and not unit/(unit/unit), also in the adaptive parsing mode (there should be no issues with the other parsing modes which applies a more strict syntax).

**Comment by hanna-kn** [comment]
Should be fixed now.
