### ISSUE TITLE
Qalculate CLI prints ones and zeroes when slash in expression

### ISSUE THREAD

**Issue by schuelermine** [Qalculate/libqalculate#313]
Since a recent upgrade via Apt to version `3.19.0+git20210715.162ed52-1daily709~ubuntu21.04.1` and a subsequent upgrade to version `3.19.0+git20210716.5b23861-1daily709~ubuntu21.04.1`, typing an expression involving fractions prints as many ones and zeroes as fractions in the result (I think—there seems to be correlation between the number of fractions and number of digits).

For instance:
```none
> (37/650) * (45/32)
0
0
1

  (37 / 650) × (45 / 32) = 333/4160

> 2 ÷ 3 ÷ 17
0
0
1

  (2 / 3) / 17 = 2/51

> 50 * 2/3 · 4/7 · 5/24
0
0
0
1

  (((((50 × 2) / 3) × 4) / 7) × 5) / 24 = 250/63
```

**Comment by rickhg12hs** [comment]
Executing `./src/test` demonstrates this behavior too.

**Comment by hanna-kn** [comment]
Fixed.
