### ISSUE TITLE
log() and ln() parse differently

### ISSUE THREAD

**Issue by Mee42** [Qalculate/libqalculate#314]
```
> ln 64 / ln 2

  ln(64) / ln(2) = 6

> log 64 / log 2

  log(64 / log(2)) = 6 × ln(2) − ln(ln(2)) ≈ 4.525396004

> log(64) / log(2)

  log(64) / log(2) = 6
```
here's a quick example. Either behavior would be acceptable, but I'm curious why it's different - in this context they operate the exact same. logN, like `log7`, parses the same as `log`. 

expected behavior: consistency between the two, very similar, functions

**Comment by hanna-kn** [comment]
The difference is that ln takes only one argument, while log takes two (the second argument is optional). I've now changed the behaviour so that log will be parsed in the same way as ln if no additional arguments are found.

**Comment by Mee42** [comment]
That makes sense. Thanks for the change! I imagine this project is a nightmare full of edge cases of ambiguous parses :stuck_out_tongue:
