### ISSUE TITLE
Crash in Windows when "Calculate as you type" is enabled

### ISSUE THREAD

**Issue by CrendKing** [Qalculate/libqalculate#316]
Fresh install either the x86 or x64 version in Windows. Enable "Calculate as you type". Press any key into the box and the app freezes for 2 seconds before crash. The pressed character is not displayed.

Previous versions work without this problem.

Version: 3.20

**Comment by CrendKing** [comment]
Apparently duplicate to https://github.com/Qalculate/qalculate-gtk/issues/307. Feel free to close.

**Comment by hanna-kn** [comment]
Fixed in version 3.20.1.
