### ISSUE TITLE
the self-contained linux binaries download link does not work due to a missnaming on the release

### ISSUE THREAD

**Issue by ReNardier** [Qalculate/libqalculate#319]
https://github.com/Qalculate/qalculate-gtk/releases/download/v3.20.1/qalculate-3.20.1-x86_64.tar.xz
is what the download link at http://qalculate.github.io/downloads.html call up, "qalculate-3.21.0-x86_64.tar.xz" its how is actually called, the problem is the 21.0 instead of 20.1, and this has happened on libqalculate, qalculate-gtk and qalculate-qt

**Comment by hanna-kn** [comment]
Fixed.
