### ISSUE TITLE
Get proper exchange rates

### ISSUE THREAD

**Issue by musikjunkie** [Qalculate/libqalculate#32]
Hi,

I'm using the version that came with Kubuntu 17.04: Qalculate! 0.9.9.

When I want to use it for currency conversions, it offers me Euros [€] and only the former currencies, which have now been replaced by euros (e.g. Deutsche Mark). I cannot use any current currencies like British Pounds or US$.

My suspicion is that there is something wrong with fetching the exchange rates from the European Central Bank. It seems to only fetch the frozen exchange rates of those former currencies relative to Euros.

**Comment by hanna-kn** [comment]
If only Euro and former European currencies are offered than it means that no exchange rates has been fetched at all. I do not however find any issues with the program or the the exchange rate data from ECB. 

If you are using the qalc (and not the GUI, qalculate-gtk), than you need to update the exchange rates manually (using the -e/-exrates command line swithc or the exrates command) before any other currencies are available.

**Comment by musikjunkie** [comment]
Tried that. This is what I get:
`user@pc:~$ qalc -e
/home/user/.local/share/qalculate/eurofxref-daily.xml:1: parser error : Document is empty

^
> quit
user@pc:~$ qalc -exrates
/home/user/.local/share/qalculate/eurofxref-daily.xml:1: parser error : Document is empty

^
> exrates
/home/user/.local/share/qalculate/eurofxref-daily.xml:1: parser error : Document is empty

^
> ^C
user@pc:~$ `
I checked the file; its size is 0b.

**Comment by hanna-kn** [comment]
That is strange. 

What do you get if you manually download the exchange rates using:
`gvfs-copy http://www.ecb.int/stats/eurofxref/eurofxref-daily.xml /home/user/.local/share/qalculate/eurofxref-daily.xml`

**Comment by musikjunkie** [comment]
`user@pc:~$ gvfs-copy http://www.ecb.int/stats/eurofxref/eurofxref-daily.xml /home/user/.local/share/qalculate/eurofxref-daily.xml
Fehler beim Kopieren der Datei »http://www.ecb.int/stats/eurofxref/eurofxref-daily.xml«: Der angegebene Ort wird nicht unterstützt
user@pc:~$ `

That error message means "Error while copying file ... : The specified location is not supported."

**Comment by hanna-kn** [comment]
You need to install gvfs-backends.

**Comment by musikjunkie** [comment]
That did the trick. Thanks a lot.

Seems to be a but in the Kubuntu packaging then; Qalculate! should depend on gvfs-bin and gvfs-backends, so they get pulled in automatically.
