### ISSUE TITLE
l not recognized as liter

### ISSUE THREAD

**Issue by LinAGKar** [Qalculate/libqalculate#320]
Qalculate does not recognize "l" as liter, instead requiring you to use the less common "L". "l" is just ignored, so if you write "2 ml", it's interpreted as 2 meters, rather than 2 milliliters.

**Comment by hanna-kn** [comment]
Which language are you using?
For me it seemed to work for every language except Swedish (which actually is my native language).

**Comment by LinAGKar** [comment]
I too am using Swedish.

**Comment by hanna-kn** [comment]
This was caused by an erroneously case-insensitive comparison combined with the reordering of names/symbols in the Swedish translation, which resulted in changed cased of the first lower-case "l". This has now been fixed.
