### ISSUE TITLE
Odd version name to tarball - should be 3.20.1 rather than 3.20.0 I think

### ISSUE THREAD

**Issue by rubyFeedback** [Qalculate/libqalculate#323]
The release subpage shows this:

"Download the source code here:
libqalculate-3.20.1.tar.gz"

But the URL points to:

https://github.com/Qalculate/libqalculate/releases/download/v3.20.0/libqalculate-3.20.0.tar.gz

I think the URL link was not corrected after 3.20.0 may have been released before.

**Comment by hanna-kn** [comment]
Fixed.
