### ISSUE TITLE
List the dataset entries from the cmdline

### ISSUE THREAD

**Issue by eadmaster** [Qalculate/libqalculate#327]
is it possible to query a dataset from the cmdline and show the output on the console?

e.g. i'd like to list all the entries in [this db](https://github.com/Qalculate/libqalculate/blob/c45f08a18916b01aa4647bd56c22c7f34fcfe29c/data/elements.xml.in).

**Comment by hanna-kn** [comment]
All datasets have an associated function (in the Dataset category). For the included datasets these are `atom()` (the element function name is for matrix elements) and `planet()`. If the function is invoked without the second argument (property), all properties will be listed for the entry specified in the first function argument.

```
> qalc atom H
-------------------------------------
Symbol:
H

Number:
1

Name:
Hydrogen

Classification:
9

Atomic Mass:
[1.00784, 1.00811] u

Boiling Point:
20.271 K

Melting Point:
13.99 K

Density:
8.988E-5 g/cm³
-------------------------------------
atom('H', "info") = 0
```

**Comment by eadmaster** [comment]
ok, can i also list all the entries inside a dataset on the console + some selected field?

basically something like this:
````
$ qalc "atom(*, symbol, number, name)"
Symbol:
H

Number:
1

Name:
Hydrogen

--

Symbol:
He

Number:
2

Name:
Helium

...

````

**Comment by eadmaster** [comment]
>  can i also list ALL the entries inside a dataset on the console 

nevermind about this, i've found a way to query the xml db directly via [xmlstarlet](https://sourceforge.net/projects/xmlstar/).
