### ISSUE TITLE
Test suite?

### ISSUE THREAD

**Issue by sodface** [Qalculate/libqalculate#333]
Hello, I am packaging libqalculate for Alpine Linux. Is the tests/limits.batch meant to be run by a build system at compile time or is this file used for manual testing after the fact? Right now I have the package build set to skip checks with a comment that no test suite is available. Can you verify that's correct?

The package builds successfully and appears to work, however when I:
`qalc -f limits.batch`
I do see some errors in the output:
> error: Unable to find limit. 

and it appears to hang at line 287. Does this indicate something is amiss?

**Comment by hanna-kn** [comment]
Both tests/limits.batch and src/test.cc are solely intended for use by the developer (me). The issues with limits.batch is known (limits support is incomplete).

**Comment by sodface** [comment]
Thank you.
