### ISSUE TITLE
64 bit Qalculate Loading delay.

### ISSUE THREAD

**Issue by PowerUser1234** [Qalculate/libqalculate#336]
I am using the Win64 download bundle, non installer, version of Qalculate!.  With a small registry tweak recommended
from the Qalculate people themselves.  The issue that I presently have is that the version of the program that I run,
there is a long pause before the GUI displays on my screen.  Is there an easy way to fix this?  Is this something
that the next version will or has changed or fixed?

**Comment by PowerUser1234** [comment]
I find that when I type ! on some natural number, it gives me the factorial.  I find, however, that when I call !!,
it calls a separate function, called factorial2, doing what I know now what.  Is there something I can do
to get two invocations in a row, !!, to just call and submit to the original factorial, twice?  I need
this for Taylor and Maclaurin series I am using.

?

**Comment by hanna-kn** [comment]
> I find that when I type ! on some natural number, it gives me the factorial. I find, however, that when I call !!, it calls a separate function, called factorial2, doing what I know now what. Is there something I can do to get two invocations in a row, !!, to just call and submit to the original factorial, twice? I need this for Taylor and Maclaurin series I am using.

Use parentheses (e.g. `(n!)!`).
