### ISSUE TITLE
Zero terms in simplification

### ISSUE THREAD

**Issue by vvs-** [Qalculate/libqalculate#34]
This is more a CAS issue but still.

Try e.g.
```
x^2-1
factor
simplify
```

**Comment by hanna-kn** [comment]
This is what I get with the latest git version (where factorization/simplification has been improved):

```
> x^2-1

  (x^2) - 1 = x^2 - 1

> factor

  x^2 - 1 = (x - 1)(x + 1)

> simplify

  (x - 1)(x + 1) = x^2 - 1

```

I assume that you get a different result.

**Comment by vvs-** [comment]
Yes, but I have the latest git too 😄

It appears to depend on assumptions setting. Is that expected?

**Comment by hanna-kn** [comment]
I assume you get x^2 + 0x - 1 when simplifying (x - 1)(x + 1) because there are no assumptions for the type of x.

I do not remember the original reasoning for this behaviour, but there are some values for x where 0*x does not equal zero (e.g. if x is a matrix). The problem is that for matrices  x^2 - 1 does not equal (x - 1)(x + 1).

**Comment by hanna-kn** [comment]
But matrix^2+0×matrix=matrix^2, so the current behaviour should not be necessary for matrices. I do not understand why (matrix - 1)(matrix + 1) currently gives such a strange result (it might be a bug).

**Comment by vvs-** [comment]
Current behavior formally breaks invariant, so factor ≠ simplify. Though, this is just an optimization issue, because it adds a zero term, so nothing really serious.

As for matrices, I don't understand what is the meaning of matrix minus scalar? I admit that I never used matrices in Qalculate!

**Comment by hanna-kn** [comment]
I never use matrices myself. There is no meaning of matrix minus scalar (at least not in Qalculate! where matrix - scalar = matrix - scalar). If you know that does not represent a matrix you should at least set the default assumptions to not matrix (default assumption is real number), to avoid unexpected oddness.

**Comment by vvs-** [comment]
Yes, polynomials over matrices are very odd at least. Especially with scalars and non-square matrices as its terms.

But the point is that the zero term in polynomials seems to be meaningless in case of matrices anyway. So, I believe that there is no reason to make it a special case. Otherwise it appears all of a sudden without any particular reason.

**Comment by hanna-kn** [comment]
The best option might be to simply remove the possibility that _x_ is a matrix and make _number_ the first option for assumption type. There are more cases where _x_ as matrix is broken and at the moment it has no real use.
