### ISSUE TITLE
Compact output

### ISSUE THREAD

**Issue by qsmodo** [Qalculate/libqalculate#340]
To save vertical space, a setting called "compact" that, if enabled, would not output empty lines above and below the calculation. E.g.

```
> 10-2

  10 − 2 = 8

> set compact off
>10-2
  10 − 2 = 8 
>
```

Thanks for the great software.

**Comment by hanna-kn** [comment]
Done (the new option is `vertical space` or `vspace`).

**Comment by yashpalgoyal1304** [comment]
in the description, it was intended to be `set compact` i think. but yeah, anyways 😅
