### ISSUE TITLE
RAM Latency Calculator

### ISSUE THREAD

**Issue by kidimbwi** [Qalculate/libqalculate#341]
Qalculate! is such an awesome calculator, it is very convenient to have so many functions in one application. Thank you for your work on it.

can i suggest a feature to add ram latency calculation ? this information comes in handy when shopping for ram or when working out what your latency would be if you overclocked your ram and tightened its timings. you can find the formula to work out latency on this page: https://calculator.academy/ram-latency-calculator/

Thank you and keep up the great work on Qalculate!

**Comment by foreachthing** [comment]
Just define your own function (i. e. in Qalculate-GTK) and use that in libqalc.
