### ISSUE TITLE
pearson() and spearman() error

### ISSUE THREAD

**Issue by joepatricio** [Qalculate/libqalculate#348]
Attempting to use the before mentioned functions result in the following errors, respectively: 

error: Please use the cross(), dot(), and hadamard() functions for vector multiplication.
pearson(data1, data2) = ([20, 40, 60] × [170, 153, 136] − 18360) / √(|[20, 40, 60]^2 × [170, 153, 136]^2 − 4800 × [170, 153, 136]^2 − 70227 × [20, 40, 60]^2 + 337089600|)

error: Please use the cross(), dot(), and hadamard() functions for vector multiplication.
spearman(data1, data2) = ([1, 2, 3] × [3, 2, 1] − 12) / √(|[1, 2, 3]^2 × [3, 2, 1]^2 − 12 × [3, 2, 1]^2 − 12 × [1, 2, 3]^2 + 144|)

Expected: pearson(data1, data2) = -1

data1, and data2 are vectors with the following values:
data1 = [20, 40, 60]
data2 = [170, 153, 136]

**Comment by hanna-kn** [comment]
Fixed.

The definition of pearson() in functions.xml was changed from `(\x*\y-\1*\2/\3)/abs(((\x^2-(\1^2)/\3)*(\y^2-(\2^2)/\4))^(1/2))` to `(\x.\y-\1*\2/\3)/abs(((\x.\x-(\1^2)/\3)*(\y.\y-(\2^2)/\4))^(1/2))` (it was broken by changes to vector multiplication in version 3.19). spearman() is defined using pearson() and was a result also affected by this issue.
