### ISSUE TITLE
Support end of options --

### ISSUE THREAD

**Issue by iyzana** [Qalculate/libqalculate#349]
Currently it is hard to get qalc to print some negative constants when not in interactive mode.

e.g. "computing" the negative speed of light does not work and instead enters interactive mode
```
~ qalc -c
> 
```
because the `-c` is parsed as the `-color` flag.

I would expect qalc to implement to "end of options" flag - a lone `--`, see https://www.man7.org/linux/man-pages/man1/getopts.1p.html - to indicate that everything following it is to be interpreted as a positional argument and not an option.

# Expected behaviour
```
~ qalc -- -c
-speed_of_light = -299.792458 km/ms
```

# Current behaviour
```
~ qalc -- -c
−(−(−speed_of_light)) = −299.792458 km/ms
```

**Comment by hanna-kn** [comment]
Done.
