### ISSUE TITLE
Parallel inductor/capacitor calculation using '||'

### ISSUE THREAD

**Issue by zhangjingye03** [Qalculate/libqalculate#351]
Hello,
For now, qalculate supports parallel resistance calculation (e.g. `10kOhm || 100Ohm` => `99Ohm`), which is a very useful function.
However, in some high frequency circuits, parallel inductor/capacitor is commonly used and it's convenient to calculate the inductance/capacitance directly (e.g. `3pH || 6pH` => `2pH`) without converting it to reactance first.
Would be much appreciated if you could add this feature, thanks.

P.S. 
I took a quick look at the source and find it is likely related to 
[L5665,L5671 at MathStructure-calculate.cc](https://github.com/Qalculate/libqalculate/blob/ccc930d54352d9b1400c8e274d7cc3983aaa0c1a/libqalculate/MathStructure-calculate.cc#L5665,L5671)
Maybe the condition could be extended to something like this?
```C
if (.... && 
    CHILD(0)[1].unit()->name().find("ohm") != string::npos && 
    CHILD(0)[1].unit()->name().find("F") != string::npos && 
    CHILD(0)[1].unit()->name().find("H") != string::npos
)
```

P.S. 2
The shunt capacitance is actually the sum of two capacitor. Could we use `||` to represent series capacitance calculation just for convenience?

**Comment by hanna-kn** [comment]
Done.

> The shunt capacitance is actually the sum of two capacitor. Could we use || to represent series capacitance calculation just for convenience?

I'm really not familiar with these kinds of calculations and do not know what shunt capacitance is. You will have to describe more clearly how this would work.

**Comment by zhangjingye03** [comment]
Usually in circuit, shunt means parallel and series means serial.

For two capacitor, assume C1 and C2, their reactance is Z1=1/(jωC1) and Z2=1/(jωC2) respectively.
When they are connected in parallel, the total reactance is Z = Z1||Z2 = 1/(jω(C1+C2)), and the total capacitance is C1+C2.
When they are connected in serial, the total reactance is Z = Z1+Z2 = (C1+C2)/(jωC1\*C2), the total capacitance is C1\*C2/(C1+C2), which is the actually C1||C2.

With this change, the result of `C1||C2` gives C1 and C2 in series, which is not "parallel". Maybe a tip or warning should be issued when using `||` with unit `F`?

**Comment by hanna-kn** [comment]
I realised that the parallel operator is not only useful in electrical engineering, and I've therefore extended it to apply to all units. I've also added support for the Unicode parallel to symbol (∥), which does not require use of units, and moved the interpretation of `||` to the parsing stage (the interpreted expression will be displayed using ∥ instead of "or").

**Comment by zhangjingye03** [comment]
Nice idea, it's pretty useful. Thanks!
