### ISSUE TITLE
`clear` in qalc

### ISSUE THREAD

**Issue by yashpalgoyal1304** [Qalculate/libqalculate#352]
hi, i am very very habitual of clearing things up, so, escape in GUI and `clear` in terminal things. so, t'd be really nice for me to have `clear` command in qalc too.

it may come in handy for example:
* when u have interacted with help command
* when u were trying some thing, and then u figured the correct way, and now u wanna record it cleanly (for showing in video, or for keeping records/documentation)

Related:
* https://github.com/Qalculate/qalculate-gtk/issues/125
* i thought to open it in libqalculate repo but got confused between the 3 repos (libqalculate , qalculate-gtk , qalculate-qt) and decided to open it here first, i suppose the admins/reporters have access and option to [move this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) there
* search terms: windows cmd shell `cls`

**Comment by hanna-kn** [comment]
Ctrl+L clears the terminal in GNU/Linux. 
I've added `clear` command.

**Comment by yashpalgoyal1304** [comment]
hi so, this issue can be closed then right??

**Comment by yashpalgoyal1304** [comment]
released on stable in current latest tag: https://github.com/Qalculate/libqalculate/releases/tag/v3.22.0
