### ISSUE TITLE
Add multithreading support for large calculations

### ISSUE THREAD

**Issue by sauce420** [Qalculate/libqalculate#358]
I know this is a big ask, but adding multi threading support would allow for much larger calculations in a much shorter time, and would allow this great library and app to be used for a lot more.

**Comment by hanna-kn** [comment]
I tried implementing multi-threaded calculations, but did not deem it worth the effort.

What kind of calculations do you have in mind?

Most calculations are sequential in nature and would benefit little from multi-threading (although I guess some could be altered to somewhat increase the benefit). It would primarily be useful for calculations involving vectors (e.g. statistical calculations) and matrices, but for calculations involving large data sets other software are better suited. It would be useful to create more data points in shorter time for plots, but this alone would not make it worth the effort.

**Comment by sauce420** [comment]
I was doing a large summation, and was thinking that it could be improved through multithreading, but, as you said, they're sequential, so I realise now it wouldn't work. Multi-threading might be useful for parallel calculations, e.g evaluating brackets, but you're right; it doesn't seem worth the effort
