### ISSUE TITLE
Upstream of Patch for Alpine Package

### ISSUE THREAD

**Issue by sodface** [Qalculate/libqalculate#360]
Hello, during the process of packaging libqalculate and qalculate-gtk for Alpine Linux, one of the developers assisted with the [following comment](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/26266#note_184560):  

> The reason of this problem is incorrect pkg-config file (/usr/lib/pkgconfig/libqalculate.pc). Otherwise abuild would be able to assign correct dependencies to the package. Could you patch it and report it upstream?  

[The patch:](https://gitlab.alpinelinux.org/alpine/aports/-/raw/ee50d7c700eb493f16575a6e41f5195dc4d66b8f/testing/libqalculate/libqalculate.pc.in.patch)

```
--- a/libqalculate.pc.in	2021-10-09 05:03:47.712401038 +0200
+++ b/libqalculate.pc.in	2021-10-09 05:06:54.039307183 +0200
@@ -8,5 +8,6 @@
 Version: @VERSION@
 Libs.private: @LIBCURL_LIBS@ @ICU_LIBS@ @LTLIBINTL@ @LTLIBICONV@ -lmpfr -lgmp -lpthread
 Required.private: libxml-2.0 >= 2.3.8
+Requires.private: gmp mpfr
 Libs: -L${libdir} -lqalculate
 Cflags: @LIBCURL_CFLAGS@ @ICU_CFLAGS@ -I${includedir}
```

Would you merge this change?  

Also, notice the existing line above the addition uses the keyword "Required" instead of "Requires". I think this may be a typo? [This guide to pkg-config ](https://people.freedesktop.org/~dbn/pkg-config-guide.html#concepts) only lists "Requires.private".

**Comment by hanna-kn** [comment]
"Required" is a typo. gmp and mpfr are included in Libs.private (for libraries without pkg-config support). pkg-config support was not added in mpfr until version 4.0, and I'm therefore hesitant about moving mpfr from Librs.private to Requires.private.

**Comment by sodface** [comment]
Closing this as it will be handled on the Alpine side. Thanks for the review and the great software!
