### ISSUE TITLE
iconv is actually required (not recommended)

### ISSUE THREAD

**Issue by mr-kenhoff** [Qalculate/libqalculate#361]
Compiling libqalculate without `iconv` (becauae the readme says that `iconv` is only recommended) does not work, because `libqalculate/utils.cc` (and maybe other files too) depend on it. Can someone confirm this or did I miss something?

Quick fix: Simply remove "recommended" for iconv from the readme to avoid confusion :stuck_out_tongue_winking_eye:.
We might also want to throw an error during `./configure` when iconv is not present

I am happy to fix this, once it is confirmed.

**Comment by hanna-kn** [comment]
Fixed (iconv is no longer strictly required).

**Comment by mr-kenhoff** [comment]
Thanks a lot for the quick fix!
