### ISSUE TITLE
Qalculate! v3.22 Evaluation and Crashing Bugs.

### ISSUE THREAD

**Issue by PowerUser1234** [Qalculate/libqalculate#363]
I am running 64 bit Windows 10 Home Edition, and am encountering the following two bugs in the latest stable,
3.2.2 version of Qalculate!.

I have reconfigured a binary "paste" version of the Win64 3.2.2 version of the software as follows:

_1)  Inside the normal GUI version of the program, I have set [[Mode\Interval Display\<Interval>] to true.

2)  Inside the normal GUI version of the program, I have set [Mode\Numerical Display\<Indicate Repeating Zeroes>]
to true.

3)  Inside every copy of qalculate-gtk.cfg that I can find, I have set either [interval_display=0] or [interval_display=2]
to [interval_display=5]._

I have been trying to do evaluations of pi as a benchmark, or testing indicator.  Having done all this, I have asked for
the evaluation of pi, which has to display in the History area.  If I go [Mode\<Precision>] and set it to 10,000 ,
I get exactly what I would expect, given that and the other settings changes also made, as above. If I set
<Precision> to 100,000 , the calculations and displaying seem to fail totally, the GUI crashes and drops entirely off
the screen display, and I do not get my 100,000 significant figures of pi, in fact I don't get any figures at all.

**-Is there anything I need to do to the program to prevent this total crashing, along with the calculation and display of my values?
 If not, is this all a bug area that can be corrected by the Qalculate team, so that I can get 100,000 accurate significant values of pi, and even more, for as high a a precision value as may be entered, and as much free RAM as my computer has?**

**Comment by hanna-kn** [comment]
I can confirm that the GUI crashes in Windows when a value with more than approximately 50 000 digits is displayed and the history view is displayed (or has been displayed). 

I recommend that you use the command line interface, qalc, instead if you need that many significant digits (although GNU/Linux works better if you want millions of digits).

If you just want as many digits as possible of pi, and other constants, there are text files available, if you search the Internet, with trillions of digits.

**Comment by PowerUser1234** [comment]
Are the Qalculate team in a position to alter this problem, so that the software doesn't crash, does calculate to larger precision, and
does accurately display all required digits?

**Comment by hanna-kn** [comment]
> Are the Qalculate team in a position to alter this problem, so that the software doesn't crash, does calculate to larger precision, and does accurately display all required digits?

The issue has now been fixed (although I still do not know exactly why the now modified code caused a crash). You can avoid the issue in version 3.22.0 by setting digit grouping (in preferences) to off or local.

**Comment by PowerUser1234** [comment]
Thanks, that seems to have one the trick!

How many precision significant figures will Qalculate! be able to calculate pi for, in the history area?
________________________________

**Comment by PowerUser1234** [comment]
I have set digit grouping to local, and find that my pi calculating to 100,000 significant figures does occur.

However, now the program is post manipulating the value that I put into the tiny precision menu,
available from the Mode menu.  I try to put in and calculate via 100,001, or any number larger than 100,000,
and my input is altered back to 100,000.

Is there any particular reason why one cannot operate from 10^6 digit places, or even more, in RAM availability terms,
or in time to calculation, or calculation completion, terms?  I have 8 Gigabytes of RAM on my use PC.

?
________________________________

**Comment by hanna-kn** [comment]
> Is there any particular reason why one cannot operate from 10^6 digit places, or even more, in RAM availability terms,
or in time to calculation, or calculation completion, terms?  I have 8 Gigabytes of RAM on my use PC.

RAM is nowhere near a limiting factor. The GTK GUI will not display results with more than 500 000 characters. If I allow more than that the GUI will not behave well any more. The CLI (qalc) does not set a maximum precision, but it becomes problematic to abort slow calculations with precision ≥ 10⁶. I successfully calculated 10⁷ digits of pi, which required more than an hour, but less than 2 GB of RAM.

**Comment by hanna-kn** [comment]
You can actually set a precision higher than 100 000 if you enter the command `/set precision [PRECISION]` (e.g. `/set precision 250000`) in the expression entry.

**Comment by PowerUser1234** [comment]
Dear Hanna,

I have given this a go.  What I am finding is that Qalculate! 3.22.0 Is converting this to

second x e x tone x precision x [250000]

and that the precision field is not getting updated internally.

-What can I do to update precision to > 100000, and have the new
number work?

________________________________

**Comment by PowerUser1234** [comment]
Thanks a heap!  This is working.  You guys should update the [Mode\Precision\<Value>] setting so that it just takes values
larger than 100000, by means of this command, or even just by means of wrapping that input with this command.

Merry Christmas!
________________________________

**Comment by PowerUser1234** [comment]
Dear Hanna,

I am going

/set precision 500000

and while Qalculate! is going forward to evaluate pi,
it is only giving me 100000 figures.  I am using
OpenOffice Writer [Tools\<Word Count>]
which tells me the number of characters, being
the number of digits.

It seems the software is still reducing my precision value to
100000.  Is there anything I can do to exceed it successfully?
________________________________

**Comment by hanna-kn** [comment]
> It seems the software is still reducing my precision value to 100000.  Is there anything I can do to exceed it successfully?

It doesn't work if the precision dialog has been open (it should work if you restart Qalculate and enter the command again, or edit the configuration file).

> /set precision 500000

As I said before Qalculate won't display results with more than 500 000 character, so this will not work properly.

> You guys should update the [Mode\Precision\<Value>] setting so that it just takes values larger than 100000, by means of this command, or even just by means of wrapping that input with this command.

That will likely not happen. As I've said, the GUI will not behave well with higher precision, and such long results are really not practical. It is better to use command such as `qalc -t -s "precision 500000" pi > pi500k.txt` (although because of a bug, caused by timed key press waiting not working for calculation that takes more than one second, in the Windows version, you'll have to press Enter after while for the command to return).

**Comment by PowerUser1234** [comment]
Dear Hannah,

Thank for this.  All of your news implies, for me, that the command line 'qalc' command will be the place for me to go,
and not the graphical user interface.

It seems that configuration settings done at the graphical user interface level, or maybe even configuration file changes,
do not percolate down to the calc command line.  The command line is doing final decimal place rounding for me, again.

What can I do to prevent the command line performing final decimal place rounding?

I have been looking through https://qalculate.github.io/manual/qalc.html, and cannot see or figure out
exactly what to type and do!


Merry Christmas!


________________________________

**Comment by PowerUser1234** [comment]
Dear Hannah,

the final thing is that I am having trouble sing qalc command line functions.

How do I specify degrees or radians mode?

How do I get combinations and permutations calculating, nCr, nPr ?

Merry Christmas!
________________________________

**Comment by PowerUser1234** [comment]
Dear Hannah,

I have figured out about comb() and perm() functions.
I know also about sin(90 deg), cos(90 deg), tag(90 deg).

-I cannot get arcsin, arccos, arttan, to return in degrees
mode by default. How can I use deg or rad with these functions,
without having to invoke 180/pi?

-Also, how can I disable final decimal place rounding?

Infinite thanks for your help, and replying to messages like mine!


________________________________

**Comment by rickhg12hs** [comment]
@PowerUser1234 This might help you find functions, etc., in `qalc`.
```
> find combination
comb (Combinations)	

For more information about a specific function, variable, unit, or prefix, please use the info command (in interactive
mode).

> find permutation
perm / variations (Permutations (Variations))	

For more information about a specific function, variable, unit, or prefix, please use the info command (in interactive
mode).

> help comb

Function: Combinations

comb(Objects, Size)

Returns the number of possible arrangements of an unordered list with a number of objects to choose from and a list
size. If there are three objects (1, 2 and 3) that are put in a list with place for two, the alternatives are [1, 2],
[1, 3], and [2, 3], and thus the number of combinations is 3.

Arguments
Objects: an integer ≥ 1
Size: an integer ≥ 1

Expression: \x!/(\y!*(\x-\y)!)

> help perm

Function: Permutations (Variations)

perm(Objects, Size)
variations

Returns the number of possible arrangements of an ordered list with a number of objects to choose from and a list size.
If there are three objects (1, 2 and 3) that are put in a list with two positions, the alternatives are [1, 2], [2, 1],
[1, 3], [3, 1], [2, 3] and [3, 2], and thus the number of permutations is 6.

Arguments
Objects: an integer ≥ 1
Size: an integer ≥ 1

Expression: \x!/(\x-\y)!

> 
```

**Comment by PowerUser1234** [comment]
Thanks for the heads up about comb() and perm().

I have figured out about comb() and perm() functions.
I know also about sin(90 deg), cos(90 deg), tag(90 deg).

-I cannot get arcsin, arccos, arttan, to return in degrees
mode by default. How can I use deg or rad with trigonometry
inverse functions, without having to invoke 180/pi?

-If not possible, how do I alter the default angle unit between
radians and degrees, and vice versa, from the command line?

-Also, how can I disable default final decimal place rounding
from the command line, so that at the end of precision,
the final decimal place is always just truncated alone, and
nothing more is done to that digit?

Infinite thanks for your help, and replying to messages like mine!

________________________________

**Comment by rickhg12hs** [comment]
@PowerUser1234  What I actually wanted to highlight is `find`, `help`, and `info`.  Using these you can probably find what you need and how to use it.

**Comment by PowerUser1234** [comment]
I have been trying to do the very thing, it's just that I still cannot
figure out how to translate what it states into the typing I need
to carry out, on the command line, to generate the behaviour I am after.

I have been typing

qalc -t -s "precision 30" 1/7

as a general example.  I need to stick to non-interactive mode.

-Can someone kindly reply with an active example of how I can
gel this with the statement that will disable final decimal
place rounding at default, so that the default becomes truncation,
on the qalc command line?

-How also may one alter the default angle unit from
radians to degrees, and degrees to radians, at the command line?
________________________________

**Comment by PowerUser1234** [comment]
To whom is may concern,

I have figured out that I need to use

-s "angle_unit 2"

and similar to change the default angle unit successfully.

However, I cannot quite work out what to type
in order to prevent final decimal place rounding,
on the Windows command line in non-interactive mode.
Can someone please reply with the command(s) required, please?
________________________________

**Comment by PowerUser1234** [comment]
Don't worry about it any further!  The answer seems to be

-s "ivdisp 5"
________________________________

**Comment by rickhg12hs** [comment]
@PowerUser1234 Since you opened the issue, you should be able to `Close` it too.

**Comment by PowerUser1234** [comment]
I have only been taking part in the correspondence by email.  I didn't know that it was
being duplicated or echoed elsewhere.

Anyway, many thanks for the help, I have gotten there in the end!
________________________________

**Comment by rickhg12hs** [comment]
Welcome to GitHub Issues!  :-)
https://github.com/Qalculate/libqalculate/issues/363

**Comment by PowerUser1234** [comment]
It seems that with the following two commands, the first one gives me what is expected,
but the second one is not.  Why does the first one truncate the value one, while the second
one rounds the final decimal places, and truncates?

I am after truncation with no rounding in all case:

>qalc -t -s "ivdisp 5" -s "angle_unit 2" -s "precision 5" pi
3.1415

>qalc -t -s "ivdisp 5" -s "angle_unit 2" -s "precision 5" 1/7
0.14286

?
________________________________

**Comment by hanna-kn** [comment]
> It seems that with the following two commands, the first one gives me what is expected, but the second one is not. Why does the first one truncate the value one, while the second one rounds the final decimal places, and truncates? I am after truncation with no rounding in all case:
> qalc -t -s "ivdisp 5" -s "angle_unit 2" -s "precision 5" pi
> 3.1415
> qalc -t -s "ivdisp 5" -s "angle_unit 2" -s "precision 5" 1/7
> 0.14286 ?

For rational numbers you'll need to activate the repeating decimals option (`repeating decimals`/`repdeci`), e.g. qalc -t -s "repdeci 1" 1/7 (= 0.142857 142857…).

You can save these options if you use the `set` command in interactive mode (e.g. `set repdeci`). Instructions for qalc are included in the manual (https://qalculate.github.io/manual/qalc.html).

**Comment by PowerUser1234** [comment]
I have gotten "repdeci" to work on its own, but I land
problems when I combine it with "prec", particularly
with a smaller "prec" value:

qalc -t -s "repdeci 1" -s "prec 4" 1/7

Can this be avoided when including both "repdeci" and "prec" setting?
________________________________

**Comment by PowerUser1234** [comment]
There are problems when the "prec" value is less than the number
of decimal place pattern, "repdeci 1" number of digits.
Is there a way to harmonize these two together, under mutual circumstances?
________________________________

**Comment by PowerUser1234** [comment]
How can I turn off final decimal place rounding in these circumstances?
Particularly if I can't know or see if the repeating decimal pattern
ends after the precision cut off, or not?

>qalc -t -s "repdeci 1" -s "prec 4" -s "angle_unit 2" -s "ivdisp 5" 1/7
________________________________

**Comment by hanna-kn** [comment]
> There are problems when the "prec" value is less than the number
of decimal place pattern, "repdeci 1" number of digits.
> Is there a way to harmonize these two together, under mutual circumstances?

No. It would be problematic for rational number which requires many digits (e.g. `qalc -t -s "repdeci 1" -s "precision 1000000" 1/450563` returns 450 574 characters after a few minutes.

The proper solution, for both irrational and rational numbers, is to use `trunc()` (e.g. trunc((1/7)*10^5)/10^5). You can add a function to simplify this (e.g. using the command `function tr trunc(x*10^y)/10^y`, which creates a function with the value as first argument and desired number of decimals as second argument, e.g. `qalc -t "tr(1/7, 5)"` returns 0.14285. Alternatively, use precision instead of a second argument with command `function tr trunc(x*10^(precision-ceil(log10(x))))/10^(precision-ceil(log10(x)))` (e.g. `qalc -t -s "precision 5" "tr(1/7)"`).

I will consider adding an option to truncate numbers in the result in the next version.

**Comment by PowerUser1234** [comment]
I was aware that trunc() could be used to achieve this, however I see this as somewhat inefficient.
My thinking is that the final decimal place rounding is like an artifact, and so there should
be some setting to just turn it off, prevent its introduction.

I think that introducing such as   -s "deciround 0" in the next version would be great.

My only question then is, do you have a guess about how far away 3.23 may be?
________________________________

**Comment by hanna-kn** [comment]
> My only question then is, do you have a guess about how far away 3.23 may be?

At least a month.
