### ISSUE TITLE
Lack of command line option, or GUI option, to disable Final Decimal Place Rounding.

### ISSUE THREAD

**Issue by PowerUser1234** [Qalculate/libqalculate#368]
1) Tests reveal that the "precision" setting only begins counting from the left, first non-zero digit. However,
    those zeros can be significant, which imples that the zero digits should be counted and included. 
    For example:

>qalc -t -s "exp 0" -s "appr 2" -s "repdeci 0" -s "angle_unit 2" -s "prec 40" 1/17
0.05882352941176470588235294117647058823529, incorrect.

2) It is the situation, which is pretty well a bug, that version 3.22 of Qalculate! on the command line posseses no consistent, sole object manner to disable final decimal place rounding.  By default, if a rational value is truncated by

**-s "prec v"**

in a situation where the expression is a rational value, and the subsequent decimal value is 5 or higher, the final rational decimal point is rounded up by default.  This is done instead of sheer truncation at that point, and the disregarding of the subsequent decimal point, which in fact may be what is needed.  Consider the following examples:

>qalc -t -s "exp 0" -s "appr 2" -s "repdeci 0" -s "angle_unit 2" -s "prec 5" pi
3.1415, correct.

>qalc -t -s "exp 0" -s "appr 2" -s "repdeci 0" -s "angle_unit 2" -s "prec 7" sqrt(2)
1.414213, correct.

>qalc -t -s "exp 0" -s "appr 2" -s "repdeci 0" -s "angle_unit 2" -s "prec 4" 1/7
0.1429, incorrect.

>qalc -t -s "exp 0" -s "appr 2" -s "repdeci 0" -s "angle_unit 2" -s "prec 2" 1/8
0.13, incorrect.

Qalculate 3.22, particularly the bundled binary, non-installation version, needs to be patched to either remove the present defaulting behaviour, and default to truncation only behaviour, or provide a gui switch and a command line switch to disable this behaviour.  It could look like:

final decimal place rounding
**-s "fdeciround off"**

It is my hope that maybe this could be implemented earlier, rather than later! :)

**Comment by hanna-kn** [comment]
Done (option `truncate` has been added, despite that you haven't provided a single real argument for your request).

**Comment by PowerUser1234** [comment]
1#) I have consulted the online documentation. I have downloaded the file

qalculate-3.22.0-x64.zip

and have tried:

-----------------------------------------------------------------------------------------------------------------------
>qalc -t -s "exp 0" -s "appr 2" -s "repdeci 0" -s "angle_unit 2" -s "prec 1" -s "trunc on" 1/17

>qalc -t -s "exp 0" -s "appr 2" -s "repdeci 0" -s "angle_unit 2" -s "prec 1" -s "trunc 1" 1/17
-----------------------------------------------------------------------------------------------------------------------

etc...

There is a new function called trunc() under qalc --list trunc. Which is indeed is you described.

However, this approach only rounds towards an integer value, and does not reference the final decimal
place initially.  What I need is a -s "option value" setting that will turn off the final decimal place rounding
behaviour in computation to start with, instead of this inefficient approach, which
alters extra data after the fact, and has to shuffle digit places around, to the right, and then left.

2#) What I have also managed to find is that the following input produces this:

-------------------------------------------------------------------------------------------------------
>qalc -t -s "exp 0" -s "appr 2" -s "repdeci 0" -s "angle_unit 2" -s "prec 2" 1/17
0.059
-------------------------------------------------------------------------------------------------------

Here, in -s "prec 2" I have asked for 2 significant figures, and qalc has given me 4.
In this context, the zero digits present are necessary placeholders for further
non-zero digits.  Shouldn't "prec" count all digits beginning from the left hand side?
Is this a change possibility?

________________________________

**Comment by hanna-kn** [comment]
> I have consulted the online documentation. I have downloaded the file qalculate-3.22.0-x64.zip and have tried:
> qalc -t -s "exp 0" -s "appr 2" -s "repdeci 0" -s "angle_unit 2" -s "prec 1" -s "trunc on" 1/17 qalc -t -s "exp 0" -s "appr 2" -s "repdeci 0" -s "angle_unit 2" -s "prec 1" -s "trunc 1" 1/17

The `truncate` option is available in the Git source code, but you will have to wait for the next official version before the binaries are updated.

> There is a new function called trunc() under qalc --list trunc.

That function has existed for almost 20 years...

> -------------------------------------------------------------------------------------------------------
> qalc -t -s "exp 0" -s "appr 2" -s "repdeci 0" -s "angle_unit 2" -s "prec 2" 1/17
> 0.059 ------------------------------------------------------------------------------------------------------- Here, in -s "prec 2" I have asked for 2 significant figures, and qalc has given me 4. In this context, the zero digits present are necessary placeholders for further non-zero digits. Shouldn't "prec" count all digits beginning from the left hand side? Is this a change possibility?

No. That is not how significant figures work (https://en.wikipedia.org/wiki/Significant_figures). There is however a `max decimals` (or `maxdeci`) option (both in qalc and the GUIs).

**Comment by PowerUser1234** [comment]
Dear Hannah,

I have tested -s "maxdeci v", and it works as expected!

All this is brilliant news.  Particularly if "truncate" becomes a -s option on the command line,
to apply at the final decimal place that -s "prec v" -s "maxdeci v" allows.

-Will that be the case?

-Will this be updated in the official download version, say, by the end of January?

Thanks for all your attention so far, and a Merry Christmas and Happy New Year!

S.M.
________________________________

**Comment by PowerUser1234** [comment]
Dear Hannah,

you did send in an email communication, at one point, that there will be a new release of Qalculate! in 2022, 
possessing a truncate switch at the command line.  It is Febuary now.  How far away is that version or release, 
presumably, version 3.23?

**Comment by hanna-kn** [comment]
>  It is Febuary now. How far away is that version or release, presumably, version 3.23?

Version 4.0 will be released on Monday.

**Comment by PowerUser1234** [comment]
That is brilliant news!  Can you reply to me here with an example of how the final decimal place truncate command will work,
and can be included, at, say, the Windows 10 command line?

**Comment by PowerUser1234** [comment]
-It is UTC + 9:30 time where I am.  On my clock, it is 1:25pm, 14-Feb-2022.  There seems to be no version 4 download that I can find.  I will check again, this evening.

?
