### ISSUE TITLE
Crash with a simple equation

### ISSUE THREAD

**Issue by galileo-pkm** [Qalculate/libqalculate#372]
qalculate-3.22.0-1.fc35

`> multisolve([x+y=8; x+z=13; y+z=14]; [x; y; z])
/usr/include/c++/11/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = long unsigned int; _Alloc = std::allocator<long unsigned int>; std::vector<_Tp, _Alloc>::reference = long unsigned int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
`

**Comment by hanna-kn** [comment]
Fixed.

Note that `multisolve([x+y=8; y+z=14; x+z=13]; [x; y; z])` works.
