### ISSUE TITLE
Unicode superscripts followed by unicode plus-minus (uncertainty) is parsed incorrectly

### ISSUE THREAD

**Issue by schuelermine** [Qalculate/libqalculate#373]
`5²±1` is parsed as `5^(2±1)`, but should be parsed as `(5^2)±1`.

**Comment by hanna-kn** [comment]
This is an issue for superscript followed by any operation with equal or higher precedence. `5²` is interpreted as `5^(2)`.

**Comment by hanna-kn** [comment]
Fixed.
