### ISSUE TITLE
'strings' tests fails on arm64, armhf, ppc64el and s390x

### ISSUE THREAD

**Issue by rikmills** [Qalculate/libqalculate#378]
Version: 3.22.0
Builds: https://launchpad.net/ubuntu/+source/libqalculate/3.22.0-1
Architectures: arm64, armhf, ppc64el and s390x
and bug in Debian: 'libqalculate FTBFS on architectures where char is unsigned' https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003003

(In Debian the failure also occurs on riscv64 as Ubuntu does not yet run build time tests by default on that, where it presumably would occur if we did)

> [0m[31m
> Mismatch detected at line 42
> char(0xD8)
> expected ''Ø''
> received '"Ø"'

**Comment by hanna-kn** [comment]
This is a quite serious issue that affects much of the code handling Unicode characters. https://github.com/Qalculate/libqalculate/commit/a822d5bf7e0743a8a14ead920ae512f895ca87b2 should fix this, but there might be some char comparisons, that assume that char is signed, that I've missed. The code in qalculate-qt and qalculate-gtk will also need some fixes.

**Comment by hanna-kn** [comment]
I've now confirmed, using `-funsigned-char`, that https://github.com/Qalculate/libqalculate/commit/a822d5bf7e0743a8a14ead920ae512f895ca87b2 fixes this issue. I recommend compilation with `-fsigned-char` as a temporary solution for 3.22.0 and older versions.
