### ISSUE TITLE
[Feature request] Converting between number bases as a function

### ISSUE THREAD

**Issue by sdasda7777** [Qalculate/libqalculate#379]
Hi, could it be possible to add function for converting between number bases?
The current way by setting expression base and result base is kinda hidden (especially using the classic interface), involves lot of clicking around, and is far from ergonomic if you have to convert multiple times in one calculation.
It sounds like a no-brainer, but I wasn't able to find any issues that would relate to this, and the manual doesn't mention any such funtion either, so sorry if this is something that was discussed before.

**Comment by sdasda7777** [comment]
I see, that's huge, thanks for letting me know. 
I looked in the manual again, and it is in fact explained there, I just assumed if such feature exists it would be a function.
On the subject of manual, is there a version that has all pages combined into one page, making it simple to search for a keyword?

**Comment by hanna-kn** [comment]
> I just assumed if such feature did exist it would be a function

Functions affects the value, not the format, of numbers and expressions. E.g. there is no function for unit conversion.

> On the subject of manual, is there a version that has all pages combined into one page, making it simple to search for a keyword?

No. Although I guess that you can search in https://raw.githubusercontent.com/Qalculate/qalculate-gtk/master/doc/C/qalculate-gtk.xml (without appendices).

**Comment by sdasda7777** [comment]
That's not great, but I guess it's at least something. Thanks again.
