### ISSUE TITLE
Shortcuts for planck constant

### ISSUE THREAD

**Issue by stephtr** [Qalculate/libqalculate#381]
In the physics community ([as in LaTeX](https://docs.latexbase.com/symbols/hbar/)) it is usus to write the reduced planck constant as <kbd>hbar</kbd>. I would find it useful, if Qalculate would also include that by default.
In addition, it would be nice, if the ordinary planck constant could show up when entering just <kbd>h</kbd>.

**Comment by foreachthing** [comment]
Please don't. 
I have never used Plank Constant and never will. 
I'd much father assign (user-) functins to custom keys on the keyboard - thanks for considering.

**Comment by stephtr** [comment]
> Please don't. I have never used Plank Constant and never will. I'd much rather assign (user-) functins to custom keys on the keyboard - thanks for considering.

But have you ever used `hbar` for something else? And does it matter to you if in the long list which appears when entering the letter `h` one entry is being added?

For me it's not about _everyone_ using it, but most people in the quantum physics community expecting it to work.

**Comment by hanna-kn** [comment]
Done (assuming that you meant the reduced Planck constant, 1.054 571 818 × 10<sup>−34</sup> J·s).

**Comment by hanna-kn** [comment]
> In addition, it would be nice, if the ordinary planck constant could show up when entering just `h`.

This seems reasonable and should ideally apply to to all special symbols that are similar to ordinary letters.

**Comment by stephtr** [comment]
That would be really useful 🙂

**Comment by foreachthing** [comment]
> But have you ever used `hbar` for something else? And does it matter to you if in the long list which appears when entering the letter `h` one entry is being added?
> 

I misunderstood your request!!! I thought you what that `hbar` on key [h]! Sorry to interfere in your conversation *shame*.

**Comment by stephtr** [comment]
It's perfectly fine 🙂

**Comment by idamir** [comment]
Very useful thing!
