### ISSUE TITLE
Conversion request

### ISSUE THREAD

**Issue by mturiansky** [Qalculate/libqalculate#383]
A common conversion that I have to do is from wavelength to energy. For example, I may want to convert from 550 nm to 2.25 eV. I can do this with the input `m_to_J / (550 nm) to eV`, but it would be much more convenient if `550 nm to eV` would present the same result. I tried looking through the manual, but couldn't figure out if this would be possible.

Anyway, thanks for this awesome utility!

**Comment by hanna-kn** [comment]
The problem with `nm to eV`, and more clearly `eV to nm`, is that meter is one of the base units that eV is derived from (1 eV = 1.602 176 634 × 10<sup>−19</sup> J, 1 J = 1 kg·m<sup>2</sup>·s<sup>−2</sup>). When _reciprocal_ meters (which the conversion factor applies to) are used, it should however be safe to guess the intention of the user.

**Comment by mturiansky** [comment]
Okay, I see. That makes sense. Being able to specify `(550 nm)^-1 to eV` is a reasonable compromise. Thanks for the help!
