### ISSUE TITLE
Function as argument

### ISSUE THREAD

**Issue by Wumianzhe** [Qalculate/libqalculate#385]
I am having trouble creating a function that applies a function that is an argument to another argument. Simplest example:

![image](https://user-images.githubusercontent.com/49762386/149657022-4d2a9bb3-c3a1-40c9-9dcc-fe67376d3222.png)

In advanced mode function looks like \x(\y). I also tried other combinations of \x, \y and parentheses, but was unable to achieve desired result. What i needed currently can be achieved using subfunction, but that might not be the case later.

**Comment by hanna-kn** [comment]
The function `replace(abs(\y),abs(),\x)` (abs can be replaced with any available function) should return the desired result. This might seem a bit hackish, and it might have been preferable if an internal function that either evaluates a text string or does exactly what you've asked for was available.

\x(\y) is interpreted as \x × (\y).
