### ISSUE TITLE
Crashes on "arc"

### ISSUE THREAD

**Issue by MithicSpirit** [Qalculate/libqalculate#390]
Running `qalc arc` in a shell crashes immediately with 
```
/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = long unsigned int; _Alloc = std::allocator<long unsigned int>; std::vector<_Tp, _Alloc>::reference = long unsigned int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```

This crash (same error message) occurs when using any input that contains `arc` (as its own word—`arcsin` doesn't trigger it). Note that this is also present when `qalc` is in interactive mode and in the GTK frontend (haven't tested on Qt). It is especially bad in graphical frontends due to calculate-as-you-type causing them to crash immediately when typing `arc`, even as a prefix for something like `arcsin`.

**Comment by hanna-kn** [comment]
Which version are you using?

I've only been able to reproduce this with the current Git version, with -D_GLIBCXX_ASSERTIONS. This has now been fixed.

**Comment by MithicSpirit** [comment]
Oh yeah I'm using the current git version too (from the [AUR](https://aur.archlinux.org/packages/libqalculate-git/)). Just recompiled it and seems to be working correctly now, thanks!
