### ISSUE TITLE
e^x=0 is solved weirdly

### ISSUE THREAD

**Issue by schuelermine** [Qalculate/libqalculate#395]
Typing `e^x=0` gives the weird result `x = 2i * pi * n - (+infinity)`. While it is true that `e^(2i*pi*n-infinity)` results in zero, this is also true of `e^-infinity`.

**Comment by hanna-kn** [comment]
`e^x=0` is true for both real and complex infinity.

`e^x=y` is simplified as `x = 2 pi * i * n + ln(y)`, and ln(0) returns -infinity. I agree that the result is problematic, but if x is not defined as real (in which case the expression returns false), `e^-infinity` is not the only solution.

**Comment by hanna-kn** [comment]
I decided that x=-infinity is consistent with the behaviour in other cases and made the change despite my previous reservations.

**Comment by schuelermine** [comment]
Thank you!
