### ISSUE TITLE
feature request: local variable definitions

### ISSUE THREAD

**Issue by nojus297** [Qalculate/libqalculate#400]
Currently one can set a variable in CLI using syntax `variable <name> <value>`. However, values set like this persist to future sessions, thus possibly polluting the namespace, especially when using short variable names, such as `x`, `m` or `n`. 

I propose to add local variable definitions, maybe something like `local <name> <value>`. It would work the same as `variable`, but all set variables would be wiped out when exiting session (not saved to data files). As a side note, it would be nice to have silent local variable shadowing, that is not having to type `y<enter>` every time you change value of a local variable.

**Comment by hanna-kn** [comment]
The syntax `<name>:=<value>` saves the value as a temporary variable. Likewise does the store and save commands by default. There is also a function for variable creation (`save(Value, Name[, Category][, Title][, Precalculate expression])`).

**Comment by nojus297** [comment]
Missed that, this is essentially what I was asking for. Thanks!
