### ISSUE TITLE
missing function to delete variable

### ISSUE THREAD

**Issue by ngrcld** [Qalculate/libqalculate#404]
I can't find a function to delete a variable.
The opposite of: save("value";name)
For example: delete(name)

Useful for example after "A global unit or variable was deactivated. It will be restored after the new variable has been removed." without having to use the app menu.

**Comment by hanna-kn** [comment]
You can use the command `/delete NAME` (all commands from the CLI, qalc, can be used in the GUIs if preceded by slash). The global object will however not be activated until the application has been restarted (for temporary variables, deletion is in this case superfluous).

**Comment by ngrcld** [comment]
ok, thanks
