### ISSUE TITLE
Can’t plot x!

### ISSUE THREAD

**Issue by schuelermine** [Qalculate/libqalculate#405]
Here is `gamma(x+1)` being plotted correctly:
![Screenshot from 2022-02-24 10-04-00](https://user-images.githubusercontent.com/48802534/155492851-8d5847c2-7da5-4e2d-b09e-fe5926221e98.png)
And here is `x!`, ideally identical, not being plotted at all:
![Screenshot from 2022-02-24 10-03-56](https://user-images.githubusercontent.com/48802534/155492863-3fb6e3ce-9622-48fc-83dd-01cac593ffff.png)

This is `qalc`, version 4.0.0.  
This also occurs in version 3.22.0.

**Comment by hanna-kn** [comment]
Factorial function only accepts integers. You need to make sure that the x values are integers (I suggest that you use step size instead of number of samples, e.g. `plot(x!,1, 8, 1, x, 1)`).

**Comment by schuelermine** [comment]
I see, that makes sense.
Sorry.
