### ISSUE TITLE
Crash caused during hex digit entry in `rand` function

### ISSUE THREAD

**Issue by zvodd** [Qalculate/libqalculate#406]
### Bug:
Upon entering a hexadecimal digit value (with the prefix `0x`) after the string `rand(` the tool tip displays, before the entire application becomes unresponsive. Ungraceful crash with a single CPU core maxed out and external intervention required to kill proccess.

### Reproduce Steps:

In the main formula entry text line:
 - Enter `rand(0,)` or `random(0,)`
 - Move text carrot back 2 characters (in between `,` and `)` ) 
 - Enter `0xffffffff`.
 - [? Possible Step ?] Hover mouse over current text entry line to trigger tool-tip with documentation for "random" function
 
At this point the application should freeze up or enter some kind of soft-lock state, becoming unresponsive.

Hopefully that is clear enough to reproduce.
* Also the Number Bases Panel (<kbd>Ctrl</kbd>+<kbd>B</kbd>) was open/expanded in both cases

### Platform & Version:
Tested in latest 3.X and latest 4.0 `qaculate-qt.exe` 64bit in Windows 10.
Other versions untested.

**Comment by hanna-kn** [comment]
This is occurs because of inability to abort creation of an extremely large vector (the problematic expression returns billions of random numbers).

**Comment by hanna-kn** [comment]
Fixed.
