### ISSUE TITLE
How to input a date in CLI mode

### ISSUE THREAD

**Issue by Leoongithub** [Qalculate/libqalculate#410]
In interactive mode, I can use `"2022-3-7"`. But how should I input it in non interactive mode (`qalc xxxx`)?

**Comment by hanna-kn** [comment]
Put quotation marks around the whole expression and use different quotation marks for the date, e.g. `qalc '"2022-03-07"-"2022-02-24"'`, or escape the quotation marks, e.g. `qalc \"2022-03-07\"+2d`. Note that this won't work for expressions that only consist of a single date (which however wouldn't be very useful).
