### ISSUE TITLE
Exchange rates - nbrb.by timeout

### ISSUE THREAD

**Issue by mooreye** [Qalculate/libqalculate#416]
When using `qalc` in CLI and trying to update conversion rates, I've been getting the following error for quite a few days already:

`Failed to download exchange rates from nbrb.by: Failed to connect to www.nbrb.by port 443 after 3771 ms: Connection timed out`

**Comment by hanna-kn** [comment]
See https://github.com/Qalculate/qalculate-gtk/issues/349.

**Comment by mooreye** [comment]
> See [Qalculate/qalculate-gtk#349 (comment)](https://github.com/Qalculate/qalculate-gtk/issues/349#issuecomment-1059117686).

**Comment by hanna-kn** [comment]
@renyhp 

Which version are you using?
Recent versions only use a separate source (nbrb.by) for exchange rates when the BYN currency has actually been used and the primary exchange rates sources have failed (and a secondary source, which usually fails, doesn't).

**Comment by renyhp** [comment]
Oops, it looks like I installed it via apt (on Linux Mint 21.2) and that version is pretty old (3.22.0). You're not maintaining that anymore?
