### ISSUE TITLE
Trouble plotting circle

### ISSUE THREAD

**Issue by GreySky1** [Qalculate/libqalculate#419]
I am attempting to plot a circle using the command `plot((x^2) + (y^2))` however qalc gives the output `plot((x^2) + (y^2)) = 0` and my gnuplot window appears empty. I have tried using the built-in circle and circumference functions but to no avail, is there anything I am doing wrong?

(sorry for such a basic question!)

**Comment by hanna-kn** [comment]
Qalculate does not support y in the plot function. You will need to solve y=x^2+y^2, for y, first, which results in two functions. Use either `plot(solve(y=x^2+y^2, y), −1/2, 1/2)` or `plot([(1 + sqrt(1 − 4x²))/2, (1 − sqrt(1 − 4x²))/2], −1/2, 1/2)`.

**Comment by GreySky1** [comment]
Your second suggestion works wonderfully, i had a feeling solving for y might be part of the solution. Thank you!
