### ISSUE TITLE
Gravitational constant behaves strangely

### ISSUE THREAD

**Issue by Tomaasci** [Qalculate/libqalculate#424]
![Screenshot_20220401_173143](https://user-images.githubusercontent.com/42543513/161295253-ad8c5165-7440-4c78-884f-4548e6de0cd3.png)
This happened when I tried calculating the gravitational force between two 70kg people. The result wasn't in newtons, but in micrograys * meter / megagram. Is this an error on my part or is this a bug?

**Comment by hanna-kn** [comment]
Fixed in version 4.1.1.
