### ISSUE TITLE
randpoisson segfault

### ISSUE THREAD

**Issue by and-nissa** [Qalculate/libqalculate#427]
`uname -srmo`: Linux 5.15.32_1 x86_64 GNU/Linux
`qalc -v`: 3.20.1

randpoisson segfaults sometimes. interestingly, if i repeatedly use something else as input, like `(0, 5)`, it doesn't segfault (this could be arbitrary though).

```qalc
> randpoisson(3, 5)

  randpoisson(3, 5) = [0, 0, 0]

> randpoisson(3, 5)

  randpoisson(3, 5) = [0, 0, 0]

> randpoisson(3, 5)

  randpoisson(3, 5) = [0, 0, 0]

> randpoisson(3, 5)
<segmentation fault>
```

by the way, i don't know what poisson distribution is, so i don't know if the output it gives before segfaulting is expected.

running `qalc` with `strace`, the last syscall seems to always be `clock_nanosleep`.

can anyone else replicate this?

**Comment by hanna-kn** [comment]
Fixed.
