### ISSUE TITLE
Add BDT currency

### ISSUE THREAD

**Issue by munim** [Qalculate/libqalculate#43]
Hi,

Can anyone please suggest how to add Bangladeshi Taka (BDT). Something that I want to do is

    > 30USD to BDT

Currently it says

    warning: Error(s) in unitexpression.
    30 * dollar = $30

Please suggest

**Comment by hanna-kn** [comment]
Fixed (support for over 100 additional currencies was added).

**Comment by munim** [comment]
Thanks for your response @hanna-kn 

I see you've committed the code to support additional currencies but do you've a timeline when it will be released as a new version?

Thanks for that.
Cheers.

**Comment by hanna-kn** [comment]
The next version will probably be released 2017-09-25.
