### ISSUE TITLE
Distinguish between si(x) and sinc(x)

### ISSUE THREAD

**Issue by funnym0nk3y** [Qalculate/libqalculate#431]
As per #51 the sinc-function was added. And as stated there, there is also the si-function. However as far as my field of study is concerned, they are similar but not the same: 

- si-function: `si(x) = sin(x)/x`
- sinc-function: `sinc(x) = si(pi x) = sin(pi x)/(pi x)`

**Comment by hanna-kn** [comment]
I haven't been able to find any references to this definition of the si-function. The sinc-function has two definitions (normalized and unnormalized) depending on context. According to Wikipedia "the unnormalized sinc function is often called the [sampling function](https://en.wikipedia.org/wiki/Sampling_function), indicated as Sa(x)" (https://en.wikipedia.org/wiki/Sinc_function). WolframAlpha uses the unnormalized definition for sinc(x), while Matlab uses the normalized variant.

Wikipedia provides a different definition for si(x) in the context of [trigonometric integrals](https://en.wikipedia.org/wiki/Trigonometric_integral):
> By definition, Si(x) is the antiderivative of sin x / x whose value is zero at x = 0, and si(x) is the antiderivative whose value is zero at x = ∞.

**Comment by funnym0nk3y** [comment]
Unfortunately that topic is a little inconsistent regarding the si-function. The german wikipedia even states that a proper distinction is unusual in english literature. However to me it seems that a normalized sinc-function is more popular (Python, Julia). Instead of defining two separate functions a settings switch could be an option?

**Comment by hanna-kn** [comment]
> Instead of defining two separate functions a settings switch could be an option?

This might be the best solution, considering the circumstances. It would be easier to add a sinc<sub>pi</sub> function but it would hardly be more convenient for the user than multiplying the function argument by pi. Changing to default definition of the sinc function would create compatibility issues with earlier version, which I would like to avoid, even though it might otherwise have been preferable.

**Comment by hanna-kn** [comment]
The user will now be asked for the desired sinc() variant (in qalc, not yet implemented in GUIs).

**Comment by funnym0nk3y** [comment]
Nice, thanks!
