### ISSUE TITLE
Adding floats gives me divisor

### ISSUE THREAD

**Issue by trev-dev** [Qalculate/libqalculate#435]
I _feel_ like some recent change has caused this, but I could be mistaken. Bare with me.

When I add some numbers/floats together, I expect a float return type.
Eg: `20 + 88 + 0.48 + 450.64 + 0.4 + 0.32 + 1.92 + 87.68 = 649.44`

Instead what I am getting is a divisor:
`20 + 88 + 0.48 + 450.64 + 0.4 + 0.32 + 1.92 + 87.68 = 16236/25`

I think "okay, fair enough" and enter a expression for that divisor and it just gives me that divisor back: `16236 / 25 = 16236/25` - Amusing! Not what I'm looking for.

Have I somehow flicked a switch somewhere or do I need to structure my expressions differently now?

**Comment by hanna-kn** [comment]
`set fr -1` (or cycle through fraction modes using Ctrl+F)  should fix this.
