### ISSUE TITLE
Qalc command is trying to be too smart.

### ISSUE THREAD

**Issue by BossCode45** [Qalculate/libqalculate#440]
When using this command to do physics I want to use planck's constant sometimes, and qalc provides this as a variable which is great. However, what I do not want is planck's constant in "yJ*s", I just want it as 6.62607015 × 10-34.
The same goes for other constants such as the speed of light, so is there a way for me to do this.
I couldn't find a forum so am posting here instead.

**Comment by hanna-kn** [comment]
Either use the `nounit()` function (e.g. `nounit(c)` equals 299 792 458) or deactivate "variable units" (using `set varunits 0` / `set variable units off`, or with command line option `-s "varunits 0"`, in qalc, _Mode->Units in Physical Constants_ in qalculate-gtk, or _Preferences->Units & Currencies->Enable units in physical constants_ in qalculate-qt).

> I couldn't find a forum so am posting here instead.

https://github.com/Qalculate/libqalculate/discussions

**Comment by BossCode45** [comment]
Thanks :D
