### ISSUE TITLE
Feature request: Disable persistent history (privacy and security)

### ISSUE THREAD

**Issue by mvasi90** [Qalculate/libqalculate#443]
Hello everyone,

I can't see any option to disable the persistent history (on file).
This is very useful for advanced users that need to calculate arbitrary inode sectors in filesystems, hashes of derived passwords, etc. If this information is stored in the disk, there is no privacy and security.

**Comment by hanna-kn** [comment]
Until such an option has been added, you can either delete the history file (`~/.config/qalculate/qalc.history`) after each run (e.g. run qalc from a script which does this automatically), or make the directory not writable, e.g. using `cmod -w ~/.config/qalculate` (this does not affect the ability to update to configuration file).

**Comment by mvasi90** [comment]
Thank you very much @hanna-kn.

I didn't know that the program would work if you don't have write permissions.

Deleting the history file is not a secure option, even using shred for secure deletion with 32 passes (no SSD, of course), because the data can be recovered.

So far I used tmpfs (encrypted RAM).

**Comment by hanna-kn** [comment]
`clear history` command (clears current expression history immediately) and option (clear / do not save history on exit) have now been added.
