### ISSUE TITLE
Iterative Modulo of very large Numbers

### ISSUE THREAD

**Issue by keinezeit8** [Qalculate/libqalculate#447]
## General Problem and Solution

When calculating with very large numbers, one might reach an overflow or loose necessary precision. This is not always solvable. But when calculating with modulo there are clever tricks to help out.

Lets imagine one wants to calculate the last digit of 3^(3^(3^3)). This could be done with 'mod(3^3^3^3;10)'. But the result is 'mod(3^(7 625 597 484 987); 10)' and a floating point overflow error.

This could also be calculated like so:
$$3 \cdot 3 \mod 10 = 9$$ $$9 \cdot 3 \mod 10 = 7$$ $$7 \cdot 3 \mod 10 = 1$$ $$1 \cdot 3 \mod 10 = 3$$  $$\vdots$$
Disregarding the obvious pattern in this example witch could improve performance dramatically, it is possible to calculate the remainder accurately without risking an overflow.

[Further Reading](https://www.geeksforgeeks.org/modular-multiplication/)

***

## Optimisation
When calculating the same calculation very often, like in the example above, a periodicity can be observed.
This could be used to short cut many calculations.
[Wikipedia](https://en.wikipedia.org/wiki/Modular_exponentiation)

**Comment by hanna-kn** [comment]
Done (primarily using [mpz_powm](https://gmplib.org/manual/Integer-Exponentiation)).
