### ISSUE TITLE
(Feature Request) Ability to convert from IEEE 754 formats other than float (i.e. half, double, quadruple, octuple)

### ISSUE THREAD

**Issue by sdasda7777** [Qalculate/libqalculate#448]
Hi, would it be possible to add the ability to convert from IEEE 754 formats other than float? (i.e. half, double, quadruple, octuple)
I know it is possible to convert to them, but I recently needed to convert from them to decimal, and to my surprise I couldn't find a single tool that would allow that, so in the end I had to do it in code, which is not great for many reasons, to be honest.

**Comment by hanna-kn** [comment]
`float()` (and related functions) takes a second optional argument argument specifying the number of bits (default is 32, but you can enter 16 for half, 64 for double, etc.). There is also a third argument which allows you to specify a non-standard number of exponent bits.
```
> float(0 10100 0000000000, 16)

  float(0101000000000000, 16) = 32

> help float

Function: IEEE 754 Floating-Point

float(Floating-point number (binary)[, Number of bits][, Number of exponent
bits])

Reads a number in a IEEE 754 floating-point format. The number will be read as a
binary number, unless it contains digits other than 1 or 0. If the third
argument (exponent bits) is set to zero, the standard number of exponent bits
will be used (e.g. 8 for 32-bit format).

Arguments
Floating-point number (binary): a text string
Number of bits: an integer ≥ 8 and ≤ 18446744073709551615 (optional, default:
32)
Number of exponent bits: an integer ≥ 0 and ≤ 18446744073709551615 (optional,
default: 0)

Requirement: "Number of exponent bits"<"Number of bits"-1
```
In the GUIs you can select 16, 32, 64, 80, or 128-bit format in the floating point conversion dialog.

**Comment by sdasda7777** [comment]
Ah, I see, I completely missed that. Thank you.
