### ISSUE TITLE
(1 = 1) = false

### ISSUE THREAD

**Issue by Samisafool** [Qalculate/libqalculate#449]
![image](https://user-images.githubusercontent.com/59611020/178129937-75fd8246-d1fb-4237-8ea7-59f11246c3c7.png)

```
> 0.999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999 = 0.999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999998

  (1 = 1) = false

> 
```

Uhhh... yeah I think the response could be a bit better, but I realise this is a bit arcane

**Comment by hanna-kn** [comment]
I've now modified the output. `(0.9999999999… = 0.9999999999…) = false` will be displayed instead (an alternative solution would be to output `≈ (1.0000000000 = 1.0000000000) = false`).
