### ISSUE TITLE
² interpreted differently than ^2 for multiple digits

### ISSUE THREAD

**Issue by Fabian42** [Qalculate/libqalculate#451]
I found a very weird edge case:

* `qalc "1l/m^2"`→`(1 × liter) / (meter^2) = 1 mm` :heavy_check_mark:
* `qalc "10l/m^2"`→`10 × (liter / (meter^2)) = 10 mm` :heavy_check_mark:
* `qalc "1l/m²"`→`(1 × liter) / (meter^2) = 1 mm` :heavy_check_mark:
* `qalc "10l/m²"`→`10 × ((liter / meter)^2) = 10000000 mm⁴` :negative_squared_cross_mark:

This also happens with e.g. `.1` and `01`, but not with `1/10 ` and also with `³`.

**Comment by hanna-kn** [comment]
Fixed.

**Comment by yashpalgoyal1304** [comment]
`if fixed: close()` 😛

**Comment by Fabian42** [comment]
I didn't even see that previous comment. Yes, I can confirm that it's fixed on the current `master` branch.

**Comment by yashpalgoyal1304** [comment]
anyways, i just came here to say that it's nice that python styled `**` (double asterisk) operator for exponent is also supported - that is much easier to enter via numpad as compared to the normal symbol since the `^` (caret) symbol is located in the far far wild west on the keyboard 😅

**Comment by hanna-kn** [comment]
> anyways, i just came here to say that it's nice that python styled ** (double asterisk) operator for exponent is also supported - that is much easier to enter via numpad as compared to the normal symbol since the ^ (caret) symbol is located in the far far wild west on the keyboard

It's even easier to not use any operator at all (works for units, e.g. `10 l/m2`).

**Comment by yashpalgoyal1304** [comment]
wow, that's nice to know for units. thanks 😊; for both and more (:
