### ISSUE TITLE
Conversion from ounce to liter not working

### ISSUE THREAD

**Issue by liquidev** [Qalculate/libqalculate#455]
`qalc -v`: 4.2.0

No matter what combination I try, I can't get it to work:
```
> 20 oz to l

  20 × ounce = 20 oz

> 20 oz to L

  20 × ounce = 20 oz

> 20 oz to liter

  20 × ounce = 20 oz
```

**Comment by hanna-kn** [comment]
Use the fluid ounce unit (fl_oz or FluidOunce) for volume.

**Comment by liquidev** [comment]
Oh, you're right. I'm not familiar with imperial units at all, hence my confusion.
