### ISSUE TITLE
qalc will not create ~/.config if it doesn't exist

### ISSUE THREAD

**Issue by kc2zgu** [Qalculate/libqalculate#456]
When starting qalc for the first time, if the `~/.config` directory doesn't exist (this will probably only be likely on non-GUI systems) it will not be created automatically, and creating `~/.config/qalculate` will fail:

```
$ qalc
Couldn't write preferences to
/home/user/.config/qalculate/qalc.cfg>

  0 = 0

>
$ mkdir ~/.config
$ qalc
>

```

**Comment by hanna-kn** [comment]
Fixed.
