### ISSUE TITLE
In input base >10 only numbers work

### ISSUE THREAD

**Issue by apiote** [Qalculate/libqalculate#46]
When input base is set to anything greater than 10 variables, functions and units don’t work. Parser thinks everything is a number.
In all the examples bellow output is in base 12.

```
$ qalc -s "input base 10"   
> 20 pi

  20 * pi ≈ 52.9B954

> log(20)

  log(20, e) ≈ 2.BB4761

> 20 a + 10 ha

  (20 * are) + (10 * hectoare) = 710 a

$ qalc -s "input base 8"    
> 20 pi

  16 * pi ≈ 42.32291

> log(20)

  log(16, e) ≈ 2.93304A

> 20 a + 10 ha

  (16 * are) + (8 * hectoare) = 580 a

$ qalc -s "input base 12"   
> 20 pi

  error: Character 'p' was ignored in the number "20pi" with base 12.
  24 * i = 20i

> log(20)

  error: Character 'l' was ignored in the number "log" with base 12.
  error: Character 'o' was ignored in the number "log" with base 12.
  error: Character 'g' was ignored in the number "log" with base 12.
  0 * 24 = 0

> 20 a + 10 ha

  error: Character 'h' was ignored in the number "10ha" with base 12.
  298 + 154 = 318
```

**Comment by hanna-kn** [comment]
That is intentional. It would, for example, be difficult for to program to know when to user means ampere instead 10, when typing "A". I guess it would be possible to guess the users intention based on white spaces and parentheses, but I have so far not considered it worth the effort for something I see little practical use for. For base 16, the 0x notation can be used instead (with decimal input base). I am however open to persuasion.

**Comment by apiote** [comment]
I was hoping I finally found *the* calculator with which I could perform calculations in dozenal (with TGM units, but that I’d add on my own). Dozenalists created their own digits for ten and eleven—respectively ↊ [U+218A] (or X) and ↋ [U+218B] (or E) which makes input unambiguous as I cannot find units ‘E’ or ‘X’ and non–ten–base modes don’t use E as 10 to the power of n (and input `*10^n` is not illogical). But I guess implementing this for just a single base as an exception from all other bases greater than ten would be painful.

For further reference—in dozenal—You can visit Dozenal Societies’ websites, [GB](http://www.dozenalsociety.org.uk/sitemap.html) or [US](http://www.dozenal.org).

**Comment by hanna-kn** [comment]
Fixed. Duodecimal numbers now uses 'X' or '↊' and 'E' or '↋', instead of 'A' and 'B'. E conflicts with exa prefix and both E and X is used by currency codes, but I find that acceptable. I am considering making this behaviour optional.

**Comment by apiote** [comment]
Thank You so much.
Making this behaviour optional seems like logical choice as there are those who use duodecimal just like all other bases with reference to base ten—i.e. with A and B—and not as a stand-alone base.
