### ISSUE TITLE
Add a clear function

### ISSUE THREAD

**Issue by Matr1x-101** [Qalculate/libqalculate#461]
Since I primarily use the keyboard for equations in qalculate (and also i use the terminal a lot :) ), I would like to see a function where if you typed "clear" or "clear()" it would clear the history in qalculate.

**Comment by hanna-kn** [comment]
I have now added support for the qalc command `clear history` in the graphical user interfaces (most commands in qalc are also supported in the GUIs, if prepended by `/`).

I have also added clear history to available keyboard shortcut actions.

I do not think that it would be appropriate to implement it as a mathematical function.
