### ISSUE TITLE
qalc: Unit conversion causes problems with uncertainty after use of trigonometric function

### ISSUE THREAD

**Issue by lauritzt** [Qalculate/libqalculate#462]
Example:

```
> arcsin(0.5 +/- 0.1) to deg

  error: Argument 3, Uncertainty is relative, in uncertainty() must be a boolean (0 or 1).
  arcsin(0,5±0,1) ≈ uncertainty(30,00000000°; 6,615946745°; 0,000000000°)
```

This issue is not present in Qalculate GTK.

**Comment by hanna-kn** [comment]
This issue occurs when approximation is set to exact (press Ctrl+E twice or enter `set appr -1` to set the default approximation mode). It has now been fixed.

**Comment by hanna-kn** [comment]
> Changing the approximation mode does not seem to work for me

Perhaps you are not using a recent version (in that case, enter the command `approximate` instead)?

> (presumably because of the trigonometric function).

Unlikely

**Comment by lauritzt** [comment]
I am using version 4.2.0 from the openSUSE Tumbleweed repositories.

To clarify, the approximation mode changes successfully, but the error still occurs. `approximate` does not behave any differently than Ctrl+E. (It's not a problem though.)

**Comment by hanna-kn** [comment]
The error occurs in approximate mode if angle unit is set to none (it occurs if the result before conversion contains a unit and/or a constant). Looking again at the result in the description of the issue, this (and not the approximation mode) was likely the reason the bug was triggered.

**Comment by lauritzt** [comment]
The angle unit was indeed set to none (this is also the reason the issue did not appear in Qalculate-GTK for me, as it was set to radians there),
