### ISSUE TITLE
failing uncertainty propagation / variance

### ISSUE THREAD

**Issue by SubhashBose** [Qalculate/libqalculate#463]
Uncertainty propagation work in simple arithmetic like addition (+)
`5±0.3 + 5±0.3 + 5±0.3 ≈ 15.00±0.52`

But it fails for other functions like total(), mean() etc
e.g., 
<pre>
> total(5+/-0.3,5+/-0.3,5+/-0.3)

  warning: Calculation of uncertainty propagation failed (using interval arithmetic instead).
  total([5±0.3  5±0.3  5±0.3]) ≈ 15.00±0.90
</pre>

it even fails if I try to run summation to loop over a vector of numbers
<pre>
>  z=[5±0.3,  5±0.3,  5±0.3]
> sum(element(z,\i), 1, elements(z))

  warning: Calculation of uncertainty propagation failed (using interval arithmetic instead).
  sum(element(z, i), 1, elements(z)) ≈ 15.00±0.90
</pre>

It seems the problem basically lies when the 'number+-error' values are stored in in a vector
<pre>
> z=[5±0.3,  5±0.3,  5±0.3]

  warning: Calculation of uncertainty propagation failed (using interval arithmetic instead).
  save([5±0.3  5±0.3  5±0.3], z, Temporary, , 1) ≈ [5.00±0.30  5.00±0.30  5.00±0.30]
</pre>

Why it behaves like this? any way around? or can this be fixed?

**Comment by hanna-kn** [comment]
Fixed (uncertainty propagation did not support vectors).

**Comment by SubhashBose** [comment]
Thanks. That's awesome.

**Comment by SubhashBose** [comment]
I think there is another related issue
elements() function return an approximate value instead of an exact value when the input vector has uncertainties

elements([1  2  3]) = 3  #exact value as expected
but
elements([1±0.1  2±0.1  3±0.3]) ≈ 3   # approxmmiate value which is not expected


Actually, I encountered an issue when passing on elements() value to genvector function limits. Apparenty genvector only works when min/max value is a exact value. 
<pre>
> z=[1+/-.1, 2+/-0.2, 3+/-.3]
> genvector(element(z, x), 1, elements(z), 1, x, 1) = [] 
</pre>

Above fails, but when round off elements() return value, it works

<pre>
> genvector(element(z, x), 1, round(elements(z)), 1, x, 1) ≈  [1.00±0.10  2.00±0.20  3.00±0.30]
</pre>

**Comment by hanna-kn** [comment]
Fixed.

**Comment by SubhashBose** [comment]
Thanks, it's fixed too!
