### ISSUE TITLE
Any function(s) to separately get the value and error component of a number?

### ISSUE THREAD

**Issue by SubhashBose** [Qalculate/libqalculate#464]
Suppose I have a number z=5+/-0.2. I want to get its value and error component separately. Something similar we do for complex numbers.
So desired function outputs like:
value(z) = 5
uncertainty(z) = 0.2

Does any method already exist? or can this be implemented?

I am trying to write a function for error-weighted mean (for which I believe there is n function in libqalculate), for this, I need the components separately.

**Comment by hanna-kn** [comment]
I've now added functions lowervalue(), uppervalue(), and midvalue().
Usage:
z = 5+/-0.2
midvalue(z) = 5
uppervalue(z) - midvalue(z) = 0.2

The reason I've not yet added a function that returns the uncertainty value directly is that I couldn't come up with an appropriate name ("uncertainty" is used for the function which sets the uncertainty of a value).

**Comment by SubhashBose** [comment]
Thanks again for adding the functions, this will work. These are great!

Regarding naming, I may suggest these alternatives
1. If I know correctly, qalculate can only deal with symmetric errors. So, lowervalue(), uppervalue() functions are kind of redundant. Maybe instead just name two valuepart() and errorpart() for getting value and uncertainty.
2. or name as getvalue() and geterror()
3. or maybe a single function getvalueerror(), such it would return a 2element vector like  getvalueerror(5+/-0.2) = [5.0 0.2]

**Comment by hanna-kn** [comment]
I've now added errorPart() function, and additional name valuePart() for midpoint() function (was midvalue()).

lowervalue() and uppervalue() (now renamed lowerEndpoint() and upperEndpoint()) makes more sense from an interval perspective. Errors/uncertainties are implemented using intervals, with lower and upper endpoints (but no midpoint) for approximate numbers.

**Comment by SubhashBose** [comment]
Perfect! Thanks.. these names sound more initiative now.

Just getting a compilation error, possibly for those newly added function
<pre>
Calculator.cc: In member function ‘void Calculator::addBuiltinFunctions()’:
Calculator.cc:1635:18: error: expected type-specifier before ‘GetUncertaintyFunction’
 1635 |  addFunction(new GetUncertaintyFunction());
      |                  ^~~~~~~~~~~~~~~~~~~~~~

</pre>

**Comment by hanna-kn** [comment]
> Just getting a compilation error, possibly for those newly added function

I forgot to add BuiltinFunctions.h to the commit.

**Comment by SubhashBose** [comment]
Great! it works now
