### ISSUE TITLE
explain the user where the currency conversion rate comes from

### ISSUE THREAD

**Issue by anarcat** [Qalculate/libqalculate#467]
Hi!

It's really nice that qalculate has that conversion mechanism for all those currencies, great! But I'm often at a loss on how it actually *works*. I *guess* that when I ask for rates related to euros, it talks with the ECB. And from a casual look around the source code, i also found links to https://www.mycurrency.net/=US, is that where the USD rates come from? how about the other rates?

When I use this feature, I often need to justify the results i'm giving to people, say something like: "1.00 Euro = 0.9671121 US Dollars as of now on xe.com"... but with qalculate, i have no idea where that figure comes from...

Could we have that as a comment in the history or something? :)

**Comment by hanna-kn** [comment]
Exchange rates for major currencies (and some minor European currencies, 30 in total) are provided by the data from ECB. These exchange rates are updated daily (but normally retrieved less often by Qalculate). These currencies are always converted to Euro first, before conversion to or from a different currency.

The rest of the exchange rates (except Bitcoin and BYN) are retrieved from https://www.mycurrency.net, with USD as reference currency.

I think it would be too much to display a comment after each currency conversion, but it might be feasible to provide the information the first time an exchange rate source is used.

**Comment by anarcat** [comment]
Yeah, so I guess I don't know exactly where in the UI that could be
pulled from... I totally understand not wanting to crowd that space...

but maybe having a subtle, clickable link would be enough?  Maybe make
the currency icon clickable?

In any case, even with the above explanation, I'm still not entirely
sure whether *my* currency conversion is actually done with ECB or
mycurrency.net... It's the core issue here. There's also custom sources
now (right? #209?) so there's also the possibility the numbers come from
there.

In any case, I really love that feature but not having a source make it
harder to use for me... It's kind of a `{{citation needed}}` on
wikipedia. :)

-- 
I believe that if someone choose arts as their subject but do not
criticize the issues of their society, they have have betrayed
themselves, their conscience, and their society.
                        - Atena Farghadani

**Comment by hanna-kn** [comment]
Exchange rates for the following currencies are available in the ECB data:
USD, JPY, BGN, CZK, DKK, GBP, HUF, PLN, RON, SEK, CHF, ISK, NOK, HRK, TRY, AUD, BRL, CAD, CNY, HKD, IDR, ILS, INR, KRW, MXN, MYR, NZD, PHP, SGD, THB, ZAR, EUR (the base unit for currencies)

All the other currencies (except Bitcoin, BYN, and obsolete European currencies) uses mycurrency.net.

If you convert between two currencies in the ECB data, the first currency is first converted to EUR and then converted to the second currency. If you convert between two currencies using mycurrency.net, the first currency is first converted to USD.

If you convert between a currency which uses mycurrency.net and a currency which uses ECB (with the exception of USD), both data sets are used (with both USD and EUR is used as intermediate currencies).

Custom sources are only used if the user themselves have added them.

It think it would be feasible to add information about data sources used for conversion as a tooltip for the flag in the result in the Qt ("new") UI, and as a tooltip for the information icon (upper right corner of the expression entry) in the GTK ("classic") UI.

**Comment by hanna-kn** [comment]
> It think it would be feasible to add information about data sources used for conversion as a tooltip for the flag in the result in the Qt ("new") UI, and as a tooltip for the information icon (upper right corner of the expression entry) in the GTK ("classic") UI.

This has now been implemented.

**Comment by anarcat** [comment]
this is and you are amazing :)
