### ISSUE TITLE
No way to disable colored output

### ISSUE THREAD

**Issue by en0** [Qalculate/libqalculate#472]
I often use qalc from vim to compute the result of some equation in a document.  I recently installed a updated version of libqalculate and have found that there is no way to disable the colored output. This causes a bunch of garbage in the output.  This goes against the Unix philosophy: Expect the output of every program to become the input to another, as yet unknown, program. Don't clutter output with extraneous information.  Please provide a way to disable colored output. Perhaps in conjunction with the terse output flag.

```
~ » qalc --version
4.3.0
~ » uname -a
Linux xx 5.15.71-1-lts #1 SMP Wed, 28 Sep 2022 10:41:31 +0000 x86_64 GNU/Linux
```

**Comment by hanna-kn** [comment]
Modify the `color` setting (`set color 0`) or use the -c/--color command line option (`qalc -c0`).

By default qalc does not format or colorize the output if not in "interactive" mode.

**Comment by en0** [comment]
Thank you for the suggestion about `-c0`. That has solved my immediate problem. However, I am not observing what you describe using an non-interactive terminal. Based on what you say, this file should not contain any terminal control characters, but it does.  Am i misunderstanding? 

```
~ » echo '3*3' | qalc > output
~ » hexdump -C output
00000000  3e 20 33 2a 33 0a 0a 20  20 1b 5b 30 3b 33 36 6d  |> 3*3..  .[0;36m|
00000010  33 1b 5b 30 6d 20 c3 97  20 1b 5b 30 3b 33 36 6d  |3.[0m .. .[0;36m|
00000020  33 1b 5b 30 6d 20 3d 20  1b 5b 30 3b 33 36 6d 39  |3.[0m = .[0;36m9|
00000030  1b 5b 30 6d 0a 0a 3e 20                           |.[0m..> |
00000038
```

**Comment by hanna-kn** [comment]
> However, I am not observing what you describe using an non-interactive terminal. Based on what you say, this file should not contain any terminal control characters, but it does. Am i misunderstanding?

`echo '3*3' | qalc` colorize output by default, but not `qalc '3*3'` or `echo '3*3' | qalc -f -`.

**Comment by en0** [comment]
I understand. Thank you for taking the time to explain.
