### ISSUE TITLE
[Feature Request]Addition to pressure and flow conversions

### ISSUE THREAD

**Issue by kidimbwi** [Qalculate/libqalculate#473]
as it is currently, Qalculate! can convert to and from: gallons per hour, gallons per minute and litres per second on the flow side and between inch of mercury and millimetre of mercury on the pressure side. would you consider adding: litres per minute, litres per hour and gallons per second to the flow conversions and inch of H₂O and millimetre of H₂O to the pressure conversions ?

Thank you.

**Comment by hanna-kn** [comment]
I've now added millimetre of H₂O and related units.

Qalculate! supports conversion of flow rate using any volume and time units (even if you have to enter the derived unit manually instead of selecting it from a list in the GUI), e.g. `5 gal/s to L/h`, but I've now added some additional derived units for simplicity.

**Comment by kidimbwi** [comment]
Thank you very much for the quick response and additions to Qalculate!.

**Comment by kidimbwi** [comment]
just installed and tested version 4.4 and the conversions are there; no more going online to convert these units on webpages. on the pressure side, i see that meter of water units have been added(mH₂0) can you be able to add millimeters of water(mmH₂0) to the conversions as well ?

Thank you very much for your quick turnaround.

**Comment by hanna-kn** [comment]
> on the pressure side, i see that meter of water units have been added(mH₂0) can you be able to add millimeters of water(mmH₂0) to the conversions as well ?

Oops. mmH₂0 and cmH₂0 where added, but they use the replaced invalid name mH20 to reference the parent unit (making them invalid). As mentioned before conversion is nevertheless possible with any prefix.

If you do not wish to wait for the next version (a simple search and replace of `mH20` with `mWC` in definitions\units.xml (in the folder where Qalculate is installed, e.g. c:\Program Files\Qalculate on Windows) should fix the issue.

**Comment by kidimbwi** [comment]
Nice! i've adjusted the units.xml file and it is now working, Thank you. 

this is a minor request but would it be possible to type in "mmh" and receive the popup suggestions for mmH₂0 among the results. currently, only mmHg is returned. i ask this because, as it is, we have to type in mmWC to get mmH₂0 which may not be clear to a new user who expects to type in mmH₂0/mmh to get the units they want.
