### ISSUE TITLE
Allow atan2 to take in any values with matching units

### ISSUE THREAD

**Issue by AnotherNeko** [Qalculate/libqalculate#478]
**atan2(-1 meter, -1 meter)** should return **atan((1 meter)/(1 meter)) + 180 degrees** which simplifies to **atan (1/1) + 180 degrees** which simplifies further to **(tau/8) radians + 180 degrees** which finally simplifies to **225 degrees** , but instead, atan2 requires all the inputs to be real numbers, which doesn't seem right to me. 
Also, I am looking for a setting to cause all the inverse trigonometric functions to ALWAYS output a number with a unit instead of outputting a unitless number matching the current setting for angle units - here's an example of what Qalculate! (Qt) outputs:

```
atan2(1V, 1V)  "="" atan2(""1"" * ""volt"", ""1"" * ""volt"")"
- Argument 1, Y, in atan2() must be a real number.
- Argument 2, X, in atan2() must be a real number.
= atan2(1 V, 1 V)
```
```
atan(1/1) + 180deg  "="" arctan(""1""/""1"") + (""180"" * ""degree"")"
≈ 180.0000000° + 0.7853981634
```

**Comment by hanna-kn** [comment]
> atan2(-1 meter, -1 meter) should return atan((1 meter)/(1 meter)) + 180 degrees which simplifies to atan (1/1) + 180 degrees which simplifies further to (tau/8) radians + 180 degrees which finally simplifies to 225 degrees , but instead, atan2 requires all the inputs to be real numbers, which doesn't seem right to me.

I do not remember why this choice was made. The arg() function allows any type of argument, e.g. `arg(-1 m + (-1i) m)` (equivalent to `atan2(-1 m, -1 m)`) returns -135 degrees.

> Also, I am looking for a setting to cause all the inverse trigonometric functions to ALWAYS output a number with a unit instead of outputting a unitless number matching the current setting for angle units

Set the default angle unit to "none", using `/set angle 0` (this option has been excluded from the Qt GUI, but the qalc command can be used). This will require use of an explicit angle unit in the argument of trigonometric functions (e.g. `sin(1 rad)`).

**Comment by smm9509** [comment]
I found a function that can replace atan2 but allows arguments to have units:
![image](https://user-images.githubusercontent.com/102259265/205726150-73be1cb3-12a6-48b8-a95a-f61587614775.png)


atan2
−i×ln((\x+i×\y)/(sqrt(\x^2+\y^2)))×radian
I would rename "y" to "rise" and "x" to "run", but I'm not sure how.

**Comment by AnotherNeko** [comment]
I found a function that can replace atan2 but allows arguments to have units:
![image](https://user-images.githubusercontent.com/102259265/205726150-73be1cb3-12a6-48b8-a95a-f61587614775.png)


atan2
−i×ln((\x+i×\y)/(sqrt(\x^2+\y^2)))×radian
I would rename "y" to "rise" and "x" to "run", but I'm not sure how.

**Comment by hanna-kn** [comment]
Support for non-numerical arguments has now been added to atan2().

> I would rename "y" to "rise" and "x" to "run", but I'm not sure how.

Edit argument names in the "Details" tab.
