### ISSUE TITLE
Segmentation fault on nonsensical unit conversions/expressions

### ISSUE THREAD

**Issue by NPN** [Qalculate/libqalculate#48]
Certain combinations of nonsensical unit conversions lead to segmentation faults. These expressions all seem to fall into two categories: `1/(t1+x) to t2` and `y/(t1+z) to y/t2`, where `t1` and `t2` are different units of time, `x` is any non-time unit, and `y` and `z` are any units.

Here are some examples:
```
1/(m+s) to h
cd/(ly+ns) to cd/fortnight
1/(dd+s) to h
1/(m+s) to d
```
However, this pattern doesn't always hold. Here are some examples which follow the patterns I stated above but don't cause segmentation faults:
```
1/(m+ms) to h
cd/(mm+ms) to cd/d
1/(dd+ms) to h
1/(m+ms) to d
```
And here are some more expressions I found in the process of writing this issue that also cause segmentation faults:
```
m/(ly+fs)
cd/(m+ns)
V/(Gh+Gy) to kd
```
For reference, I am using `qalc` from version `2.1.0-1` of `libqalculate` on Arch Linux.

**Comment by hanna-kn** [comment]
Fixed ([patch](https://gist.githubusercontent.com/hanna-kn/7c1edb8bcddd0306e7acfb8e384a84c2/raw/1f2b998524e423079f1ac15d888034bcfb30e4e9/48.patch)).

The simplest segfaulting expression I could find was m/(0,0001 + s). It failed during the formatting phase while transforming the expression to (10000 m)/(1 + 10000 s).
