### ISSUE TITLE
[Feature request or Enhancement] Combing large-numbers with unit conversion

### ISSUE THREAD

**Issue by SubhashBose** [Qalculate/libqalculate#480]
I want conversions like these to work which involve 'large-numbers' like million, billion etc.
`1E15 second to million×year`
or
`1000 BTC to million USD`

but these don't work

I know using prefixes instead like `1000 BTC to megaUSD` would work, but not all large-number have equivalent prefixes. Also, sometimes it is more natural sounding to use large-number like 'million USD' instead of megaUSD.

So, can this be implemented? that large-numbers can be also used along with units and prefixes for conversions.

**Comment by hanna-kn** [comment]
Done. If the conversion expression is not recognized as unit(s) or a single variable, simple division will be tried, e.g. `1E15 s` is divided by `million×year`, and `million×year` appended to the resulting value (if the resulting value does not contain any units).

**Comment by hanna-kn** [comment]
A) is specific for conversion expression where the expression first match against single units and variables and then an expression with only units.

B) is only an issue for very few units and prefixes. Gyr and Myr are the only examples that I'm currently aware of. Myr can be fixed by making MYR (currency) case-sensitive, but Gyr is more problematic. The current algorithm searches for the longest object names from left to right, but does not add the length of any subsequent unit to the length of prefix.

The "limit implicit multiplication" option (`set limimpl` in qalc) can be enabled to avoid matching of sub-swords.

**Comment by hanna-kn** [comment]
`1e15 s to lakh yr` and `1e15 s to Gyr` has now been fixed.

**Comment by SubhashBose** [comment]
'set limimpl' could be a good option, but it seems to only work for inputs, but not working when defining output unit for conversion.
for example, after setting this, '1Wh' won't be an accepted input, but still accepts `20000 J to Wh ≈ 5.55556 W·h`. So, it is not working in my case A too.

A) The existing rule you mentioned should also work as intended for most cases. But here I think by matching expression you mean whole expression, like in my case `lakh yr`, it tries to match full expression against any unit or variable names, which is not there. But instead, if each word (separated by space or operator) is first tried to match with variables and units, then it should be fine, if no match then go for sub-word matching
like `1 lakh yr`, lakh and yr should be tried individually to match single names first.

B) I am still unclear about this behavior, for example `as` is treated `atto-second` (i.e prefix and unit), not as `are second`. This perfect!. But why not same rule apply for Gyr or Myr. prefix should be given higher priority.

Overall I think prefix and single-word names should be given higher priority everywhere before finding implicit combination of units. Becuase,  in confusing cases, user can always force calculator to understand each unit separately by giving space, but reverse can not be done. For example 'lakh' is a matching single-word name (in my setup), but if a user want to mean Litre-are-kilo-hour, then user can explicitly write as `L a kh` to be specific, but if already subwords are matched, then there is no way to make calculator understand it as single-word name.

**Comment by SubhashBose** [comment]
Perfect!! Working as expected.
I tested a few cases and  all works fine.

Thanks .
