### ISSUE TITLE
Weird behavior of genvector()

### ISSUE THREAD

**Issue by SubhashBose** [Qalculate/libqalculate#481]
The 4th argument accepts a number fine, but when I enter a numeric expression (no unit or variables, only numbers in it), then it fails.
```
> genvector(\i,1, 10, 5)    #this works fine

  genvector(i, 1, 10, 5)  = [1  3.25  5.5  7.75  10]

> genvector(\i,1, 10, 10/2)   # but not this

  error: The number of requested elements in generate vector function must be a positive integer.
  genvector(i, 1, 10, 10 / 2) = genvector(i, 1, 10, 5)
```

Am I missing out on something or this is a bug? I didn't notice it before.

Also genvector is not working for negative steps. No error, but doesn't return anything.

```
> genvector(\i, 0, -10, -1,  \i, 1)

  genvector(i, 0, −10, −1, i, 1) = genvector(i, 0, −10, −1, i, 1)
```

**Comment by hanna-kn** [comment]
Fixed.

**Comment by SubhashBose** [comment]
Thanks. This is partly fixed.

When the 4th argument is the number of points, it still has the same issue. Fixed for step size however.
`genvector(\i,1, 10, 10/2)`

**Comment by hanna-kn** [comment]
Fixed.

**Comment by SubhashBose** [comment]
I am reopening this issue as I think this is related to the negative step size.
It seems genvector() goes into an infinite loop when step size is -ve, and the start and end values are equal.

`genvector(\i,5,5,-1,\i,1)`

**Comment by hanna-kn** [comment]
> It seems genvector() goes into an infinite loop when step size is -ve, and the start and end values are equal.

Fixed.
