### ISSUE TITLE
Element-wise operations for inline variable substitution 

### ISSUE THREAD

**Issue by SubhashBose** [Qalculate/libqalculate#487]
What is the correct way of doing element-wise operation for inline substitution of vectors?

Also why this one doesn't work
```
> x.^2 /. x=[1 2 3]

  x^2 = [1  2  3]^2
```

but these two way works
```
> pow(x,2) /. x=[1 2 3]

  pow(x, 2) = [1  4  9]
```
```
> x=[1 2 3]

  warning: A global unit or variable was deactivated. It will be restored after the new variable has been removed.
  save([1  2  3], x, Temporary, , 1) = [1  2  3]

> x.^2

  pow(x, 2) = [1  4  9]
```

Thank you

**Comment by hanna-kn** [comment]
Fixed.

`x.^2` was parsed as `x^2`, before variable substitution because x (without variable substitution) is a scalar. I think the primary reason for this behaviour was that some element-wise functions initially did not support scalars as (first) argument.

**Comment by SubhashBose** [comment]
Great! Thanks for the fix.
