### ISSUE TITLE
dont use heavy minus for cli

### ISSUE THREAD

**Issue by bgkillas** [Qalculate/libqalculate#488]
heavy minus makes parsing text so much worse why is this a thing
like /usr/bin/qalc -t "-2"|sed 's/-//' does not work because it translates - to − for a monospace font this looks identical

**Comment by hanna-kn** [comment]
Use the "u8" command line option, e.g. `/usr/bin/qalc -t +u8 "-2"|sed 's/-//'` (or change the Unicode setting).
For many monospace fonts (e.g. Liberation Mono, Ubuntu Mono, Noto Sans Mono, Hack) there is a clear visual difference.
