### ISSUE TITLE
gnuplot x11 cant display heavy minus sign and +u8 does not help

### ISSUE THREAD

**Issue by bgkillas** [Qalculate/libqalculate#492]
gnuplot in x11 mode top right legend gets messed up with any minus sign, it seems to to do with heavy minus sign being still in the legend even with +u8
![image](https://user-images.githubusercontent.com/55570525/204926121-14a6fe88-1b00-48eb-8b62-63c6f048c375.png)

**Comment by hanna-kn** [comment]
Fixed. 
The setting affecting plot output setting was not updated when the `u8` command line option was used (the correct sign was used with `-s "unicode 0"` or `set unicode 0`).
