### ISSUE TITLE
Variable can't check equality

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#497]
I can check equality between two numbers.
> 1=2

  (1 = 2) = false

But variable can't check equality.
> var:=1

  save(1, var) = 1

> var=2 

  save(2, var, Temporary, , 1) = 2

**Comment by hanna-kn** [comment]
It was deemed more useful to allow simple variable assignment instead. This does not interfere with usage in subexpressions (e.g. in `if` function) or solving of equations. You can still check equality by slightly modifying the expression, e.g. `(var=2)` or `+var=2`.
