### ISSUE TITLE
Question: How to obtain the most recent calculated value?

### ISSUE THREAD

**Issue by fjdemos** [Qalculate/libqalculate#502]
As the question says, how do I quickly obtain the most recent calculated value without saving it in a variable?

For example,

1. 5 + 5 (output is 10)
2. <what_should_i_write_here_to_obtain_the_previous_output_without_saving_to_a_variable> * 2 (output should be 10 * 2 = 20)

I know I can do this:
1. save(5 + 5, my_output)
2. my_output * 2

Is it possible to get the most recent output without saving it to a variable?

**Comment by hanna-kn** [comment]
Use the `ans` (short for `answer`) variable. There are also `ans2`, `ans3`, `ans4`, and `ans5` variables which contains the second, third, fourth, and fifth last result. The values of these variables are included in the list shown using the command `list`.

The GUIs in addition provides the answer() function (most easily used by clicking an index in the history list) for fixed references.

Also note that there are more convenient options for saving variables, e.g. `my_output=5+5`, `my_output:=5+5`, or the `store`/`save` command (saves the most recent value).

**Comment by fjdemos** [comment]
Perfect, exactly the answer I was looking for. Thank you!
