### ISSUE TITLE
Qt6?

### ISSUE THREAD

**Issue by ManuelSchneid3r** [Qalculate/libqalculate#508]
Are there any reasons not to go with qt6? Otherwise I'd ask you to move on. Its not that bad. I recently ported albertlauncher to it. Its feasible.

**Comment by hanna-kn** [comment]
qalculate-qt can be compiled against both Qt5 and Qt6. The Windows packages use Qt6. The GNU/Linux flatpak and snap packages use Qt5, while packages for Arch Linux and Manjaro are compiled against Qt6. Personally I prefer Qt5 on GNU/Linux, because of better desktop integration.

**Comment by ManuelSchneid3r** [comment]
On MacOS with homebrew it also comes with qt6. Good to know. Thank you
