### ISSUE TITLE
Strange behaviour when doing unit conversion inside of nounit() function

### ISSUE THREAD

**Issue by aa-ko** [Qalculate/libqalculate#509]
Hi!

I noticed some strange behaviour of the _nounit()_ function when performing unit conversion.

For reference, here are some examples where _nounit()_ behaves as expected:
```
nounit(12 second) # 12

nounit(12 second × 12) # 144

nounit(12 minute × 12) −> second # 144 s
```
In each case, the calculation is performed on the expression inside the function and **then** the unit is removed completely.
Converting a plain number result back to a unit (in this case to seconds) just appends the given unit.

However, if the unit conversion is done **within the braces of the _nounit()_ function**, the result does no longer make sense.
Consider the following example, which is just a slight variation of the third example given above:
```
nounit((12 minute × 12) −> second) # 144 s
```

Pulling the unit conversion inside the braces does not change the result.
I would expect the multiplication to yield `144 minutes`, which would then be converted to `8640 seconds` and yielding the final result `8640` after stripping the unit.

Maybe my assumptions are wrong, but this certainly does not look correct to me.
Please let me know if this is indeed a bug or if I just misunderstood something here.

All of this was done using Qalculate 4.5.1 on Windows 10.

**Comment by hanna-kn** [comment]
Unit conversion is not supported within an expression (e.g. in a function). It can only be applied to the whole expression. `nounit((12 minute × 12) −> second)` is interpreted as `nounit((12 minute × 12)) −> (second)`.

Also notice that nounit() removes all units before any conversion `nounit(12 min × 12 s) = 12 × 12 = 144`.

**Comment by aa-ko** [comment]
Thanks for the quick reply!
Glad to hear that this is indeed intended.

Are there any plans to change _nounit()_ in the future to support fine-grained stripping of units?
Even though this is no bug, I'd still consider this behaviour to be kind of unintuitive.

In any case, feel free to leave this issue open for future reference.

**Comment by hanna-kn** [comment]
nounit() was primarily created for internal use.
`nounit((12 minute × 12) −> second)` can be replaced with `(12 minute × 12) / second`.
Conversion within the function for expressions similar to `nounit(12 min × 12 s)` would be result in less predictable calculations (especially in cases where the relation between the units is less obvious, where none of the units is a SI base unit, or for units which lack a standard base unit).

**Comment by aa-ko** [comment]
Alright, that makes sense.

I replaced my unit conversion + _nounit()_ construct with division by the base unit and that works perfectly fine in all cases!
