### ISSUE TITLE
[RFE] Please add the sinc() function

### ISSUE THREAD

**Issue by genodeftest** [Qalculate/libqalculate#51]
The `sinc(x)` function (sometimes abbreviated as `si(x)` function) is defined as follows:
* `sinc(0) = 1`
* `sinc(x) = sin(x)/x` ∀ x≠0

This would be a nice function to be added to libqalculate/Qalculate.

I thought adding this code to category "Trigonometry" in [data/functions.xml.in:1195](https://github.com/Qalculate/libqalculate/blob/master/data/functions.xml.in#L1195) would be enough:
```
<function>
	<_title>unnormalized sinc function</_title>
	<_names>r:sinc,r:si</_names>
	<expression>if(\x = 0,1,sin(\x))</expression>
</function>
```
and it works, so I'll add it in a pull request.

Additional info:
This change is backwards-incompatible. I don't know whether you care about that. Currently, running `$ qalc "sinc(pi/2)"` will interpret this as `sin((speed_of_light * (pi / 2)) * radian)` and `$ qalc "si(pi/2)"` will interpret as `second * i * (pi / 2)`.

PS: Thank you for this useful application/library!

**Comment by hanna-kn** [comment]
I see no issues with your definition, and I do not care about backwards-compatibility for such confusing expressions. I think however that it might be better to add the function to the library c++-code,  to allow differentiation and integration (the if() function is problematic in this regard).

**Comment by genodeftest** [comment]
I'm not used to C++ programming so I won't implement that feature any time soon. I've closed my pull request in favour of any better implementation as proposed by you.

**Comment by hanna-kn** [comment]
Done.

I did not expect you to implement it yourself. It is easy to do and just takes a few minutes, but only if you are familiar with the libqalculate code.
