### ISSUE TITLE
"=" operator can't assign value to variable when same variable on right hand side

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#513]
> x=1           

  save(1, x, Temporary, , 1) = 1

> x=x+1

  (x = (x + 1)) = false

BTW, what is the difference between "":=" and "="? Is there some example?

**Comment by hanna-kn** [comment]
Some variable assignments using `=` is disabled to avoid conflict with equation solving primarily. To avoid this, `=:` can be used instead.

`:=` will store the expression, without any calculation. The difference will primarily be noticeable for approximate values.
```
> x=sin(5)

  save(sin(5 radians), x, Temporary, , 1) ≈ −0.9589242747

> x/sin(5)

  x / sin(5 radians) ≈ 1.000000000

> x:=sin(5)

  save(sin(5 radians), x) ≈ −0.9589242747

> x/sin(5)

  x / sin(5 radians) = 1
```

**Comment by howaboutuser** [comment]
When should I use "=" instead of ":="? It must be meaningful to have two save operators.

I think a more precise example which distinguish "=" from ":="  is better than "var1=ln(5)+2" in man page. Besides, listing some condition which "=" work as save operator instead of comparison operator will be great.
