### ISSUE TITLE
Inconsistent use of minus and hyphen-minus glyphs in output may cause frustration

### ISSUE THREAD

**Issue by r-terrett** [Qalculate/libqalculate#514]
# Description of problem:

*I'll preface this by saying that I have not been using Qalc for long and so am not intimately familiar with its configuration.*

In command line output, Qalc denotes negative numbers using a leading minus glyph (Unicode U+2212), and negative exponents using an infix hyphen-minus glyph (Unicode U+002D). Whilst the use of a minus glyph is typographically correct, there exist two related issues:

1. Inconsistent use of glyphs in output containing a negative number with a negative exponent is typographically unsound.
2. Copying and pasting such output into other programs may lead to undesirable behaviour. Concretely, Python will not interpret such output as a number due to the presence of the leading minus glyph. In the case of pasting this output into a CSV file which was read by Pandas, the number was interpreted as a string, whilst in the case of variable assignment, a syntax error was raised due to the presence of the minus sign, which is considered an invalid character in float literals. Similar problems are likely to be found in other programs and programming languages attempting to interpret Qalc output. When using fixed-width fonts (for instance, in a terminal) the two glyphs may be visually indistinguishable, exacerbating the confusion.

# To reproduce:

1. `qalc -1.234E-56`
2. Obtain output −1.234E-56
3. Note that the leading minus sign is U+2212, whilst the exponent 'minus sign' is a hyphen (U+002D).
4. Optional: inside a Python REPL, attempt to assign copy-pasted Qalc output to a variable, *e.g.* `a = −1.234E-56`. Note that this raises a `SyntaxError`.

# Suggested mitigations:

1. Harmonise leading and exponent negative signs in output.
2. Implement a command line switch or rc option (?) which selects the desired negative sign glyph to use.

# Platform details:

Qalc 4.5.1 on Arch Linux

# Notes:

I don't know what the behaviour is like in the GUI application as I don't use it.

**Comment by hanna-kn** [comment]
If I remember correctly, I decided not to use Unicode minus for scientific E notation in order to reduce the visual distance between the E and the exponent to reduce potential confusion particularly when lower case e is used.

> Implement a command line switch or rc option (?) which selects the desired negative sign glyph to use.

There is a command line switch (`+u8`) and an option (`set unicode off` command when launched without an expression, or using the `-s, -set "OPTION VALUE"` command line switch) to disable (or enable) Unicode characters.

**Comment by hanna-kn** [comment]
I've now fixes the inconsistent use of minus.

**Comment by r-terrett** [comment]
Your patch combined with the unicode switch that I did not notice more or less solve this issue, thank you.
