### ISSUE TITLE
Cross product and dot product should output different units

### ISSUE THREAD

**Issue by AnotherNeko** [Qalculate/libqalculate#515]
[reference discussion on units](https://physics.stackexchange.com/a/37882)
When Newtons and meters are cross multiplied, the product is a moment measured in Nm, but Qalc simplifies this to J (wrong). The formula for energy (J) requires a dot product, not a cross product.

Example:
```
cross([(0 m) (−175 mm) (0 m)] , [(75 N) (0 N) (0 N)])
--
= [(0 J)  (0 J)  (13.125 J)]


dot([10N, 5N, 0N], [0cm, 80cm, 0cm])
--
= 4 J
```

for the cross product, the units should be Nm not J

**Comment by AnotherNeko** [comment]
I'm not super familiar with cross products, I just got the idea that maybe:
> all cross products should have units of rad^-1

**Comment by hanna-kn** [comment]
Qalculate does not know that you are calculating the moment of force. A generic cross product (the cross product is used in multiple other context) is calculated, which results in a vector with the unit g·m²/s². If automatic unit conversion is enabled, units in the result are, with few exceptions, converted to the unit with the least of amount of subunits. This does not always match the users intentions, in which case explicit unit conversion should be used (e.g. `cross((0 m, −175 mm, 0 m), (75 N, 0 N, 0 N)) to Nm`).

I've now added a special case which prefers Nm when the result is a vector with three components.

**Comment by AnotherNeko** [comment]
> all cross products should have units of rad^-1

I've been thinking about this issue a bit more recently (not enough to warrant re-opening it) as I continue to use `qalc.exe`...

I think it comes down to the units/dimensions system not being detailed enough to consider whether a product has an energy component or a torque component. One way to think about torque is that rotating by one radian with or against a torque requires that amount of energy. So with that interpretation, torque should have an angle unit in the denominator (but it's commonly omitted because angles are dimensionless).

Another way to interpret the issue is that the type of a product is not well defined. We use the dimensions of the matrix (e.g. a 1x3 matrix being a vector3) to encode whether the product is a scalar product or a vector product. However, if I am using a Nx3 matrix to describe the energetic state of three thermal systems, and I take a row from that matrix, suddenly my list of 3 energies of three different systems resembles a 1x3 matrix which we classify as a vector3 and treat it as a torque. That doesn't make sense but it happened. 

So I feel like there should be a way to tag the cross product as a torque (possibly by putting radians in the denominator) or as not a torque, that carries across systems with a varying number of dimensions and doesn't pop up unexpectedly.

This is kind of a vent of my frustrations with this conundrum as well as deliberations on how to solve it.
