### ISSUE TITLE
rref function doesn't accept units

### ISSUE THREAD

**Issue by AnotherNeko** [Qalculate/libqalculate#521]
Actual result when using qalc:
```
> Maugmented := [[ 1, 2, 3 ];[ 4, 5, 6 ]]

  save([[1, 2, 3], [4, 5, 6]], Maugmented) = [[1, 2, 3], [4, 5, 6]]

> rref(Maugmented)

  rref(Maugmented) = [[1, 0, −1], [0, 1, 2]]

> Maugmented := [[ 1m, 2m, 3m ];[ 4m, 5m, 6m ]]

  save([[1 × meter, 2 × meter, 3 × meter], [4 × meter, 5 × meter, 6 × meter]], Maugmented) =
  [[1 m, 2 m, 3 m], [4 m, 5 m, 6 m]]

> rref(Maugmented)

  rref(Maugmented) = rref([[1 m, 2 m, 3 m], [4 m, 5 m, 6 m]])

```
expected result of rref with units:
(solving by hand):
[1 m, 2 m, 3 m]
[4 m, 5 m, 6 m]
row 1 := row1 * 4
[4 m, 8 m, 12 m]
[4 m, 5 m,   6 m]
row 1 := row1 - row2
[0 m, 3 m, 6 m]
[4 m, 5 m, 6 m]
swap
[4 m, 5 m, 6 m]
[0 m, 3 m, 6 m]
row 2 := row 2 / 3m
[4 m, 5 m, 6 m]
[0    ,  1    ,  2    ]
row 1 :=  row 1 / 1m
[ 4, 5, 6 ]
[ 0, 1, 2 ]
row 1 := row 1 - 5*row2
[ 4, 0, -4]
[ 0, 1, 2 ]
row 1 := row 1 / 4
[ 1, 0, -1]
[ 0, 1, 2 ]
the result should be the same as with no units, but conversions may be necessary if the units do not match.

**Comment by hanna-kn** [comment]
Fixed (units will be divided out before further calculations).

**Comment by AnotherNeko** [comment]
The fix looks incomplete. 
When I add a row of zeros to the bottom of the augmented matrix (this is normal in my practice), it performs the Gaussian Elimination as expected. However, when the last column is made from a column vector with units (with all values in the third dimension equal to zero), it seems unable to evaluate the function. 
The way I understand it mathematically (and [a Quora discussion to support my opinion](https://www.quora.com/In-science-does-0-need-units) ): This failure makes sense with units that aren't centered on zero (e.g. 0 oC is not at all equivalent to 0, unless it represents a change or difference in temperature). But with distances and forces like m and N, these values always represent a change in position or a net force, so it would make sense to have 0N = 0 .
```
> Maugmented := [[ 1, 2, 3N ];[ 4, 5, 6N ]]  

  save([1  2  (3 newtons); 4  5  (6 newtons)], Maugmented) =

  1  2  (3 N)

  4  5  (6 N)

> rref(Maugmented) 

  rref(Maugmented) =

  1  0  (−1 N)

  0  1   (2 N)

> Maugmented := [[ 1, 2, 3N ];[ 4, 5, 6N ];[ 0, 0, 0 ]]  

  save([1  2  (3 newtons); 4  5  (6 newtons); 0  0  0], Maugmented) =

  1  2  (3 N)

  4  5  (6 N)

  0  0      0

> rref(Maugmented) 

  rref(Maugmented) =

  1  0  (−1 N)

  0  1   (2 N)

  0  0       0

> Maugmented := [[ 1, 2, 3N ];[ 4, 5, 6N ];[ 0, 0, 0N ]]  

  save([1  2  (3 newtons); 4  5  (6 newtons); 0  0  (0 newton)], Maugmented) =

  1  2  (3 N)

  4  5  (6 N)

  0  0  (0 N)

> rref(Maugmented) 

  rref(Maugmented) = rref([1  2  (3 N); 4  5  (6 N); 0  0  (0 N)])

```
