### ISSUE TITLE
libqalculate: "1 m to cm" works but "9 to hex" does not

### ISSUE THREAD

**Issue by probonopd** [Qalculate/libqalculate#522]
In helloSystem's [Menu](https://github.com/helloSystem/Menu/), we are starting to use libqalculate. "1 m to cm" works but "9 to hex" does not, whereas it does work in `qalc` on the command line.

Are we doing it wrong?

```
    MenuQCalc() : Calculator()
    {
        eo.auto_post_conversion = POST_CONVERSION_BEST;
        eo.structuring = STRUCTURING_SIMPLIFY;
        eo.parse_options.angle_unit = static_cast<AngleUnit>(ANGLE_UNIT_DEGREES);
        eo.parse_options.functions_enabled = true;
        eo.parse_options.limit_implicit_multiplication = true;
        eo.parse_options.parsing_mode = static_cast<ParsingMode>(PARSING_MODE_CONVENTIONAL);
        eo.parse_options.units_enabled = true;
        eo.parse_options.unknowns_enabled = false;
        po.indicate_infinite_series = true;
        po.interval_display = INTERVAL_DISPLAY_SIGNIFICANT_DIGITS;
        po.lower_case_e = true;
        po.use_unicode_signs = true;
        // Enable unit conversion using the "to" keyword
        // so that "1 m to cm" works
        po.use_unit_prefixes = true;
        po.use_prefixes_for_currencies = true;
        po.use_prefixes_for_all_units = true;
        loadGlobalDefinitions();
        loadLocalDefinitions();
        loadGlobalCurrencies();
        loadGlobalUnits();
        loadGlobalVariables();
        loadGlobalFunctions();
        loadGlobalPrefixes();
        // Now "1 m to cm" works but "9 to hex" does not
    }
```

Thanks for any hints. Is there a way to make libqalculate return the same results as `qalc` does on the command line?

**Comment by hanna-kn** [comment]
`to hex` affects the output of the result (the `PrintOptions` passed to `MathStructure::print()`) and requires use of [`Calculator::calculateAndPrint()`](https://qalculate.github.io/reference/classCalculator.html#a0b73aa4f90347f17b842625069aa534b) (as in the [gnome search provider](https://github.com/Qalculate/qalculate-gtk/blob/master/src/searchprovider.cc)), or separate handling of non-unit conversion as in qalc.

**Comment by probonopd** [comment]
Thanks @hanna-kn.

Is there a way to call `libqalculate` so that what the user gets back is the same as what the user gets back from `qalc`, without having to basically copy/recreate the `qalc` code?
