### ISSUE TITLE
multiplicative inverse FPE when number not coprime to modulus

### ISSUE THREAD

**Issue by awuctl** [Qalculate/libqalculate#523]
When finding the multiplicative inverse mod N of a number where the inverse is undefined (number is not in the multiplicative group of integers mod N), libqalculate crashes with a floating point exception.
This will kill any programs using libqalculate that don't handle FPEs (most notably qalc, qalculate-gtk).
It should probably just return `undefined` instead.

```zsh
% qalc '2^-1 %% 10'
zsh: floating point exception (core dumped)  qalc '2^-1 %% 10'
```

Here's the stack trace from the coredump of the above (gmp raises divide by zero as documented for `__gmpz_powm`):
```
Stack trace of thread 167017:
#0  0x00007f10f3ca08ec n/a (libc.so.6 + 0x878ec)
#1  0x00007f10f3c51ea8 raise (libc.so.6 + 0x38ea8)
#2  0x00007f10f622cb5e __gmp_exception (libgmp.so.10 + 0x11b5e)
#3  0x00007f10f622cba5 __gmp_divide_by_zero (libgmp.so.10 + 0x11ba5)
#4  0x00007f10f624637e __gmpz_powm (libgmp.so.10 + 0x2b37e)
#5  0x00007f10f6884add n/a (/tmp/qalc/libqalculate/libqalculate/.libs/libqalculate.so.22.18.0 + 0x2f9add)
ELF object binary architecture: AMD x86-64
```

**Comment by awuctl** [comment]
https://github.com/Qalculate/libqalculate/commit/485e558c79d966a4ba7039b2491d32ff41aa2f0a it'd be nice to still have the option to find modular inverses though (or at least have a separate function for it, if not with plain mod).
to keep the previous notation a simple GCD check would suffice (sadly I don't know the code enough to write that myself for now)

**Comment by hanna-kn** [comment]
Unfortunately the return of the modular inverse for the modulo operation/function was unintended and inconsistent. I've now added a new function, `powmod()`,  which can find the modular inverse (but not yet modular roots).
