### ISSUE TITLE
Value variable and element variable are opposite in csum help message

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#526]
> help csum

Function: Custom Sum of Elements

csum(First element, Last element, Initial value, Function, Value variable, Element variable, Vector[,
Index variable][, Vector variable])

>csum(1,-1,0,'y'+2*'x','x','y',[1,2])  

  csum(1, −1, 0, y + (2 × x), x, y, [1  2]) = 6

x is element variable and y is value variable in this example.

**Comment by hanna-kn** [comment]
Fixed.
