### ISSUE TITLE
Repeated qalculate-searc errors as a possible cause for Manjaro Gnome freezing and logging off.

### ISSUE THREAD

**Issue by Developer-42** [Qalculate/libqalculate#529]
My Manjaro Gnome system froze and logged off when I pasted some longer text into the search bar (the one that you can access with the Windows key). I assume that it included a special sign that could not be displayed correctly, because I saw a white symbol at the end that was not a character. I don't know if this happened because of "qalculate-searc", but there are definitely a lot of "qalculate-searc" errors that happened over the day. The latest are uploaded in the file [logs.txt](https://github.com/Qalculate/libqalculate/files/11162373/logs.txt). I installed both libqalculate and qalculate-gtk version 4.6.0-1 with pamac from extra repo.
[inxi-b.txt](https://github.com/Qalculate/libqalculate/files/11162428/inxi-b.txt)

**Comment by hanna-kn** [comment]
The repeated qalculate-search-provider errors are likely not the cause for the freeze and log off. See https://github.com/Qalculate/qalculate-gtk/issues/473 and  https://github.com/Qalculate/qalculate-gtk/issues/472.

Even if the the errors are not related, it is still possible that the qalculate-search-provider is somehow causing the freeze and logg of.

**Comment by Developer-42** [comment]
@hanna-kn Since the fix has been committed 3 days ago, how is the procedure for updating? I could compile it from source, but shouldn't there be a newly released version? I installed qalculate-gtk from extra using pamac on Manjaro.

**Comment by hanna-kn** [comment]
> Since the fix has been committed 3 days ago, how is the procedure for updating? I could compile it from source, but shouldn't there be a newly released version?

I will release on new version next Monday (2023-04-17).
