### ISSUE TITLE
Numerical Display: incomplete approximation for scalar ./ vector

### ISSUE THREAD

**Issue by etterli** [Qalculate/libqalculate#532]
Hi there! Important things first, thanks for creating and maintaining such a lovely calculator tool! While using it I found a strange behavior which I don't know how to solve / work around.

### Problem
When I perform a elementwise division of a scalar and a vector the behavior is not as I would expect it.

I expect an elementwise division to give the following results:
```
> [8; 4.5] ./ 4

  divide([8; 4.5], 4) =

      2

  1.125
```
This works properly. However, if I switch around the position of the elementwise division I would expect the same output in regards to the format. But what I get is:
```
> 4 ./ [8; 4.5]

  4 / [8; 4.5] = 4 / [8; 4.5]
```
I would expect the output to be the vector `[0.5; 0.888888]` (either in [  ] format or like the working example is fine)

This probably has to do something with the settings in section "Numerical display".  But I wasn't able to figure out the correct settings. 

Can someone guide me in the correct direction?

### Qalc information:
Version 4.6.0, reproduced with CLI and GUI (the "new" version), Windows 11, 64bit

### Background
I'm using vectors to pass multiple values of a variable in a physical formula, to quickly calculate something for different materials.
Yes, I'm aware that for this purpose functions are probably the way to go. However, I don't want to define each time a function for very simple formulas. And "inverting" a vector also commonly occurs in vector calculations...

### Qalc in VS Code
I installed the VS Code extension Qalc (Extension ID: [nortakales.vs-qalc](https://github.com/nortakales/vs-code-qalc)) and tested the same example there. With this extension the output is as I would expect it. Therefore, I suppose it definitely has something to do with the settings. But I wasn't able to match the extension's setting "Notation (`qalc.output.notation`" to one described in the Qalc man pages. The extension setting is set to the default value "fixed". This setting somehow directly affects the Math.js settings.

**Comment by hanna-kn** [comment]
This is a bug, which has now been fixed.

I'm not familiar with the VS Code extension. It does not seem to use libqalculate and the name is therefore a bit unfortunate.

**Comment by etterli** [comment]
Thank you!
