### ISSUE TITLE
[Feature request] Need function to enter complex number in polar format...

### ISSUE THREAD

**Issue by manuvarkey** [Qalculate/libqalculate#533]
This is a widely used function in electrical engineering applications when dealing with phasors. Has a dedicated key in Casio 991 series calculators!.

![Casio image](https://user-images.githubusercontent.com/4415312/231689879-d62ca120-a53b-43d8-b37b-e3f97d8cc8b6.jpg)

**Comment by hanna-kn** [comment]
Qalculate supports the ∠ symbol. This can be input in the GUI:s using Ctrl+Shift+A, right-click on the *i* button (qalculate-qt), or using the menu of the *i* button (qalculate-gtk), but I understand that it's more problematic if using the CLI (qalc). Alternatively the `cis` function can be used (`a*cis(b)` is equivalent to `a∠b`).

**Comment by manuvarkey** [comment]
@hanna-kn That is great. Thanks.

**Comment by manuvarkey** [comment]
![Screenshot from 2023-04-13 16-48-00](https://user-images.githubusercontent.com/4415312/231745906-b3893d80-0bf9-4c1d-9413-c7195d22b78c.png)
![Screenshot from 2023-04-13 16-48-10](https://user-images.githubusercontent.com/4415312/231745917-f29af01c-b5ce-42a7-98dd-05c3d60dce87.png)
![Screenshot from 2023-04-13 16-48-17](https://user-images.githubusercontent.com/4415312/231745921-1538890a-766c-4a67-94df-c2b98c1643f6.png)

Is this behavior expected ? ∠function seems to correctly account for unit preference.

**Comment by hanna-kn** [comment]
> Is this behavior expected?

Yes, cis() always assumes radians if no unit is used (cis(x) is calculated as e^(i*x)).

**Comment by manuvarkey** [comment]
@hanna-kn Thanks for the clarification.
