### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by weiweiwei9811** [Qalculate/libqalculate#539]
in libqalculate/Calculator-definitions.cc:1717, the return of xmlGetProp() is not freed, this could cause memory leak.

**Comment by hanna-kn** [comment]
Fixed (xmlGetProp() replaced with xmlHasProp()).

Note that this memory leak could only potentially occur when loading a data file saved with version < 0.6.3 (almost twenty years old), but it should not normally occur even in this unlikely case.
