### ISSUE TITLE
Bug parsing simple expression ("-" is not a valid variable/function/unit)

### ISSUE THREAD

**Issue by aib** [Qalculate/libqalculate#54]
I came across a weird bug while using Qalculate! GTK. Entering the formula

`(x-"y")^2 + 2*x*1`

yields "2x" because the (x-"y") expression is interpreted as (x * (0 * y)). Note that copy/pasting it does not work, as unicode characters need to be used, more on that on following comments. You can use the expression below for pasting:

`(x−"y")^2 + 2⋅x⋅1`

**Comment by aib** [comment]
The bug seems to manifest only when both the subtraction and the multiplication operators are unicode. Here is a test case against the latest version:

`$ cat myinput 
(x-"y")^2 + 2*x*1
(x−"y")^2 + 2*x*1
(x-"y")^2 + 2⋅x⋅1
(x−"y")^2 + 2⋅x⋅1
(x-"y")^2 + 2⋅x
(x−"y")^2 + 2⋅x
$ ./qalc < myinput
I/O warning : failed to load external entity "/usr/local/share/qalculate/prefixes.xml"
I/O warning : failed to load external entity "/usr/local/share/qalculate/currencies.xml"
I/O warning : failed to load external entity "/usr/local/share/qalculate/units.xml"
I/O warning : failed to load external entity "/usr/local/share/qalculate/functions.xml"
I/O warning : failed to load external entity "/usr/local/share/qalculate/datasets.xml"
I/O warning : failed to load external entity "/usr/local/share/qalculate/variables.xml"
Failed to load global definitions!
> (x-"y")^2 + 2*x*1

  ((x - "y")^2) + (2 * x * 1) = x^2 + 2x - 2x "y" + "y"^2

> (x−"y")^2 + 2*x*1

  ((x - "y")^2) + (2 * x * 1) = x^2 + 2x - 2x "y" + "y"^2

> (x-"y")^2 + 2⋅x⋅1

  ((x - "y")^2) + (2 * x * 1) = x^2 + 2x - 2x "y" + "y"^2

> (x−"y")^2 + 2⋅x⋅1

  error: "−" is not a valid variable/function/unit.
  ((x * (0 * "y"))^2) + (2 * x * 1) = 2x

> (x-"y")^2 + 2⋅x

  ((x - "y")^2) + (2 * x) = x^2 + 2x - 2x "y" + "y"^2

> (x−"y")^2 + 2⋅x

  ((x - "y")^2) + (2 * x) = x^2 + 2x - 2x "y" + "y"^2

> %                                                                                `

**Comment by hanna-kn** [comment]
Fixed.
