### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by ghost** [Qalculate/libqalculate#544]
Version: 4.6.1

Launching `qalc 0 / 0` returns `0 / 0 = 0/0`, which COULD be fine to me. But `qalc 2 / 0` returns `2 / 0 = 1/0` which is really strange and `qalc 0/0=0` gives `((0 / 0) = 0) = true`, which is totally wrong.

Am I missing something or there's no `DivisionByZero` exception?

**Comment by hanna-kn** [comment]
Fixed. `2 / 0 = 1/0` was an formatted output anomaly, `((0 / 0) = 0) = true` was the result of an assumption (applied to freely in some cases) that zero multiply by anything (including 0^-1 and other values considered undefined or infinite) was zero.
