### ISSUE TITLE
Feature request: Tensor product

### ISSUE THREAD

**Issue by RobertSchuh** [Qalculate/libqalculate#553]
I would like to calculate the tensor/kronecker products of matrices: https://en.wikipedia.org/wiki/Kronecker_product

Furthermore, built-in shortcuts for Pauli matrices could be useful, with another shortcut for the 2x2 identity as 0th Pauli matrix.

Example: 
px kx pz = kron(Pauli X, Pauli Z) = [[0, 0, 1, 0], [0, 0, 0, -1], [1, 0, 0, 0], [0, -1, 0, 0]].

**Comment by hanna-kn** [comment]
Done (Kronecker product has been added as kron() function, and Pauli matrices as pauli<sub>0</sub>, pauli<sub>1</sub>, ... and σ<sub>0</sub>, σ<sub>1</sub>, ...).

**Comment by RobertSchuh** [comment]
awesome!
