### ISSUE TITLE
"where" can't replace variables that are stored in variable

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#556]
I want to store result to result variable then use "where" to replace the variables in result variable. But "where" can't replace variables that are stored in variable.
> result="var1"+"var2"       

  save(var1 + var2, result, Temporary, , 1) = var1 + var2

> result where "var1"=1 and "var2"=2

  warning: Original value ("var1") was not found.
  warning: Original value ("var2") was not found.
  result = var1 + var2

But "where" is work on ans.
> ans where "var1"=1 and "var2"=2

  ans = 3

**Comment by hanna-kn** [comment]
Fixed.
