### ISSUE TITLE
Feature request: support for microchip 24/32-bit fp format

### ISSUE THREAD

**Issue by permaBox** [Qalculate/libqalculate#558]
The Microchip fp format is a little bit different from IEEE 754 and often used for embedded controller SW.
The format definition, procedures from/to IEEE 754 as well as examples are described in application note AN575 by Microchip.
I would like to see it similar as the x86 extended fp format under file/fp conversion.

https://www.microchip.com/en-us/application-notes/an575

**Comment by hanna-kn** [comment]
How does the Microchip 32-bit format differ from IEEE 754?
Custom number of bits in mantissa and exponent can be specified when using the floating point functions (e.g. 'float()' and `floatBits()`).

**Comment by permaBox** [comment]
The fp formats are:
                              eb             f0               f1              f2
IEEE754 32-bit       **s**xxx xxxx   **y**xxx xxxx   xxxx xxxx   xxxx xxxx
Microchip 32-bit   xxxx xxxx   **s**xxx xxxx   xxxx xxxx   xxxx xxxx
Microchip 24-bit   xxxx xxxx   **s**xxx xxxx   xxxx xxxx

Notes (see page 3 of https://www.microchip.com/en-us/application-notes/an575):
s: sign bit, y: LSb of eb
eb: exponent, f0-f2: fraction with f0 msb and implicit MSb=1
IEEE 754 places sign bit of eb with the LSb of the exponent as the MSb of f0

**Comment by hanna-kn** [comment]
If, as it initially seems, the only difference is the position of the sign bit, this would be very easy to support.

**Comment by hanna-kn** [comment]
Done.
