### ISSUE TITLE
segmentation fault when running extremum(cot(x),x)

### ISSUE THREAD

**Issue by Jaulers** [Qalculate/libqalculate#56]
when running
`extremum(cot(x),x)`
in qalc, it crashes with a segfault.

**Comment by Jaulers** [comment]
...which is interpreted as `solve(diff(1/tan(x),x) == 0,x)` which still generates a segfault,
but when substituting `diff(1/tan(x),x)` with its output `-1 -1/tan(x rad)^2`, no segfault is generated.

**Comment by hanna-kn** [comment]
Fixed.
