### ISSUE TITLE
rod not exactly 16.5 ft

### ISSUE THREAD

**Issue by cousteaulecommandant** [Qalculate/libqalculate#560]
Shouldn't 1 rod be exactly 16.5 ft, not 16.5 US_ft?
According to https://en.wikipedia.org/wiki/Rod_(unit), 1 rod is defined as 16½ feet, and is exactly 5.0292 m; however, Qalculate and qalc show it as 1 rod = 16.5 US_ft = approx. 16.50003300 ft = approx. 5.029210058 m (a U.S. Survey Foot is 0.0002% longer than a regular foot).

(If needed, the current definition could be kept as "U.S. Survey Rod" / "US_rd" in the "US Survey" system, and a new definition "Rod (pole/perch)" / "rd" measuring exactly 16.5 ft added to the "Imperial/US" system.)

**Comment by hanna-kn** [comment]
Fixed.
