### ISSUE TITLE
possible bug: nested fibonacci outputs irrational and complex numbers

### ISSUE THREAD

**Issue by baroxyton** [Qalculate/libqalculate#561]
Tested in version 4.7.0

non-nested: `fibonacci(2) = 1`

nested:

`fibonacci(fibonacci(2)) ≈ 3.1708` (fibonacci(2) = 1, so the expected output would be 1)

`fibonacci(fibonacci(fibonacci(2))) ≈ 2.1403 + 0.049716i`  (fibonacci(2) = 1, so the expected output would be 1)

**Comment by hanna-kn** [comment]
This was definitely a bug, involving erroneous simplification of `(1/2)^((1 − (1/2)(√(5) + 1))^2) × 2^((1/4)(√(5) + 1)^2)`. It has now been fixed.
