### ISSUE TITLE
Interval display option "upper" and "lower" are opposite.

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#562]
Interval display option 5 should be "lower" and option 6 should be "upper".

> help set ivdisp 

interval display (ivdisp)
(0 = adaptive, 1 = significant, 2* = interval, 3 = plusminus, 4 = midpoint, 5 = upper, 6 = lower)

> 1000±5      

  1000±5 ≈ interval(995.0000000, 1005.000000)

> set ivdisp 5

  interval(995.0000000, 1005.000000) ≈ 995.0000000

> set ivdisp 6

  995.0000000 ≈ 1005.000000

> set ivdisp upper

  1005.000000 ≈ 1005.000000

> set ivdisp lower

  1005.000000 ≈ 995.0000000

**Comment by hanna-kn** [comment]
Fixed.
