### ISSUE TITLE
[Feature request] percent error in interval arithmetic

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#563]
I want to use percent error in interval arithmetic, for example
100V±10%*10A±10% = interval(810.0000000, 1210.000000) W

But convert interval to percent error is problematic, it is not symmetrical.
(810-1000)/1000 = -0.19
(1210-1000)/1000=0.21
1. It can be approximate to 1000W±20% with warning message to tell user that the actual result is not symmetrical.
2. It can be approximate to 1010W±19.8%

**Comment by hanna-kn** [comment]
Done.

`100V±10%*10A±10%` returns `(1010±20%) W` (with interval arithmetic) or `(1000±14%) W` (with default variance formula) when relative interval display activated. The value for `100V*10A` is not calculated when interval arithmetic is used for interval calculation, and alternative 2. is therefore used as with absolute error.

**Comment by howaboutuser** [comment]
If the error is really small, 0.0123% for example, will it display 0% or 1.23*10^(-2)%?

**Comment by hanna-kn** [comment]
> If the error is really small, 0.0123% for example, will it display 0% or 1.23*10^(-2)%?

The initial tentative implementation will display 0.012% (scientific notation is currently not used for the relative error). Two digits, excluding leading zeroes, are always used for the relative error < 100% (as is also the case for absolute error, using +/- or the new concise option).

If as many significant digits as allowed by the current precision setting can be displayed without error, relative error is omitted. If the relative error is >= 100 000%, absolute error is displayed instead.
