### ISSUE TITLE
Problems in base conversion

### ISSUE THREAD

**Issue by dschopf** [Qalculate/libqalculate#567]
I am currently trying to implement base conversion in my plasma applet, but I am facing some issue.

```
#include <iostream>
#include <libqalculate/qalculate.h>

int main() {
	Calculator calc{};
	Number number{"34"};
	PrintOptions po{};
	po.base = 62;
	std::cout << "Number = " << number.print(po) << "\n";
	return 0;
}
```
This code provides this output `Number = 34o0'`.
Using base 60 gives `Number = 34o0'0"`.

Changing the base to 64 yields (the expected) `Number = Y`. 

Could you please check if this is expected or if there is something wrong with my code?

**Comment by hanna-kn** [comment]
That only works for bases <= 36 (60 and 62 are used for sexagesimal numbers, see BASE_* in https://qalculate.github.io/reference/includes_8h.html).

For number bases > 36 (as well as negative and non-integer bases), use `po.base = BASE_CUSTOM;` in combination with `Calculate::setCustomOutputBase()`.

**Comment by dschopf** [comment]
Thanks for your quick support, it's working now.
