### ISSUE TITLE
Escape to clear in UI overloaded to hide window

### ISSUE THREAD

**Issue by NathanSweet** [Qalculate/libqalculate#568]
I often hit escape to clear the UI (GTK). If it's already clear, the window is closed (to the system tray). I find sometimes this leads me to inadvertently close the window.

Can the clear and close window keyboard shortcuts be specified in the `Keyboard Shortcuts`? They could be set to escape by default and give the current behavior when set to the same shortcut. This would allow me to unmap escape from closing the window.

**Comment by hanna-kn** [comment]
I will add an option, in preferences, to disable the behaviour. Escape also aborts slow calculations.
