### ISSUE TITLE
Question: plot title

### ISSUE THREAD

**Issue by pudrio** [Qalculate/libqalculate#571]
What is the correct syntax for the title option in the plot function? (and the syntax in general for text argument options)

this `plot(sin(x), 0, 2*pi, title 'Sine Function')` sets `Function") ("Sine` as the title.

using qalc 4.8.0

**Comment by hanna-kn** [comment]
Unfortunately you've found a bug, which results in option values containing space not working properly. `plot(sin(x), 0, 2*pi, title Function Sine)` will produce the title `Sine Function` (avoid quotation marks, and reverse the order of words in the title), which is obviously not intended.
