### ISSUE TITLE
gcd and lcm of fractional numbers

### ISSUE THREAD

**Issue by cousteaulecommandant** [Qalculate/libqalculate#577]
`gcd()` and `lcm()` seem to be currently limited to integral numbers, and give incorrect results with fractional numbers:
|     Input     | Expected | Obtained |
|---------------|----------|----------|
| gcd(1/2, 2/5) |   1/5    |    1     |
| lcm(1/2, 2/5) |    2     |   1/5    |

(My understanding is that the gcd of fractions is the gcd of the numerators divided by the lcm of the denominators, and vice versa for the lcm.  At the end, the return value of lcm() divided by any of its arguments must be an integer, and any of the arguments of gcd() divided by its return value must be an integer.)

I could find this useful in digital circuit design, where gcd and lcm of frequencies may need to be calculated in order to design clock generators or reset synchronizers (for example, to generate two clocks at 156.25 MHz and 200 MHz, I'll need a PLL with an lcm(156.25, 200) = 5000 MHz generator clock, and the common reset for these clocks must be clocked at gcd(156.25, 200) = 6.25 MHz).

**Comment by hanna-kn** [comment]
Done. (Previously gcd always returned 1, and lcm returned the product of the arguments, for non-integers.)

**Comment by cousteaulecommandant** [comment]
Thanks!
And kudos for the great work :)
