### ISSUE TITLE
odd error in year subtraction

### ISSUE THREAD

**Issue by kmfahey** [Qalculate/libqalculate#578]
Using the command-line interface 'qalc'. This subtraction from 'now' of a date in a previous decade with the result converted to years output an incorrect value:

```
> now

  now ≈ "2023-09-28T09:12:48"

> now - "1982-09-28T06:59:00"

  now − "1982-09-28T06:59:00" = 14975 d + 2 h + 14 min + 8.489095 s

> now - "1982-09-28T06:59:00" to years

  now − "1982-09-28T06:59:00" ≈ 40.99957065 yr

>
```

Since the month & day part of 'now', and the month & day part of the value being subtracted, are both equal to 9 months 28 d, and 2023 - 1982 = 41, the result should've been greater than 41.0 years.

```
> 14975 d + 2 h + 14 min + 8.489095 s to years

  (14975 × day) + (2 × hour) + (14 × minute) + (8.489095 × second) ≈ 40.99957058 yr

> (14975 + 2 / 24 + 14 / 60 / 24 + 0.489095 / 60 / 60 / 24) / 365.25

  (14975 + (2 / 24) + ((14 / 60) / 24) + (((0.489095 / 60) / 60) / 24)) / 365.25 ≈ 40.99957033

> (14975 + 2 / 24 + 14 / 60 / 24 + 0.489095 / 60 / 60 / 24) / 365.24219265

  (14975 + (2 / 24) + ((14 / 60) / 24) + (((0.489095 / 60) / 60) / 24)) / 365.24219265 ≈ 41.00044672

> 
```

The result converted to years should have yielded a value above 41.0. Apparently this arose from choosing 365.25 d for the length of a year, where 365.24219265 d is approximately the correct value ([citation](https://en.wikipedia.org/wiki/Year#Symbols_and_abbreviations), paragraph 7). Here, that choice means a calculation gave an incorrect result. Of course that choice wasn't made without consideration. What is the reason why 365.25 d was chosen as the length of a year?

**Comment by hanna-kn** [comment]
> What is the reason why 365.25 d was chosen as the length of a year?

365.25 d is the exact value of the Julian year, used in astronomy (https://en.wikipedia.org/wiki/Julian_year_(astronomy)). This definition was chosen for the year unit almost two decades ago. Ideally multiple year units should be provided, but a definition for the year unit using the year names and abbreviations, without modifiers, still needs to be selected.

The yearfrac() function well return the correct value for the specific calendar years, e.g. `yearfrac(1982-09-28T06:59:00, 2023-09-28T09:12:48) ≈ 41.000 906 29`, which no average year conversion will achieve.

**Comment by kmfahey** [comment]
Alright, got my answer. In view of the fact that— due to leap seconds— all years don't have the same length, it was unrealistic for me to expect a very-precise-seeming value for year length. Thanks for pointing me to the function I should've been using. Since it's working as intended, I'll close my issue.

**Comment by kmfahey** [comment]
Alright, got my answer. In view of the fact that— due to leap seconds— all years don't have the same length, it was unrealistic for me to expect a very-precise-seeming value for year length. Thanks for pointing me to the function I should've been using. Since it's working as intended, I'll close my issue.
