### ISSUE TITLE
Support binomial coefficients with negative exponent

### ISSUE THREAD

**Issue by Serphentas** [Qalculate/libqalculate#58]
If we have `binomial(-a, b)` where a and b are integers, it should be treated as `binomial(a+b-1, b)*(-1)^b`.

For instance, `binomial(-5, 3)` would be equal to `binomial(7, 3)*(-1)^3`.

If it can be of any help, here's a video about the [extended binomial theorem](https://youtu.be/ZyUb5UxBA9Q?t=317).

**Comment by hanna-kn** [comment]
Done.

**Comment by Serphentas** [comment]
That was fast, thanks !
