### ISSUE TITLE
allow `_` (underscore) as thousand separator

### ISSUE THREAD

**Issue by yukulele** [Qalculate/libqalculate#582]
Some programming languages allow the underscore as a digit separator:
```typescript
const worldPopulation = 8_066_228_201
```
Pasting from code to qalc generates errors.

Qalc should also allow underscore as a digit separator

**Comment by hanna-kn** [comment]
Done.

**Comment by agguser** [comment]
Is there an option to use underscores (instead of spaces) as "output" thousands separators?

```(sh)
% qalc '12345'
12 345 = 12 345   # how to make it '12_345 = 12_345'?
```

**Comment by hanna-kn** [comment]
> Is there an option to use underscores (instead of spaces) as "output" thousands separators?
> 
> ```
> % qalc '12345'
> 12 345 = 12 345   # how to make it '12_345 = 12_345'?
> ```

There are three alternatives for thousands separators in qalc - off (default), standard (space), and locale (uses the current system locale). It should be possible modify a system locale to use underscore as separator, and use this for Qalculate (use `set group 2` in qalc and run with `LC_NUMERIC` set to the custom locale), but there no option to set underscore as separator directly within qalc (or any of the GUIs).

**Comment by agguser** [comment]
With `set group 2` (locale), there is no grouping after decimal point:
```sh
$ qalc -t '[12345.12345 0]'
[(12 345.123 45)  0]

$ qalc -t -s 'group 2' '[12345.12345 0]'
[(12,345.12345)  0]
```
Also note that using [narrow no-break] spaces (or commas) as group separators also shows extra parentheses.

It would be better to be able to use underscores as group separator, e.g.:
```sh
$ qalc -t -s 'group 4' '[12345.12345 0]'
[12_345.123_45  0]
```

**Comment by hanna-kn** [comment]
> With `set group 2` (locale), there is no grouping after decimal point

This is intentional. Digits after the decimal separator is usually not grouped, especially not with local formats, and if they are no common conventions for how they are grouped (often groups of five are used).

> Also note that using [narrow no-break] spaces (or commas) as group separators also shows extra parentheses.

This is unfortunately unavoidable in vectors and matrices.

> It would be better to be able to use underscores as group separator

Done (option added, `group 3`).
