### ISSUE TITLE
"micrometer" doesn't parse correctly in Russian

### ISSUE THREAD

**Issue by HolyBlackCat** [Qalculate/libqalculate#585]
Running a Russian locale.

Those work correctly: `20 um`, `20 microm`.

Starting to type `micro...` suggests `микрометр` (`micrometer` in Russian), but accepting this completion inserts `microметр` (a weird combination of Russian and English).

`microметр` somehow parses correctly, but the fact that the completion gui inserts a different string compared to what it displays looks like a bug to me.

Starting to type `микро...` suggests `микрометр` too, and this time accepting the suggestion inserts `микрометр` as expected, but this doesn't parse correctly (parses as `20 m rontobyte m`), which is also a bug.

**Comment by hanna-kn** [comment]
Parsing of микрометр has now been fixed.
