### ISSUE TITLE
[feature request]: Print exponents as unicode when unicode signs are enabled and it's possible to do so

### ISSUE THREAD

**Issue by markozajc** [Qalculate/libqalculate#586]
For example print `= x^2` as `= x²` if `use_unicode_signs` is set to true. This isn't possible in all cases (nested exponents, unsupported characters, etc.), but Unicode does have superscripts for numbers and some operations: https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts.

**Comment by hanna-kn** [comment]
Done (Unicode superscript will be used for all exponents 0-9 if there are no other exponents in the expression; previously Unicode superscript where only used units).

**Comment by markozajc** [comment]
Works as intended, thanks.
