### ISSUE TITLE
Converting joules to ft-lb or vice versa results in output including sieverts (Sv) for some reason.

### ISSUE THREAD

**Issue by iguanajuice** [Qalculate/libqalculate#588]
I want to convert ft-lb to joules by entering the following:

> 409 ftlb to J

I expect to get the answer of 556 ft-lb, but instead I get this:

>  409 foot·pounds ≈ 56.54627634 J·m/Sv

This doesn't occur when converting SI energy units to other SI energy units, and it also doesn't occur when converting imperial energy units to other imperial energy units. It's only when you try to convert across "standards" that you get this weird sievert problem.

**Comment by hanna-kn** [comment]
Use lbf (pound-force) instead of lb (pound-mass).
`409 ftlbf ≈ 554.529 540 9 J`

**Comment by iguanajuice** [comment]
Ah...mass vs force. Rookie mistake.
