### ISSUE TITLE
No `day` time unit 

### ISSUE THREAD

**Issue by Xotchkass** [Qalculate/libqalculate#591]
So for some reason qalc doesn't have a day unit. There is hour, second. week, year, even month ( which looks pretty arbitrary ngl) 
![изображение](https://github.com/Qalculate/libqalculate/assets/78706300/0bbf4215-c310-4603-b45a-408c866c254f)
But no day.
![изображение](https://github.com/Qalculate/libqalculate/assets/78706300/b0412691-29fa-4e89-98b3-85b5bf97fc04)
![изображение](https://github.com/Qalculate/libqalculate/assets/78706300/3ef4d0e2-c991-44dc-a05d-900a9b039a91)

**Comment by Xotchkass** [comment]
Okay, weird. I looked through code and found [it](https://github.com/Qalculate/libqalculate/blob/2b9b0e5468692dfeb40288a1f433dea8a3f28387/data/units.xml.in#L873) defined, but the as I showed above it doesn't show in the unit list and app doesn't recognize it.
![изображение](https://github.com/Qalculate/libqalculate/assets/78706300/3bd2b38d-e654-46ad-8742-e48dce1ef0ab)
Is this because of the collision with the `day` function?
![изображение](https://github.com/Qalculate/libqalculate/assets/78706300/c0f21559-3d4f-4aa4-85bf-f4b0e3d2d871)
![изображение](https://github.com/Qalculate/libqalculate/assets/78706300/003bfa76-ce31-493a-b69d-99d90ac1594d)

**Comment by hanna-kn** [comment]
It seems as if you've somehow deactivated the day unit. Deactivated units can be found in the `Edit->Units` dialog, or in `definitions/units.xml` in the configuration directory.

Units and functions with the same name can coexist without any issues (the unit is used unless the name is followed by an argument in parentheses).

![Skärmklipp](https://github.com/Qalculate/libqalculate/assets/19703699/bc8622d5-4a6d-4646-a388-5399e5b58ae2)

**Comment by Xotchkass** [comment]
Okay, I didn't event knew you can deactivate units here, and somehow did it.
