### ISSUE TITLE
some problem with newtonsolve

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#598]
1. What are "Precision" and "Max iterations" in newtonsolve?
newtonsolve(Equation, Initial estimate[, Variable][, Precision][, Max iterations])

> genvector(newtonsolve(x**2-1,2,,n,),-10,10,1,n) 

  genvector(newtonsolve(x² − 1, 2, undefined, n), −10, 10, 1, n) ≈
  [1.000000000  1.000000000  1.000000000  1.000000000  1.000000000  1.000000000  1.000000000  1.000000000 
  1.000000000  1.000000000  1.000000000  1.0  1.000  1.000  1.0000000  1.0000000  1.0000000  1.0000000 
  1.000000000  1.000000000  1.000000000]

> genvector(newtonsolve(x**2-1,2,,,n),0,10,1,n)  

  genvector(newtonsolve(x² − 1, 2, undefined, −10, n), 0, 10, 1, n) ≈
  [newtonsolve(x² − 1, 2, x, −10.00000000, 0.000000000)  newtonsolve(x² − 1, 2, x, −10.00000000, 1) 
  newtonsolve(x² − 1, 2, x, −10.00000000, 2)  newtonsolve(x² − 1, 2, x, −10.00000000, 3)  1.0000000 
  1.000000000  1.000000000  1.000000000  1.000000000  1.000000000  1.000000000]

expect
[2  1.25  1.025  1.000304878  1.000000046  1.000000000  1.000000000  1.000000000  1.000000000  1.000000000  1.000000000]

2. transpose not work when newtonsolve inside.
> transpose(genvector(newtonsolve(x**2-1,2,,,n),0,10,1,n))

  error: Argument 1, Matrix, in transpose() must be a matrix.
  transpose(genvector(newtonsolve(x² − 1, 2, undefined, −10, n), 0, 10, 1, n)) ≈
  transpose([newtonsolve(x² − 1, 2, x, −10.00000000, 0.000000000)  newtonsolve(x² − 1, 2, x, −10.00000000, 1) 
  newtonsolve(x² − 1, 2, x, −10.00000000, 2)  newtonsolve(x² − 1, 2, x, −10.00000000, 3)  1.0000000 
  1.000000000  1.000000000  1.000000000  1.000000000  1.000000000  1.000000000])

3. When variable not in first argument in newtonsolve, it will crash.
> genvector(newtonsolve(x**2-1,2,,,x),0,10,1,x)

I accidentally change  newtonsolve(x**2-1,2) to newtonsolve(-1,2).

**Comment by hanna-kn** [comment]
### 1.
Precision is the least number of significant digits requested. If precision is negative or zero, the general precision set in Qalculate is used, with the precision argument subtracted (the default precision argument is -10, which, with the default general precision, 10, results in a precision of 20).

The max iterations determines over how many iterations Newtons's method will run at most.  Even If the the requested precision has not been reached, the function will only return an estimate if the achieved number of significant digits is at least 5 (this fails in the example when max iterations is less than 4).

### 2.
Transpose fails because of failure to determine if the failed newtonsolve() functions represents scalars. This has now been fixed.

### 3.
The crash has now been fixed.

**Comment by howaboutuser** [comment]
f(x):=x**2*(x-1000)+1
x0=1
expect
[1  0.5002503756  0.2510628283  0.1275079337  0.06767197627  0.04122417602  0.03274121836         
  0.03164236164  0.03162328238  0.03162327662  0.03162327662]

> genvector(newtonsolve(x**2(x-1000)+1,2,,n),0,10,1,n)                                        

  genvector(newtonsolve((x² × (x − 1000)) + 1, 2, undefined, n), 0, 10, 1, n) ≈
  [0.03162327662  0.0316±0.0011  0.0316  0.0316  0.0316233  0.0316233  0.0316233  0.03162327662 
  0.03162327662  0.03162327662  0.03162327662]

How do you determine precision?
x6=0.03274121836
x7=0.03164236164 (1 significant digit, 0.03, delta=0.001098856718)
x8=0.03162328238 (3 significant digit, 0.0316, delta=0.00001907926676)
x9=0.03162327662 (6 significant digit, 0.0316232, delta=0.000000005755271290)
Why "±" appear in result?


"the function will only return an estimate if the achieved number of significant digits is at least 5"
Now I know why newtonsolve(x**2,1) not work.

**Comment by hanna-kn** [comment]
newtonsolve() returns value±delta (approximate values are represented by an interval in Qalculate). For values with only one significant digit, the uncertainty of the value is shown using ±-notation. by default.

**Comment by hanna-kn** [comment]
Also note that you can place the vector in the newtonsolve() argument instead (e.g. `newtonsolve(x**2(x-1000)+1,2,,genvector(x,0,10))`), which makes the expression easier to read.

**Comment by howaboutuser** [comment]
Thank you for your patient to answer my question, although I can't produce result identically like newtonsolve.

newtonsolve((x² × (x − 1000)) + 1, 1, undefined, genvector(x, 0, 10)) ≈
  [0.03162327662  0.0316±0.0011  0.031623±0.000019  0.031623±0.000019  0.0316232766±0.0000000058 
  0.0316232766±0.0000000058  0.0316232766±0.0000000058  0.03162327662  0.03162327662  0.03162327662 
  0.03162327662]

> f(x):=x**2*(x-1000)+1

> xi=0.0316±0.0011                                                            

  save(0.0316±0.0011, xi, Temporary, , 1) ≈ 0.0316±0.0011

> xi=xi-f(xi)/diff(f(x),x,,xi)

  save(xi − (f(xi) / diff(f(x), x, 1, xi)), xi, Temporary, , 1) ≈ 0.031634±0.000011

> xi=xi-f(xi)/diff(f(x),x,,xi)

  save(xi − (f(xi) / diff(f(x), x, 1, xi)), xi, Temporary, , 1) ≈ 0.0316232800±0.0000000034

> xi=xi-f(xi)/diff(f(x),x,,xi)

  save(xi − (f(xi) / diff(f(x), x, 1, xi)), xi, Temporary, , 1) ≈ 0.03162327662

**Comment by howaboutuser** [comment]
How about add a parameter to choose between precision and tolerance? Because it is impossible to reach 5 significant digits when root is at 0.

**Comment by hanna-kn** [comment]
> Thank you for your patient to answer my question, although I can't produce result identically like newtonsolve. (...)

That is not how it works. The interval is only set using delta after the final iteration.

> How about add a parameter to choose between precision and tolerance? Because it is impossible to reach 5 significant digits when root is at 0.

There is a workaround for this in the function (although in doesn't come into play until iteration ten).

**Comment by howaboutuser** [comment]
It will not return 0 when x^n inside.
> newtonsolve(x**2,1)   

  newtonsolve(x², 1) = newtonsolve(x², 1)

> newtonsolve(x**3,1) 

  newtonsolve(x³, 1) = newtonsolve(x³, 1)

> newtonsolve(x**2*(x+1),1) 

  newtonsolve(x² × (x + 1), 1) = newtonsolve(x³ + x², 1)

> newtonsolve(x**3*(x+1),1) 

  newtonsolve(x³ × (x + 1), 1) = newtonsolve(x⁴ + x³, 1)

**Comment by hanna-kn** [comment]
> It will not return 0 when x^n inside.

Fixed.
If current value is close to zero, validity of zero as solution is tested. Hopefully the changes don't break anything.

**Comment by howaboutuser** [comment]
```
> newtonsolve((x+1)**2,1)             

  newtonsolve((x + 1)², 1) = newtonsolve(x² + 2x + 1, 1)

> newtonsolve((x+1)**2,3)

  newtonsolve((x + 1)², 3) = newtonsolve(x² + 2x + 1, 3)

> newtonsolve((x+1)**2,7)

  newtonsolve((x + 1)², 7) = newtonsolve(x² + 2x + 1, 7)

> newtonsolve((x+1)**2,15)

  newtonsolve((x + 1)², 15) = newtonsolve(x² + 2x + 1, 15)
```
expect: -1
