### ISSUE TITLE
libqalculate-0.9.9 - qalc.cc:3182:11: error: 'historyfile' was not declared in this scope

### ISSUE THREAD

**Issue by sugudega** [Qalculate/libqalculate#6]
Hi,

If Readline is disabled, compilation of libqalculate-0.9.9 fails with:

```
qalc.cc: In function 'void load_preferences()':
qalc.cc:3182:11: error: 'historyfile' was not declared in this scope
    g_free(historyfile);
```

Here is a patch to ifdef this line, which was missed:
https://gist.github.com/sugudega/99f6f439c05cb9cf1481498830e01ab3

(Thanks for reviving this project :))

Bye.

**Comment by hanna-kn** [comment]
Thanks. The patch has been applied.
