### ISSUE TITLE
`… oz to kg` output is an ugly fraction

### ISSUE THREAD

**Issue by ckiee** [Qalculate/libqalculate#606]
qalculate says:
```
> 7.5oz to kg
 
  7.5 ounces = (136077711/640000000) kg

> 7.5oz to grams
 
  7.5 ounces = (136077711/640000) g
```

DDG says: 
![Screenshot of https://duckduckgo.com/?t=ffab&q=7.5oz+to+kg&ia=web](https://github.com/Qalculate/libqalculate/assets/25263210/af0c667c-dc8c-44d7-bae6-7dbfdccc70f1)

(136077711/640000)g is ~212.621g, and this latter number is much more readable. Same with the kg.

**Comment by hanna-kn** [comment]
By default `7.5oz to kg` returns `≈ 0.2126214234 kg`. Please check the status of the `fractions` setting (e.g. `help fr`), and specify which version you are using.

**Comment by ckiee** [comment]
This is qalc 4.9.0, and `number_fraction_format=-1`in `~/.config/qalculate/qalc.cfg`, which seems to be the default.

**Comment by hanna-kn** [comment]
The output might also be caused by approximation set to exact (0, default is -1 = auto), in combination with the default fraction setting.

**Comment by ckiee** [comment]
That was that. It was `-2` for some reason.

thank you (:
