### ISSUE TITLE
Return Status Code in CLI When Used Non-Interactively and Use Stderr

### ISSUE THREAD

**Issue by bbb651** [Qalculate/libqalculate#607]
Currently the CLI seems to always exit with status code 0, even when it detects an error, and errors are always reported to stdout rather than stderr:
```
❯ qalc "error("test")"
error: test
error("test") = 0

❯ echo $status
0
```
I'm trying to interact with `qalc` through a python script and be detect if an error has occurred, and this behavior makes it pretty annoying, and doesn't follow the standards pretty much every other cli programs do.

It's also worth nothing that there's no good way to separate flags passed to the cli from the input, so if you misspell a cli flag it'll be treated as input, supporting something like `--` to separate between them is a pretty common practice.

Heck, handling of arguments seems to be pretty buggy in general, the `qalc(1)` man page lists many arguments starting with 2 dashes (which is the more common and correct form of arguments that are more than 1 letter):
```
--nocurrencies
               do not load any global currencies from file
``` 
But they only actually work with a single dash, leading to silly situations like this:
```
❯ qalc --nocurrencies
error: "r" is not a valid variable/function/unit.
−(−false) centiAtomicMassUnits × re(n × SpeedOfLight × i × e seconds) ≈ 0.000000000 m·u
```

**Comment by hanna-kn** [comment]
Exit code and -no... arguments double dash has now been fixed.
