### ISSUE TITLE
some problem with lambertw()

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#608]
1. Typo in lambertw help message
>Returns the inverse function for mx*e^x as ln() does for e^x.

mx*e^x -> x*e^x

2. Should lambertw(pi*e**pi) return pi in exact mode?
> set approximation exact

  lambertw(pi * e^pi) = lambertw(e^pi * pi)

**Comment by hanna-kn** [comment]
Fixed (lambertw(x × e^x) = x for x ≥ −1).

**Comment by howaboutuser** [comment]
>lambertw(x × e^x) = x for x ≥ −1

x>=-1/e?
