### ISSUE TITLE
[Feature request] angle form to anlge unit conversion

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#609]
1+i to angle to deg
When complex number is polar form, cis form or angle form, I want to use "to" to convert the angle unit.

**Comment by hanna-kn** [comment]
Done.

**Comment by howaboutuser** [comment]
Why I can not set cplxform using cis?
> set cplxform cis

Illegal value.
> set cplxform 3  

  1 + i = √(2) cis (π / 4)
