### ISSUE TITLE
switch unicode support on/off is reverse in command line argument

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#610]
$qalc -u8  "sqrt(2)"
sqrt(2) = √(2)

$qalc +u8  "sqrt(2)"
sqrt(2) = sqrt(2)

**Comment by hanna-kn** [comment]
That is as intended. `-u8` enables Unicode (as would be expected if the variant with plus was not available), while `+u8` performs the reverse action (disables Unicode). This is in line with how, in my experience, `+` in front of a command line option is usually used when it occurs (not very often) in GNU/Linux.

**Comment by howaboutuser** [comment]
If +u8 is not available, should the default output is unicode disable?

**Comment by howaboutuser** [comment]
I found that setting in interactive mode cause the CLI output unicode without specifying -u8.
