### ISSUE TITLE
false result in an operation with power representation of numbers

### ISSUE THREAD

**Issue by Hans-Theo** [Qalculate/libqalculate#611]
The correct result of the operation 389420489 * 389420488 / 2 = binomial coefficient (9⁹ over 2) is 75 824 158 431 789 316.
But the equivalent expression 9⁹ * (9⁹ - 1) / 2 results in a false value of 75 047 317 454 789 316.
Interestingly, the first two and the last 6 digits are correct.
(using a sufficient high precision of numbers, set by Mode > Precision)

**Comment by hanna-kn** [comment]
9⁹ equals 387420489, not 38**9**420489.
(387420489 × 387420488) / 2 = 75 047 317 454 789 316.
