### ISSUE TITLE
some problem with "delete" command

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#616]
1. If global function or unit is rewrited, then use "delete" to restore the function or unit, the name doesn't delete in list command.

>sin()=1
N=1
delete sin
delete N
list

Variables:
Name                                    Value
ans                                     1
ans2                                    '1'

Functions:
sin

Units:
newton

2. If variable and function have same name, it can not specify which to delete. (delete temp() not work)

>temp=1
temp()=2
delete temp
list

Variables:
Name                                    Value
ans                                     '2'
ans2                                    1

Functions:
temp

**Comment by hanna-kn** [comment]
Fixed.
