### ISSUE TITLE
Issue with 'set' command.

### ISSUE THREAD

**Issue by owabs187** [Qalculate/libqalculate#618]
Hello, I am a relatively new user of the 'qalc' CLI application, and I keep having an issue with the 'set' command. I often need to switch from radian to degree mode, so I use 'set angle 1' or 'set angle 2'. It works sometimes, but other times, it will display "second x e tonnes = 2.718281828 t*s". I have no idea why it sometimes works, but other times it doesn't. Thank you in advance for any help.

**Comment by hanna-kn** [comment]
That is the expected output when you enter `set` without any argument. If you prepend `/` to the command (e.g. `/set`) it will never be interpreted as an expression, in which case the error "set requires at least one argument" would instead be expected.

It seems odd that you would receive this output if `set` is entered with an argument (even if it is mistyped). More information about your system (e.g. Qalculate version and installation method, operating system, terminal emulator, locale) might be helpful.

**Comment by owabs187** [comment]
Platform Infromation:
Architecture: x86_64
OS: EndeavourOS (Arch-based Linux distro)
Terminal: Konsole
Shell: Bash
Locale: en_US.UTF-8
libqalculate version: 4.9.0
Installation method: pacman

One pattern I have noticed is that if you enter `set` without an argument by accident, and then you enter `set` with an argument (ex. `set angle 2`), then it won't work.

![image](https://github.com/Qalculate/libqalculate/assets/114690595/fd82b38a-5dc8-4756-8065-75db52554791)

But it also just randomly doesn't work sometimes.

Hope this info helps.

**Comment by hanna-kn** [comment]
> One pattern I have noticed is that if you enter set without an argument by accident, and then you enter set with an argument (ex. set angle 2), then it won't work.

In this case I'm quite sure that it does work. First the expression "set" is calculated. Then, when the angle unit is changed, the previous expression, in this case "set", is recalculated.

To avoid this confusion, I will change the behaviour to show an error message instead when "set" is entered without any argument, even if not `/` is used.
