### ISSUE TITLE
default setting different from qalc man page

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#619]
qalc man page: https://qalculate.github.io/manual/qalc.html

>qalc --defaults
mode

...
minus last (minlast)                            on (off in man page)
...
repeating decimals (repdeci)                    off (missing in man page)
...
parsing mode (parse)                            adaptive (syntax in man page)
...
simplified percentage (percent)                 on (missing in man page)
...
sigint action (sigint)                          exit (kill in man page)

BTW, man page can be improved by adding some description or example.

**Comment by hanna-kn** [comment]
Fixed.

**Comment by howaboutuser** [comment]
>mode

parsing mode (parse)                            adaptive

> help set parse

parsing mode (syntax)
See 'help parsing mode'.
(0* = adaptive, 1 = implicit first, 2 = conventional, 3 = chain, 4 = rpn)

Will you reserve both "parse" and "syntax"?

**Comment by hanna-kn** [comment]
Both "parse" and "syntax" will be supported, but the mode and help commands, and the man page should of course show the same short option name (probably "syntax", which was introduced in version 3.16).
