### ISSUE TITLE
How to set variable from non-interactive command?

### ISSUE THREAD

**Issue by SeryiBaran** [Qalculate/libqalculate#621]
How to set variable and compute something, if i'm generate qalc commands for non-interactive running from js script?
```js
await awaitSpawn('qalc.exe', ['-t', `aq^5`]) // how to set a and q?
```

**Comment by hanna-kn** [comment]
Simplest option is to use `where`, e.g. `aq^5/.a=5,q=2` (short variant of `aq^5 where a=5 and q=2`).

**Comment by SeryiBaran** [comment]
> Simplest option is to use `where`, e.g. `aq^5/.a=5,q=2` (short variant of `aq^5 where a=5 and q=2`).

wow, thanks!
