### ISSUE TITLE
Dsolve : Unable to solve diff(y) = -y

### ISSUE THREAD

**Issue by kernelb00t** [Qalculate/libqalculate#623]
```
> dsolve(diff(y) = -y)

  error: No differential equation found.
  dsolve(diff(y) = (−y)) = dsolve(y + diff(y) = 0)
```
But : 
![image](https://github.com/Qalculate/libqalculate/assets/68474172/3c30038e-2095-409c-9eca-6781e2b50798)

Is it me not kowing how dsolve is working? Or is it Dsolve just behaving weirdly? 

Computer :
- Arch Linux latest
```
3 extra/libqalculate 4.9.0-2 (2.7 MiB 14.9 MiB) (Installed)
    Multi-purpose desktop calculator
2 extra/qalculate-gtk 4.9.0-1 (2.4 MiB 6.0 MiB) (Installed)
    GTK frontend for libqalculate
```
- Intel CPU

**Comment by hanna-kn** [comment]
```
> dsolve(diff(y, x) = −y)

  dsolve(diff(y, x) = (−y)) = C / e^x ≈ 0.3678794412^x × C

```
Note however that version 4.9.0 is unable to isolate _x_ because _C_ is not assumed real (see https://github.com/Qalculate/libqalculate/issues/617).
