### ISSUE TITLE
Incorrect sum plot

### ISSUE THREAD

**Issue by SeryiBaran** [Qalculate/libqalculate#630]
I'm use Qalculate-qt 4.9.0.

I'm try to generate plot of this expression:
```
sum(( (−1)^(n+1) )/(2^n),1,x)
```
![image](https://github.com/Qalculate/libqalculate/assets/82605415/1fa50dda-6bbc-448b-8bd7-6865549bb942)

With this parameters:

![image](https://github.com/Qalculate/libqalculate/assets/82605415/143c4d63-636d-448e-b997-9c90b66a9695)

![image](https://github.com/Qalculate/libqalculate/assets/82605415/fe8ac746-db8e-469d-8ed4-c53a1d075999)

But i'm got this:

![image](https://github.com/Qalculate/libqalculate/assets/82605415/e7f89369-2209-436c-a2e3-cdc51d4e7c14)

Instead of something like this:

![image](https://github.com/Qalculate/libqalculate/assets/82605415/b3fafb37-0be8-4b08-9528-2beee7010e85)

**Comment by hanna-kn** [comment]
The data is correct (see below), but for the output is confusing when line style is selected. In this case I recommend that you use "steps" instead.

**Comment by SeryiBaran** [comment]
Thanks!

**Comment by howaboutuser** [comment]
Why not plot like this when using line style?
![圖片](https://github.com/Qalculate/libqalculate/assets/120489523/6591d07e-b3b2-4fad-b044-2e838b1b433a)

**Comment by SeryiBaran** [comment]
Points style works, hm..

![image](https://github.com/Qalculate/libqalculate/assets/82605415/329b1190-8c45-4cca-992f-a531ad5dad8d)

**Comment by hanna-kn** [comment]
The cause of this behaviour is that Qalculate marks the data points as discontinuous. A solution might be to automatically change style from line to point (or dot) if there are many discontinuous data points (e.g. more that half), or possible if there multiple consecutive discontinuous points.
