### ISSUE TITLE
Knuth's arrow notation?

### ISSUE THREAD

**Issue by SeryiBaran** [Qalculate/libqalculate#634]
Do you planning to add [Knuth's up-arrow notation](https://en.wikipedia.org/wiki/Knuth%27s_up-arrow_notation) (`↑`)?

**Comment by hanna-kn** [comment]
How useful would this be?
Perhaps it's enough to add a power tower/tetration (↑↑) function, considering how ridiculously large numbers additional arrows produce even for small values.
