### ISSUE TITLE
Suggestion: support converting an exact fraction to factors

### ISSUE THREAD

**Issue by arseniiv** [Qalculate/libqalculate#635]
I would find it very useful to factorize not only integers but also fractions like `117/121 to factors` ⟹ `3^2 * 13 / 11^2`.

Right now neither can I do something like `[117, 121] to factors` nor `117 to factors, 121 to factors` in one go.

What do you think?

**Comment by hanna-kn** [comment]
Done (support for `117/121 to factors` and `[117, 121] to factors`).
