### ISSUE TITLE
Usage as calculator engine on physical calculator 

### ISSUE THREAD

**Issue by BasilioPV** [Qalculate/libqalculate#639]
First of all, your project is awesome!!
Being your proyect written in C++, I need to know if it will be possible to compile them for the use on modern ARM calculators such as:

https://www.swissmicros.com/product/dm42

https://hackaday.io/project/179949-openrpncalc

The objective is to run into:

"The STM32L476xx devices embed high-speed memories (Flash memory up to 1 Mbyte, up to 128 Kbyte of SRAM)"

But other bigger alternatives, such as ESP32 or raspberry pi zero, can be an alternative.

What do you think?
Thanks

**Comment by hanna-kn** [comment]
I'm not familiar with any of the mentioned hardware. Compilation should be possible, but you would likely also need to compile at least some of the dependencies, and it is unlikely that processor speed and available memory is enough for anything with less resources than raspberry pi zero.
