### ISSUE TITLE
raw stdin-based input mode for piping expressions

### ISSUE THREAD

**Issue by ishaan-sen** [Qalculate/libqalculate#644]
I frequently find myself piping expressions from terminal-based text editors like Helix into qalc for computation. I've looked, but I haven't yet found any way to make qalc accept input from standard input without printing the `>` prompt for interactive mode.
Currently, I have an alias that uses xargs to enter my expression as an argument to `qalc -t`. I was wondering if there could be a new CLI option for returning the result of an expression piped into stdin. 

Is there already a way to do this? If not, I'm open to trying it and making a PR if this is wanted.

**Comment by hanna-kn** [comment]
How about `qalc -t -f -`?
`-f`/`--file` tells qalc to read expressions and commands from the specified file (in this case stdin).

**Comment by ishaan-sen** [comment]
Of course. Setting the file to stdin didn't occur to me. Thanks for the amazing calculator; I use it every day.
