### ISSUE TITLE
`qalc` is lying: `((((2 × x) + 1)²) > 1) = false`

### ISSUE THREAD

**Issue by xBZZZZ** [Qalculate/libqalculate#648]
version: b075892720db019a4ec851375bc7d3f55e6127f1<table><tr><th valign="top" align="left" scope="col">real and incorrect result</th><th valign="top" align="left" scope="col">expected and correct result</th></tr><tr><td valign="top" align="left"><pre>$ src/qalc&#10;&#62; (2x+1)^2 &#62; 1&#10;&#10;  ((((2 &#215; x) + 1)&#178;) > 1) = false</pre></td><td valign="top" align="left"><pre>$ src/qalc&#10;&#62; (2x+1)^2 &#62; 1&#10;&#10;  x &#62; 0 or&#10;  x &#60; &#8722;1</pre></td></tr></table>

**Comment by xBZZZZ** [comment]
<pre>$ src/qalc&#10;&#62; (2x+1)^2 &#62; 1&#10;&#10;  x &#62; 0 or&#10;  x &#60; &#8722;1</pre>after 77a7b35b28a4a637058405c9afe304f402f01637

**Comment by hanna-kn** [comment]
Thanks for discovering this quite serious bug. OR was replaced with AND (because the inequality type used was out of date). Due to it seemingly affecting few inequalities (`(ax+1)^n > 1` and `(ax+1)^n ≥ 1`, where a is not 1 and is positive and even) , it was difficult to discover.
