### ISSUE TITLE
`Number.allroots` contains unchecked dereference of `i_value`

### ISSUE THREAD

**Issue by afishhh** [Qalculate/libqalculate#649]
`Number::allroots` dereferences `i_value` [here](https://github.com/Qalculate/libqalculate/blob/6473679b7b419740f72d396a305734382de6e821/libqalculate/Number.cc#L4559) before checking whether it's non-null. I would submit a pull request but I don't even know what the function does and thus have no idea what the correct behavior is.

**Comment by hanna-kn** [comment]
The function should return (in provided vector) all real and complex roots for the specified integer degree. 

It will segfault for values without imaginary parts when the degree is an integer > 2.

The function is however not used anywhere.
