### ISSUE TITLE
Revolutions per minute unit?

### ISSUE THREAD

**Issue by BasilioPV** [Qalculate/libqalculate#652]
Where is defined the rev/minute (rpm) unit?

**Comment by sta-c0000** [comment]
hertz:
```
qalc 1500/min   #   1500 / minute = 25 Hz
qalc 25Hz*min   #   (25 hertz) × minute = 1500
```

**Comment by Vomet** [comment]
I second this. I also think it'd be nice to have a "revolutions" or "rotations" unit. We could set it such that:

1 revolution/rotation = 2 pi radians = 360 degrees

**Comment by sta-c0000** [comment]
> 1 revolution/rotation = 2 pi radians = 360 degrees

That's 1 τ (one tau):
```
qalc τ        #   tau = 2π ≈ 6.283185307
qalc τ to deg #   tau radians ≈ 360.0000000°
```

**Comment by hanna-kn** [comment]
It seems as if it would be most correct to define `rpm` as equivalent to `min<sup>-1</sup>` (rotational frequency). Alternatively it can be defined using `turns/minute` (angular frequency).

>  I also think it'd be nice to have a "revolutions" or "rotations" unit. We could set it such that:
>
> 1 revolution/rotation = 2 pi radians = 360 degrees

There is already a "turn(s)" unit which equals 360 degrees. It would be possible to add additional names/symbols to this unit.

**Comment by hanna-kn** [comment]
I've now added additional names/symbols (including rev, revolution, revolutions) to turn unit, and rpm as symbol for turns/minute.
