### ISSUE TITLE
`factor` as command line argument stops `qalc` from exiting

### ISSUE THREAD

**Issue by Diomendius** [Qalculate/libqalculate#656]
Running `qalc factor 1` causes `qalc` to write `1 = 1` followed by a newline to stdout, but the program does not exit. In this state, it ignores all input and consumes no CPU time until terminated by `CTRL-C` or similar.

The number chosen does not matter. `qalc` will output the correct answer and then hang.

Passing `factor` via stdin does not trigger the bug:
```
qalc <<< 'factor 1'; echo DONE
> factor 1

  1 = 1

> DONE
```

**Comment by hanna-kn** [comment]
Fixed (the thread involved in factorization was not terminated).

**Comment by Diomendius** [comment]
A nice speedy fix. Thanks!
