### ISSUE TITLE
Question about replacement in MathStructure

### ISSUE THREAD

**Issue by nick87720z** [Qalculate/libqalculate#66]
If i try to work with UserFunction, using MathStructure("x") as argument (turned to vector), result print() showes all x invocations double-quoted, and replacement works:
For example, for formula __'\x^2 + 3\x'__ calculate result before replacement will print __"x"^2 + 3 "x"__, and replacing to 2, i get: __2^2 + 3 * 2__ .
But for just __'x^3 - 2x'__ it does __x^3 + -2x__, and replacement doesn't work with it.

**Comment by hanna-kn** [comment]
"x" and _x_ without quotes is not the same. A quoted string creates a temporary variable using the default assumptions, while _x_ without quotes refers to a specific unknown variable (which by default also uses the default assumptions). Use replace(CALCULATOR->v_x, ...) for _x_ without quotes. In your case the end result will be the same.

**Comment by nick87720z** [comment]
Thanks.
My solution was to replace it to MathStructure("x"), just after symbolic expression is created.
