### ISSUE TITLE
Add Percent Change function

### ISSUE THREAD

**Issue by Vomet** [Qalculate/libqalculate#660]
Adding a percent change function would be a really nice addition to this calculator. Essentially, it could take in two values like so:

```
PercentChange(v_1, v_2)
```

Which will output the percent change between `v_1` and `v_2`.

Mathematically, that would like like this:

$$\frac{v_2-v_1}{v_1} \times 100 \%$$

Here are some sample inputs and outputs:

| Input | Output |
| --- | --- |
| `PercentChange(900,800)` | -11.11% |
| `PercentChange(500,600)` | 20% |
| `PercentChange(1200,1000)` | 16.67% |

**Comment by howaboutuser** [comment]
In qalculate-gtk
File>Percentage Calculation Tool
![圖片](https://github.com/Qalculate/libqalculate/assets/120489523/4320cc07-8068-4ef9-adab-e6bff8937e9b)

In qalc
> PercentChange():=(y-x)/x*100
> keep PercentChange
> PercentChange(1200,1000)

  PercentChange(1200, 1000) = -50/3 = approx. -16.66666667

**Comment by Vomet** [comment]
> In qalculate-gtk File>Percentage Calculation Tool ![圖片](https://private-user-images.githubusercontent.com/120489523/333229002-4320cc07-8068-4ef9-adab-e6bff8937e9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzY3NzQsIm5iZiI6MTcxNjc3NjQ3NCwicGF0aCI6Ii8xMjA0ODk1MjMvMzMzMjI5MDAyLTQzMjBjYzA3LTgwNjgtNGVmOS1hZGFiLWU2YmZmODkzN2U5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QwMjIxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjdmOThiZjc1YmM3NGVlODU1MTQ1ZWY1NjRhYTkwNjE4Y2M5MDRjODdhNmQ4YWEyMzZlNjdiZmFhMzE1NTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hMalNaIi9-ZstAFuUIq9ZMf-Isuo-Y0_0DLYTyZ4IaU)
> 
> In qalc
> 
> > PercentChange():=(y-x)/x*100
> > keep PercentChange
> > PercentChange(1200,1000)
> 
> PercentChange(1200, 1000) = -50/3 = approx. -16.66666667

Oh thanks! I'll close the issue now then.
