### ISSUE TITLE
some problem with variable n (integer)

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#661]
> set angle deg
> sin(x)=0.5 where 0<x and x<90  

  sin(x degrees) = 0.5 = approx.

  x = approx. 360.0000000n + 150.0000000 or
  x = approx. 360.0000000n + 30.00000000

1. I assume 0<x<90, so n=0. Is variable n necessary in result if and only if n=0?
2. Why x = approx. 360.0000000n + 150.0000000?

> set angle rad
> sin(x)=0.5 where 0<x and x<pi/2

  sin(x radians) = 0.5

  x = 2 pi * n + (5/6) * pi and n > -5/12 and n < -1/6 or
  x = 2 pi * n + pi / 6 and n > -1/12 and n < 1/6
Variable n is integer, why it output like this?

By the way, how to use variable n (integer) correctly?
> 2n<9

  ((2 * n) < 9) = (n < 9/2) = (n < 4.5)
I expect it return 4, I must misunderstand something.

**Comment by hanna-kn** [comment]
The handling of ("unknown") integer variables (including _n_) is simply incomplete.

`2n < 9` was simple to fix and will now return `n ≤ 4`.
`sin(x)=0.5 where 0<x and x<90` is more complicated to fix.

**Comment by hanna-kn** [comment]
`sin(x)=0.5 where 0<x and x<90` has now been fixed (returns `x = 30`).

**Comment by howaboutuser** [comment]
version:5.2.0
> set angle rad
> sin(x)=0.5 where 0<x and x<pi/2

  sin(x radians) = 0.5

  n = 0 and x = π / 6

**Comment by hanna-kn** [comment]
> version:5.2.0
> 
> > set angle rad
> > sin(x)=0.5 where 0<x and x<pi/2
> 
> sin(x radians) = 0.5
> 
> n = 0 and x = π / 6

Obviously the work with removal of _n_ was less complete than expected. The example has now been fixed.
