### ISSUE TITLE
Units missing: therm and thermie

### ISSUE THREAD

**Issue by UlyssesZh** [Qalculate/libqalculate#673]
I know I can define custom units, but these two seem common. My gas bill is measured in therms.

1 therm = 100000 BTU.
1 thermie = 1000 kcal.
https://en.wikipedia.org/wiki/Therm
https://en.wikipedia.org/wiki/Thermie

**Comment by hanna-kn** [comment]
Therm (in IT, ISO, and U.S. variants) and thermie units has now been added.
