### ISSUE TITLE
can not solve variable in trigonometric functions other than x y z

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#684]
> 1=sin("theta")

  1 = sin(theta radians)

  n = theta / (2π) − 1/4 ≈ 0.1591549431 theta − 0.2500000000

**Comment by hanna-kn** [comment]
Fixed.

This was caused by the priority order for variable isolation. The equation was solved for _n_ instead of "theta". `solve(1=sin("theta"))` works as expected.
