### ISSUE TITLE
can not convert mH₂O and inH₂O to Pa

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#686]
> 1 mH₂O to Pa                 

  error: Trailing characters "O" (not a valid variable/function/unit) in number "2O" were ignored.
  1 millihenry² = 0.001 H·g/(F·Pa·m)

> 1 inH₂O to Pa

  error: Trailing characters "O" (not a valid variable/function/unit) in number "2O" were ignored.
  1 inch·henry² = 25.4 H·g/(F·Pa)

**Comment by hanna-kn** [comment]
Fixed. (This is issue was only present in qalc, and not in any GUI.)
