### ISSUE TITLE
doesn't evaluate root with some arguments

### ISSUE THREAD

**Issue by nick87720z** [Qalculate/libqalculate#69]
For example. root(-8, 3) is ok, but root(-8, 2) doesn't evaluate even in approximate mode.
even for root(-2, 2)^3 - probably related to issue, with mission solving for fractional factors, as printed result is same - root(-2, 2)^3. There i don't get any errors, when doing in cli qalc.

Trying to run root with fractional (both decimal or rational) values, it gives error:
`Argument 2, Degree, in root() must be an integer >= 1`  

similar to fractional factors - fractional root factors could be decomposited, like:
root(x, n/m) => root(x^m, n) ; also ability to rearrange factors with root factors would improve further simplification.

Also for negative root factors:
root(x, -n) = x^(-1/n) = 1/x^(1/n) = 1/root(x, n)

**Comment by hanna-kn** [comment]
As mentioned in your previous issue, root() returns the real root. For root(-8, 2) no real root exists (the possible roots are 2.82i and -2.82i) and no result is returned in order to preserve the condition that root() is always real.
