### ISSUE TITLE
Wrong order of operations for implicit multiplication

### ISSUE THREAD

**Issue by avidseeker** [Qalculate/libqalculate#690]
```sh
$ echo '1/(2)(4)' | qalc
> 1/(2)(4)

  1 / (2 × 4) = 1/8 = 0.125
```

Expected: `1/(2)*(4) = 2`

See: [[1]](https://www.wolframalpha.com/input?i=1%2F%282%29%284%29), [[2]](https://www.google.com/search?q=1/%282%29%284%29)

**Comment by hanna-kn** [comment]
There is no strictly correct or incorrect behaviour in this case. There qalc will by default ask the user for the desired interpretation the first time an expression such as this is entered. The "conventional" mode, which do not differ between implicit and explicit multiplication, can also be selected using the command `set syntax 2`.

```
> 1/(2)(4)

Please select interpretation of expressions with implicit multiplication.

0 = Adaptive
1/2x = 1/(2x); 1/2 x = (1/2)x; 5 m/2 s = (5 m)/(2 s)

1 = Implicit multiplication first
1/2x = 1/(2x); 5 m/2 s = (5 m)/(2 s)

2 = Conventional
1/2x = (1/2)x; 5 m/2 s = (5 m/2)s

Parsing mode: 2

  (1 / 2) × 4 = 2
```

**Comment by avidseeker** [comment]
Oh, I see. For some reason, I didn't get the prompt for selecting the setting, and so I didn't know there was a setting for it.

**Comment by avidseeker** [comment]
Duplicate of #193.
