### ISSUE TITLE
Wrong conversion from 1/1ns to GHz?

### ISSUE THREAD

**Issue by sharkdp** [Qalculate/libqalculate#7]
That doesn't seem to be right:
```
$ qalc
> 1/1ns to GHz

  1 / (1 * nanosecond) = 1E18 GHz
```

should be: `1 GHz`.

I'm on version 0.9.9

**Comment by hanna-kn** [comment]
That is definitely not right. It has now been fixed.

**Comment by sharkdp** [comment]
Cool! Thank you very much for the quick fix.
