### ISSUE TITLE
I/O error : No such file or directory

### ISSUE THREAD

**Issue by megadr01d** [Qalculate/libqalculate#70]
On OS X 10.11, with `save_definitions_on_exit=1` set, when I `quit` or `exit` qalc interactive mode, I get:

```
I/O error : No such file or directory
I/O error : No such file or directory
I/O error : No such file or directory
I/O error : No such file or directory
I/O error : No such file or directory
I/O error : No such file or directory
I/O error : No such file or directory
I/O error : No such file or directory
```

For now, I've set `save_definitions_on_exit=0`, but is this repeating error message normal?

**Comment by hanna-kn** [comment]
I am not familiar with OS X, but my guess is that the ~/.local/share directory is missing (this should be fixed now).

**Comment by megadr01d** [comment]
Thanks, that was it. `~/.local/share` is not standard on OS X (unless a package creates it) so I created manually and everything is fine. Closing.
