### ISSUE TITLE
[Feature request] Using eng and sci to set scientific notation

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/libqalculate#701]
> help set exp

scientific notation (exp)
Determines how scientific notation is used (e.g. 5 543 000 = 5.543E6).
(0 = off, -1* = auto, -3 = engineering, 1 = pure, 3 = scientific, >= 0)

For example
>set exp eng
>set exp sci

I often forget how to spell the word, it will be convenient to type abbr. instead of whole word.

**Comment by hanna-kn** [comment]
Done. Although it seems easier to use a number instead.

**Comment by howaboutuser** [comment]
It's easier to use a number if you know what the number mean, otherwise it just a magic number.
(set ivdisp 2 #what does 2 mean? reading the manual...)
And most important, thanks.

**Comment by hanna-kn** [comment]
> It's easier to use a number if you know what the number mean, otherwise it is just a magic number.

In this case it means the maximum number of digits left of the decimal separator for display of numbers without scientific notation. A negative number (except -1) specifies the multiple used for the exponent (e.g. -3 for multiple of 3). Custom values are allowed.

**Comment by howaboutuser** [comment]
>A negative number (except -1) specifies the multiple used for the exponent (e.g. -3 for multiple of 3).

So the help message is wrong?`(0 = off, -1* = auto, -3 = engineering, 1 = pure, 3 = scientific, >= 0)`

**Comment by hanna-kn** [comment]
> > A negative number (except -1) specifies the multiple used for the exponent (e.g. -3 for multiple of 3).
> 
> So the help message is wrong? Custom values can be negative. `(0 = off, -1* = auto, -3 = engineering, 1 = pure, 3 = scientific, >= 0)`

Yes. The help message is misleading. A will update it.

> 
> ```
> > 0.00001 
> 
>   0.00001 = 1/100000
> 
> > set exp -3 
> 
>   1/100000 = 10E−6
> 
> > 0.001
> 
>   0.001 = 1/1E3
> ```
> 
> Sometimes it use negative exponent, sometimes not, why?

In the case when negative exponent is not used, the value is displayed as a fraction. When the input expression is a single decimal number, the result will by default be displayed as a mixed fraction. I've now modified this behaviour to not apply when the result is otherwise displayed using scientific notation.

**Comment by howaboutuser** [comment]
```
> set exp -3
> 0.001

  0.001 = 1/1E3

> set negexp on

  1/1E3 = 1E−3

> help set negexp

show negative exponents (negexp)
Use negative exponents instead of division for units in result (m/s = m*s^-1).
(0 = off, 1* = on)
```
Should negexp be under "Units" category? It not only apply to unit.

**Comment by hanna-kn** [comment]
> Should negexp be under "Units" category? It not only apply to unit.

`1/1E3 = 1E−3` is not caused by the negexp change. The automatic fraction state is not applied in this case when an option has changed.
```
> set exp -3
> 0.001

  0,001 = 1/10³

> set negexp on

  1/10³ = 10^−3

> 0.001

  0,001 = 1/10³

> 0.25

  0,25 = 1/4

> set negexp off

  1/4 = 250 × 10^−3
```

**Comment by howaboutuser** [comment]
>In the case when negative exponent is not used

Is it controllable?

**Comment by hanna-kn** [comment]
> > In the case when negative exponent is not used
> 
> Is it controllable?

It is controllable using the fraction (fr) option (or `to decimal`/`to fraction`). The above examples are however a special case, when a single decimal number, without any calculation, is entered (repeating of the exact expression in the result is generally avoided).
