### ISSUE TITLE
Strange unit when using years

### ISSUE THREAD

**Issue by JennToo** [Qalculate/libqalculate#702]
When I do a unit conversion into years, for some reason it shows up as a unit called `a_j`. Not sure what that is, maybe some kind of physic-y thing?

```
jwilco7670l ~ $ qalculate.qalc 
> 1 day -> year

  1 day ≈ 0.002737850787 a_j

jwilco7670l ~ $ qalculate.qalc -v
5.2.0
```

Not a big problem, once I figured out what was happening it was easy enough to substitute mentally. Figured I'd report it anyways though. Also I love Qalculate! Definitely the best calculator I've ever used by far

**Comment by hanna-kn** [comment]
a<sub>j</sub> is the abbreviation for Julian year (365.25 days). The default abbreviation was changed in version 4.9 to make it clearer which year definition is used (Gregorian year a<sub>g</sub> = 365.2425 days, Tropical year a<sub>t</sub> = 365.24219 days).

**Comment by JennToo** [comment]
oh! that makes a lot of sense, I guess I've been playing fast and loose with what I mean by "year" when I use it in my math 😅
