### ISSUE TITLE
Add 'nautical mile' unit

### ISSUE THREAD

**Issue by redfast00** [Qalculate/libqalculate#704]
See https://en.wikipedia.org/wiki/Nautical_mile. The current `nmi` unit gets interpreted as nanomiles, which is not that useful of a unit anyways.

**Comment by hanna-kn** [comment]
There is already a nautical mile unit. I've now added the _nmi_ symbol to unit.

```
> help NauticalMile

Unit:                           Nautical Mile
Names:                          NauticalMile / NauticalMiles
Base Unit:                      m
Relation:                       1852
```

**Comment by redfast00** [comment]
Thank you!
