### ISSUE TITLE
Update documentation for `use_unicode_signs` 

### ISSUE THREAD

**Issue by jherkenhoff** [Qalculate/libqalculate#705]
The field `use_unicode_signs` in `PrintOptions` used to be a boolean, but now apparently is an integer. In the documentation it is still treated as a boolean. Unfortunately I dont know the meaning of this integer value, otherwise I would have just updated the documentation myself.

**Comment by hanna-kn** [comment]
Done.

Boolean values are still supported, but there are now additional values that limit the use of Unicode exponents for non-HTML output.

**Comment by jherkenhoff** [comment]
Thanks a lot for the update and the very quick response!
