### ISSUE TITLE
Calling plot([]) crashes libqalculate

### ISSUE THREAD

**Issue by stephtr** [Qalculate/libqalculate#712]
Calculating the plot function with an empty vector (so nothing to plot at all) crashes libqalculate with an memory access out of bounds exception. Qalculate then silently exits.

To reproduce:
* Just enter `plot([])` into qalc or qalculate

I know this is an edge case, but it becomes relevant for calculate-as-you-type applications, since it gets already triggered by just the opening bracket `plot([`

**Comment by hanna-kn** [comment]
Fixed.

**Comment by stephtr** [comment]
Thanks, awesome :)
