### ISSUE TITLE
How to do currency conversion and get currency rates and new currency in qalculate

### ISSUE THREAD

**Issue by shirishag75** [Qalculate/libqalculate#72]
I am unable to figure out how to use the currency conversion, get the exchange rate and ask for new currency in qalculate. For instance I want to have Taiwanese Dollar (TWD) in qalculate if possible. It doesn't seem to be in qalculate.

**Comment by hanna-kn** [comment]
TWD conversion is already supported (since version 2.1.0). I did however discover that the new currencies where omitted from the list in the conversion tab (this has now been fixed). Expressions similar to `100 TWD to €` should work.

**Comment by shirishag75** [comment]
I do get the 100 TWD to Euro but not the other two options that you have talked about.

**Comment by hanna-kn** [comment]
Do you not see "Taiwan" under Edit->Convert to Unit->Currency->more and in the list of Edit->Manage Units? Not all currencies were displayed in the "to"-button menu (this has not been changed by using the same structure as for the currency button menu, for conversion of currency unit).

**Comment by shirishag75** [comment]
I am right now waiting for the maintainer to pull the binary to experimental to test it again and then will get back to you, sorry to leave you hanging like this.

**Comment by hanna-kn** [comment]
Which version of Qalculate! are you using?

Qalculate! fetches 32 exchanges rates from the European Central Bank (https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml), Bitcoin rate from Coinbase (https://api.coinbase.com/v2/prices/spot?currency=EUR), and over 100 additional exchange rates from mycurrency.net (https://www.mycurrency.net/=US). In addition a few obsolete currencies are supported.

The mycurrency.net source has recently changed and requires version 2.6.

The libcurl4-nss-dev Ubuntu package does not function properly and will result in failure to download exchange rates (issue #100).

**Comment by azizsayfiddin** [comment]
From cryptocurrencies, why only BTC? Why not include other cryptocurrencies like Monero (XMR), Litecoin, or ETH?

**Comment by 621625** [comment]
I second this. Please include those cryptos and more.
