### ISSUE TITLE
planck2pi and affect on derived quantities

### ISSUE THREAD

**Issue by drjamesbateman** [Qalculate/libqalculate#724]

**Comment by hanna-kn** [comment]
Why did you remove the description?
Did you discover that it was not correct, and if so should this issue closed?

**Comment by drjamesbateman** [comment]
I tried to reproduce the issue on a fresh PC and it did not persist.  Therefore, this seemed to be more of a support issue than a bug.  I tried to delete the issue, to avoid adding noise, but could not figure out how.
