### ISSUE TITLE
libqalculate-5.4.0+ fails to build without libreadline

### ISSUE THREAD

**Issue by ixlandia** [Qalculate/libqalculate#726]
When building libqalculate without libreadline, build fails as function do_autocalc() is not defined.

libqalculate/src/qalc.cc - Function AutoCalcThread::run() (2791-2797) is defined OUTSIDE of a #ifdef HAVE_LIBREADLINE block despite function do_autocalc() being defined INSIDE said block (641-654). Without digging further, it seems that AutoCalcThread::run() should not be defined without libreadline either.

**Comment by hanna-kn** [comment]
Fixed.
