### ISSUE TITLE
Add localization option

### ISSUE THREAD

**Issue by ManuelSchneid3r** [Qalculate/libqalculate#73]
I could not find an option to set the localization of the parser. Is this feature planned, or does it exist already?

I want to make the calculator to accept strings using the local decimal and group separator. E.g.
`0,2+1.000.000`

**Comment by hanna-kn** [comment]
The Qalculate! applications follows the system locale (LC_NUMERIC for decimal separator). By default no group separators (except whitespace characters) are allowed, but this can changed using the "comma as separator" and "dot as separator" options.

To enable local decimal and group separators when using libqalculate you must use `Calculator::unlocalizeExpression(string, ParseOptions)` on the input string, with dot_as_separator/comma_as_separator set to true in ParseOptions. You can set the decimal separator independently from LC_NUMERIC by using `Calculator::useDecimalComma()` and `Calculator::useDecimalPoint()` (the latter must be called with true as argument, to enable comma as group separator).

**Comment by ManuelSchneid3r** [comment]
Okay I guess I have two bugs then:
1. ```
    manuel@argon ~ $ locale
    LANG=de_DE.utf8
    LC_CTYPE="de_DE.utf8"
    LC_NUMERIC="de_DE.utf8"
    LC_TIME="de_DE.utf8"
    LC_COLLATE="de_DE.utf8"
    LC_MONETARY="de_DE.utf8"
    LC_MESSAGES="de_DE.utf8"
    LC_PAPER="de_DE.utf8"
    LC_NAME="de_DE.utf8"
    LC_ADDRESS="de_DE.utf8"
    LC_TELEPHONE="de_DE.utf8"
    LC_MEASUREMENT="de_DE.utf8"
    LC_IDENTIFICATION="de_DE.utf8"
    LC_ALL=
    ```
    But I dont get comma as separator. This applies to Qalqulate-gtk too. 
2. Calculator::useDecimalComma() does _not_ work. I tried it. Nothing changed.

**Comment by hanna-kn** [comment]
1. Which version of Qalculate!, distribution/operating system, and desktop environment are you using?
`LC_NUMERIC="de_DE.utf8" qalculate-gtk` works as expected when I test it on Arch Linux/Xfce with Qalculate! compiled from source, and with the snap package on both Ubuntu 16.04 and 17.10 (with gnome and kde) using en_US/en_GB as system locale. 

2. It should work. The code in the function is the exact same as when locale uses comma as decimal separator. It would be helpful if I could see your code.

Note that by default, dots will, in addition to comma, still be interpreted as a decimal separator.

**Comment by ManuelSchneid3r** [comment]
Okay thats pretty confusing. When I run my app using QtCreator's debugger the locale is not set. This also applies for applications launched by this instance of the launcher. Well when I run it from terminal everything is fine. Sorry for disturbing you and thank you for this awesome library. :+1:

**Comment by ManuelSchneid3r** [comment]
> Note that by default, dots will, in addition to comma, still be interpreted as a decimal separator.

This is weird, but actually nice if the group separators are completely disabled. How can I disable them?
```
CALCULATOR.parse_options.dot_as_separator = false;
CALCULATOR.parse_options.comma_as_separator = false;
```

… didnt change anything.

![auswahl_005](https://user-images.githubusercontent.com/3252315/37967281-2bc5a6b8-31cb-11e8-8b95-3aee1639237e.jpg)

![auswahl_004](https://user-images.githubusercontent.com/3252315/37967264-1f879776-31cb-11e8-8cb1-59de5cb43693.jpg)

**Comment by hanna-kn** [comment]
When comma is used as decimal separator, if ParseOptions::dot_as_separator is true, all dots are ignored, and if dot_as_separator is false dots and commas will treated exactly the same (in order to allow easy input of common "international" numbers). unlocalizeExpression() replaces commas with dots, which are used internally as decimal separator, but if dot_as_separator is true all dots will first be removed. These options have no effect on output (controlled by PrintOptions::digit_grouping).

The result might be a bit confusing if dot_as_separator is false and a number contains both dots and commas.

If dot as used as decimal separator the logic is complicated by the fact that comma is then by default used as function argument and vector/matrix element separator.

**Comment by ManuelSchneid3r** [comment]
Okay this is weird, but it sounds like a reasonable tradeoff.

I have to say that the API is sometimes confusing. E.g. separator should imho. Its ambigious since one does not know if group or decimal separators are meant.

**Comment by hanna-kn** [comment]
I am well aware of how bad the API is, with many inconsistencies, exposure of functions and properties only intended for internal usage and constant ABI breakages. libqalculate was originally only intended for use with qalculate-gtk (and the abandoned qalculate-kde), but suddenly I discovered that it was used by KDE and other projects (often in a less than optimal way), which made radical API changes much more problematic (and still kind of boring).

It would be easy to check if both dots and commas are used and in that case always ignore the dots, but then it would be confusing that 1.235,00 equals 1235, while 1.235 equals 1,235.
