### ISSUE TITLE
security implications for using on an open server

### ISSUE THREAD

**Issue by griffintuckerau** [Qalculate/libqalculate#730]
how do i compile the most basic version of qalc with the absolute minimal library usage, so that only basic calculations are enabled, such as addition and subtraction with variables?

then if i wanted division and multiplication added, how would i compile that?

are there security implications for using variables ( keep ?) on an open server?

**Comment by hanna-kn** [comment]
It is not possible to disable features, without modifying the code or data files, with the exception of support for gnuplot (`--without-gnuplot-call`), and command, load, and export functions, and uptime variable (`--disable-insecure`). It is possible to compile libqalculate and qalc without readline, icu, and libcurl.

> are there security implications for using variables ( keep ?) on an open server?

Not unless you allow saving of user definitions to file (which assume would be not be worse than allowing saving of history and preferences).
