### ISSUE TITLE
Non-interactive download of exchange rates broken

### ISSUE THREAD

**Issue by mcepl** [Qalculate/libqalculate#732]
If in the rejected pull request (#454, still don’t know why), I was updating exchange rates with the command `/usr/bin/qalc -e`. It doesn’t work any more, because `-e` is not considered an expression and `qalc` immediately goes to the interactive mode. I have to run this bizarre command `echo exrates|qalc -f -` to achieve the same effect.

Could you, please, either return the original behaviour or at least suggest some command which would just update exchange rates database, please?

**Comment by hanna-kn** [comment]
The behaviour of `qalc -e` has not changed. There are other options to avoid non-interactive mode (e.g. `qalc -e -l`).

My recommendation is however to let Qalculate update exchange rates only when needed. Automatic daily updates (when an exchange rate is actually used) in qalc can be enabled using `set update exchange rates 1` (or `set upxrates 1`).

**Comment by mcepl** [comment]
I see.
