### ISSUE TITLE
Feature request: `stamptodatetime` function that can also show time

### ISSUE THREAD

**Issue by maximbaz** [Qalculate/libqalculate#74]
The available function `stamptodate` completely ignores the time part of the timestamp.

I'd like to have a new function like `stamptodatetime` that can show in addition to the date also the hours, minutes and seconds of the timestamp.

Gotchas:
- Time format, I suggest `2013-02-08 09:30:26`
- Time zone, I suggest UTC
- Precision, often timestamps are in seconds (e.g. `1522274654`), but sometimes they are in milliseconds or even in nanoseconds (golang). This probably deserves a separate feature request, but `qalc` should correctly guess the precision based on the number of digits in the string.

**Comment by hanna-kn** [comment]
It should be relatively easy to do. I do not however agree that precision should be guessed, since Qalculate! supports extreme dates. I think its better to simply support units in the function, which would mean that any time unit and prefix can be used.

This might be a good time for me to add a proper date data type (or rather convert date strings to seconds), which would allow expressions such as "1970-01-01" + 1522274654 ns. The tricky part will probably be result presentation selection and time zone handling.

**Comment by maximbaz** [comment]
> I think its better to simply support units in the function, which would mean that any time unit and prefix can be used.

Even better! Because yes, I agree, guessing does not always lead to the correct result.

> You can actually already calculate `1970 years + 1235435323424 ms to years` (= "2009 years + 54 d + 6 h + 28 min + 43.424 s").

Neat trick, but unfortunately it doesn't show the date (shows `54d`), so I need to use `stamptodate` to get the date out of timestamp and then this trick to get the time.

**Comment by hanna-kn** [comment]
> Neat trick, but unfortunately it doesn't show the date (shows 54d), so I need to use stamptodate to get the date out of timestamp and then this trick to get the time.
And it actually gives the wrong time (in most cases), since the year unit equals 365.25 days.

**Comment by hanna-kn** [comment]
I've now changed to stamptodate() function to return both date and time. 

I've also made direct date calculations possible (e.g. `"1970-01-01"+1522575477s = 2018-04-01T09:37:57Z`). This still needs some work (particularly time zone handling).

**Comment by maximbaz** [comment]
Thanks! I've also given it a test run, here are some of my notes and questions 🙂

- `stamptodate(1522581779) = 2018-04-01T11:22:59Z` - 👍 
- `stamptodate(1522581780) = 2018-04-01T11:23Z` - I feel like you shouldn't omit seconds, keep `:00Z`
- `"1970-01-01" + 1522581779s  = 2018-04-01T11:22:59Z` - 👍 
- `timestamp() = 1522540800` - doesn't account for time
- ` stamptodate(timestamp()) = 2018-04-01T00:00Z` - thus also doesn't account for the time
- `"1970-01-01" + 1522581779000ms = 2018-04-01T11:22:59Z` - 👍 
- `"1970-01-01" + 1522581779000000000ns = 2018-04-01T11:22:59Z` - 👍 
- are you planning to add precision as a parameter to `timestamp()` and `stamptodate`, like below?
    - `timestamp("ms") =  1522581779000`
    - `stamptodate(1522581779000, "ms") = 2018-04-01T11:22:59Z`
- when you say "this needs time zone handling", do you want to add timezone as a parameter to `stamptodate`, like below?
    - `stamptodate(1522581779000, "ms", "CET") = 2018-04-01T13:22:59 CET"`

**Comment by hanna-kn** [comment]
> timestamp() = 1522540800 - doesn't account for time

 timestamp() is work in progress. 

> are you planning to add precision as a parameter to timestamp() and stamptodate, like below?

I do not think that a higher precision return value would be very useful.

> "1970-01-01" + 1522581779000ms = 2018-04-01T11:22:59Z

`"1970-01-01" + 1522581779000ms = 2018-04-01T11:22:59Z` might actually be considered wrong as it ignores leap seconds.

> when you say "this needs time zone handling", do you want to add timezone as a parameter to stamptodate, like below? 

The ideas is that stamptodate() and other functions always should return a time zone neutral value. The displayed time zone should be determined by result display settings. This is primarily an issue for expressions such as `"2018-04-01" - 12332409 hours` where it is probably safe to assume that the date is specified for the local time zone, but the historical local time offset may be different for the final result (and should follow the same setting as when stamptodate() is used).

**Comment by maximbaz** [comment]
> > are you planning to add precision as a parameter to `timestamp()`
>
> I do not think that a higher precision return value would be very useful.

I would say it's quite useful sometimes, but not super important. 

For example, I was recently developing a golang app that works with time series, and while in development I had some timestamp values (which golang provides in nanoseconds) that I had to convert back and forth to meaningful datetime strings to verify the logic. This required me to constantly pad the result of `timestamp()` with nine zeros and remove the last 9 digits of golang's timestamp before putting it through `stamptodate()`.

> `"1970-01-01" + 1522581779000ms = 2018-04-01T11:22:59Z` might actually be considered wrong as it ignores leap seconds.

Interesting thought, so the output of `"1970-01-01" + 1522581779s` and `stamptodate(1522581779)` is expected to be different, because according to wiki the unix timestamp does not contain leap seconds.

**Comment by hanna-kn** [comment]
`timestamp([date, ]"ns")` does not seem more efficient than `timestamp([date])*1e9`, `timestamp([date])*s/ns` or `timestamp([date])s to ns`, and it gives the impression of return value with higher precision than available.

`"1970-01-01" + 1522581779s` now equals `2018-04-01T11:22:32`, while `stamptodate(1522581779)` equals `2018-04-01T11:22:59`, if time zone is UTC (local time is now returned and parsed by default, unless `to utc` is appended to the expression, and a time zone is specified in the time string)

**Comment by maximbaz** [comment]
> timestamp([date, ]"ns") does not seem more efficient than timestamp([date])*1e9, timestamp([date])*s/ns or timestamp([date])s to ns, and it gives the impression of a return value with higher precision than available.

These examples are good, what do you recommend for `stamptodate()` function when I have a timestamp value of `1522753887854765925` that I want to parse?

---

Wow, thanks for the trick with `to utc`, that is useful!

**Comment by hanna-kn** [comment]
> These examples are good, what do you recommend for stamptodate() function when I have a timestamp value of 1522753887854765925 that I want to parse?

`stamptodate(1522753887854765925ns)` or `stamptodate(1522753887854765925/1e9)`, or why not create your own convenient function (`function stdns stamptodate(\x/1e9)`)

**Comment by maximbaz** [comment]
`stamptodate(1522753887854765925ns)` - I did not realize it's that simple! Nice!

Well, then from what I see, everything what I wanted is already implemented, and even more! Huge thanks!

Looking forward for the new official release with all these improvements 😉
