### ISSUE TITLE
Feature request: change how the percentages are calculated in simple operations

### ISSUE THREAD

**Issue by juanfra684** [Qalculate/libqalculate#75]
I really like qalculate-gtk but there is an annoying "problem" with the percentages. When I write `100+20%` or `100-20%` the result are calculated using 1 as base for the percentage instead of 100, so the results are `100.20` and `99.8`. That's pretty common in scientific hand calculators but the more financial oriented calculators do the right thing (imho) here, they use the previous number to calculate the percentage, i.e. the results would be `120` and `80`.

If possible, I would like a change to make libqalculate to calculate the percentages using the previous number in simple operations.

**Comment by hanna-kn** [comment]
Done.

**Comment by juanfra684** [comment]
Thanks a lot for the quick fix! :D
