### ISSUE TITLE
Change function parameter separator

### ISSUE THREAD

**Issue by palmenros** [Qalculate/libqalculate#76]
I am a native spanish speaker. However, I am very used to with using commas to separate parameters in a function: `diff(2xy, y)` instead of `diff(2xy; y)`. However, I need my excels formulae to be in the latter form (high school requirements). Is there any option to change this only in qalculate?
If I type for example `diff(x)`, qalc says: `diff(x; x; 1) = 1`, and I expect `diff(x, x, 1) = 1`, as it is in my other computers and in Linux, where the language is set to English. I have only tested it in Windows, where it happens as I say.
Thanks

**Comment by hanna-kn** [comment]
For languages which uses comma as decimal separator, it is not possible to also use comma as separator for function parameters. I have now made it possible for the user to disable use of comma as decimal separator (which consequently allows comma to be used as function argument separator).
