### ISSUE TITLE
Segmentation fault when `omega`

### ISSUE THREAD

**Issue by elisaado** [Qalculate/libqalculate#79]
Hi, I came across this issue accidentally,
when in `qalc`, typing `omega` makes it segfault.

```
eli@probook ~ % qalc
> omega
[1]    6944 segmentation fault (core dumped)  qalc
```

Qalc version 2.3.0

**Comment by hanna-kn** [comment]
This is no doubt caused by issue #77 (omega is defined as `lambertw(1)`), which has been fixed (a new version will be released this week).
