### ISSUE TITLE
[Windows] [2.4.0 regression] Segfault on start of qalc.exe and qualculate.exe

### ISSUE THREAD

**Issue by genodeftest** [Qalculate/libqalculate#82]
Today I updated qalculate on Windows from version 2.2.1 to 2.4.0. Since this update, any time I start Qalculate, it crashes immediately.  These are the windows error report files: [WERFBCB.tmp.WERInternalMetadata.xml.txt](https://github.com/Qalculate/libqalculate/files/1907126/WERFBCB.tmp.WERInternalMetadata.xml) (rename to XML which is not supported by GitHub), [WER11AC.tmp.appcompat.txt](https://github.com/Qalculate/libqalculate/files/1907128/WER11AC.tmp.appcompat.txt), [WER141D.tmp.mdmp.zip](https://github.com/Qalculate/libqalculate/files/1907131/WER141D.tmp.mdmp.zip)

Also, running qalc.exe fails too:
```
$ ./qalc.exe "2+4-7"
Segmentation fault
```
on the other hand, `qalc.exe --help` and `qalc.exe --version` work fine.

These versions were tested and work fine: 2.1.0, 2.2.0, 2.2.1, 2.3.0.

After removing 2.4.0 and reinstalling it, the issue is still present. The installer log file `%APPDATA%\..\Local\Temp\MSI[5-digit hex].LOG` summary:
```
=== Protokollierung beendet: 2018-04-13  13:46:42 ===
MSI (c) (6C:C8) [13:46:42:838]: Note: 1: 1707 
MSI (c) (6C:C8) [13:46:42:838]: Note: 1: 2262 2: Error 3: -2147287038 
MSI (c) (6C:C8) [13:46:42:838]: Note: 1: 2262 2: Error 3: -2147287038 
MSI (c) (6C:C8) [13:46:42:838]: Produkt: Qalculate! -- Die Installation wurde erfolgreich abgeschlossen.

MSI (c) (6C:C8) [13:46:42:838]: Das Produkt wurde durch Windows Installer installiert. Produktname: Qalculate!. Produktversion: 2.4.0. Produktsprache: 0. Hersteller: Hanna Knutsson. Erfolg- bzw. Fehlerstatus der Installation: 0.

MSI (c) (6C:C8) [13:46:42:838]: Grabbed execution mutex.
MSI (c) (6C:C8) [13:46:42:838]: Cleaning up uninstalled install packages, if any exist
MSI (c) (6C:C8) [13:46:42:838]: MainEngineThread is returning 0
=== Verbose logging stopped: 2018-04-13  13:46:42 ===
```

Operating system:
Windows 7 Enterprise 64Bit

**Comment by genodeftest** [comment]
Workaround: Downgrade to 2.3.0 or any previous version.

**Comment by hanna-kn** [comment]
Fixed. The [Windows binary](https://github.com/Qalculate/libqalculate/releases/download/v2.4.0/qalculate-2.4.0a.msi) has been updated.

**Comment by genodeftest** [comment]
Works fine, thank you for the quick fix!
