### ISSUE TITLE
Use two's complement to represent negative numbers when number base is binary 

### ISSUE THREAD

**Issue by Serphentas** [Qalculate/libqalculate#85]
Right now, -1 is represented as -0001 (binary) whereas it should be 1111 (two's complement of 0001).

There should be an option to select how to display negative numbers when binary format is used.

**Comment by hanna-kn** [comment]
Done (although I still need to add the option to disable it in the user interfaces). 

For input of negative number using two's complement representation bin() must be used with the the second argument set to 1.

**Comment by Serphentas** [comment]
Awesome, thanks !
