### ISSUE TITLE
magnetic_constant is missing a factor pi

### ISSUE THREAD

**Issue by felixbuettner** [Qalculate/libqalculate#86]
The vacuum permeability magnetic_constant should be 4e-7 pi Vs/Am. However, the factor pi is missing in the stored constant:

magnetic_constant/(10^−7×(Vs)/(Am)) gives 4 as result.

**Comment by hanna-kn** [comment]
This issue was fixed in version 2.2.1 (it was only present in 2.2.0 and was related to issue #55).
Please let me know if you are using a version > 2.2.0, otherwise you should upgrade to the current version (2.4.0).

**Comment by felixbuettner** [comment]
Indeed, I have version 2.2. I have upgraded to 2.4 and the problem is solved.
