### ISSUE TITLE
GTK GUI

### ISSUE THREAD

**Issue by Magnus512** [Qalculate/libqalculate#9]
I'm trying to install the gui but it requires 0.9.11 version, how it is possible ?

**Comment by hanna-kn** [comment]
If you wish to install the latest development version (from git) of qalculate-gtk you must also install the development version of libqalculate, otherwise you should install qalculate-gtk version 0.9.9 (https://github.com/Qalculate/qalculate-gtk/releases/download/v0.9.9/qalculate-gtk-0.9.9.tar.gz).

**Comment by Magnus512** [comment]
@hanna-kn I did it, but requires libqalculate 0.9.11, I used the git version for libqalculate, and the git version for the gui

**Comment by hanna-kn** [comment]
The git version has version number 0.9.11. Perhaps the problem is that libqalculate(.pc) is not in your pkg-config path. In that case youu need to specify the pkg-config path when running configure (`PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure`).

**Comment by Magnus512** [comment]
@hanna-kn thanks
