### ISSUE TITLE
Roman numeral interconversion

### ISSUE THREAD

**Issue by majumeke** [Qalculate/libqalculate#93]
currently Qalculate! can return arabic numerals from roman numerals. could it be possible to enable Qalculate! to do the reverse i.e convert arabic numerals to roman numerals ?

Continued Thanks for your work on Qalculate!

**Comment by hanna-kn** [comment]
Roman numerals can be converted both ways. Select roman "number base" to display the result using roman numerals. 

I've now also added the option to type "to roman" (as well as "to sexagesimal" and to "to time") in the expression (which reminds me that I should add completion for "to" commands).

**Comment by majumeke** [comment]
ah found the "number base" option and i also appreciate the option to type "to roman" to carry out this conversion. however, and i'm sorry for not being specific, i was also referring to the dialog found under Functions>Miscellaneous>Roman Number

![roman](https://user-images.githubusercontent.com/26199366/40629517-51c519fe-62d4-11e8-91be-e3e00d02d29f.png)

i'd appreciate it if the conversion could also be done both ways from within this dialog box too.

**Comment by hanna-kn** [comment]
All dialogs under the Functions menu are automatically generated for easy (but inefficient) entry of functions. The roman() function interpret the specified expression using the Roman numerals "base" (without forcing the user to change the number base for the whole and subsequent expressions).

I've now changed the roman() function to return a Roman number text string if the passed expression only contains decimal digits and operators. (This will be an intentionally hidden feature).

I've considered adding Roman numerals (and other missing bases) to the base conversion dialog, but for most users this would only make the dialog more cluttered.

**Comment by majumeke** [comment]
> All dialogs under the Functions menu are automatically generated for easy (but inefficient) entry of functions. The roman() function interpret the specified expression using the Roman numerals "base" (without forcing the user to change the number base for the whole and subsequent expressions).

interesting, appreciate the information.

> I've now changed the roman() function to return a Roman number text string if the passed expression only contains decimal digits and operators. (This will be an intentionally hidden feature).

Thank you. though may i ask why it will be intentionally hidden ? also since the dialogs under the function menu are automatically generated will the decimal to roman conversion now work in the Roman Number dialog ? and if so wouldn't it be clearer to rename the dialog Roman<>Decimal ?

> I've considered adding Roman numerals (and other missing bases) to the base conversion dialog, but for most users this would only make the dialog more cluttered.

this is just my opinion but i think/hope that you go for completeness by adding those bases to the base conversion dialog. this will be especially useful for new users. a compromise could be reached by using such features as dropdown menus or searchable lists to declutter the dialog and also to make those bases more visible to a new user.

**Comment by hanna-kn** [comment]
> Thank you. though may i ask why it will be intentionally hidden?

It goes against the principles of how functions in Qalculate! should work. The roman() function normally interprets an expression with roman numerals and returns a base-independent value which can be used for further calculations. When the roman() function instead returns a fixed-base text string no further calculations can be done (except string manipulations). Text string values should be avoided as much as possible and how values are presented should be decided after the expressions has been fully evaluated (which is why there for example are no factorization or unit conversion functions). 

> this is just my opinion but i think/hope that you go for completeness by adding those bases to the base conversion dialog. this will be especially useful for new users. a compromise could be reached by using such features as dropdown menus or searchable lists to declutter the dialog and also to make those bases more visible to a new user.

I thought that the big drop-down menu on the keypad would be apparent enough for new users. I did however decide to simple add duodecimal base and Roman numerals the number bases conversion dialog. It shouldn't add too much clutter.

**Comment by majumeke** [comment]
have tested out the inter-conversion in version 2.6 and as promised i can now convert between roman and arabic numerals by using both the roman() function and also the "Roman Number" dialog. 
Thank you very much for considering and implementing this feature, Qalculate! is quickly becoming a one stop shop for calculations and conversions for me. this issue can be marked as closed.

**Comment by majumeke** [comment]
sorry to reopen this one, but the hidden inter-conversion feature in the Roman Number dialog takes only text and not both text and numbers as it was in version 2.6 in the latest versions(2.6.2, 2.8.0). could you please take a look at this one again ?

**Comment by hanna-kn** [comment]
There is no difference whatsoever in the Roman number function or dialog between version 2.6.0 and version 2.8.0. The entered number will be read as a text string, but if it contains decimal numerals, it will be converted to a number and a Roman number will be returned. I still recommend use of the number bases dialog instead (or the "to roman" syntax).

**Comment by majumeke** [comment]
odd, this is what i get when i try to convert 2014 to roman via the dialog.

![roman](https://user-images.githubusercontent.com/26199366/47853434-c5304f80-ddef-11e8-9009-e3d1bb4570f4.png)

**Comment by hanna-kn** [comment]
That unfortunately did not work in the previous versions either (zeroes weren't allowed). This has now been fixed.

**Comment by majumeke** [comment]
as always, thank you for the quick response. it was my bad in not testing this feature thoroughly.
