### ISSUE TITLE
Number::absIsGreaterThan() and Number::absIsLessThan() are not implemented

### ISSUE THREAD

**Issue by dschopf** [Qalculate/libqalculate#94]
The documentation and the header file indicate that Number::absIsGreaterThan() and Number::absIsLessThan() should be available. However, when linking there are no such functions available in the dynamic library and also the source is missing the implementations for these functions.

**Comment by hanna-kn** [comment]
I've now removed the functions from the header file (they will be automatically removed from the documentation when regenerated).
