### ISSUE TITLE
i=-i

### ISSUE THREAD

**Issue by vvs-** [Qalculate/libqalculate#98]
Something's wrong with solving these equations in exact mode:

e^(i*x)=-i
cis(x)=-i

**Comment by hanna-kn** [comment]
Fixed. 
ln(-i) returned the wrong result.
(It is still however problematic that only the real solution is returned, even if x is not assumed real.)

**Comment by vvs-** [comment]
BTW, could default cartesian form be changed if desired? In fact, the only way of converting the representation that I came up with were equations similar to those above.

**Comment by hanna-kn** [comment]
Is it the polar/exponential form you're after?
In that case, you can simply use `abs(z)` (usually denoted by _r_) and `arg(z)` (_θ_), for complex number _z_. 
`abs(z) * e^(i * arg(z)) = abs(z) * (cos(arg(z)) + i * sin(arg(z))) = z` (which means that arg(-i) returns the correct principal solution to e^(i*x)=-i).
I'm however not really familiar with complex numbers.

**Comment by hanna-kn** [comment]
Is it the polar/exponential form you're after?
In that case, you can simply use `abs(z)` (usually denoted by _r_) and `arg(z)` (_θ_), for complex number _z_. 
`abs(z) * e^(i * arg(z)) = abs(z) * (cos(arg(z)) + i * sin(arg(z))) = z` (which means that arg(-i) returns the correct principal solution to e^(i*x)=-i).
I'm however not really familiar with complex numbers.

**Comment by vvs-** [comment]
Yep, that would work too. I've just sought for an easier way to convert the whole result, similar to other conversion features. Thanks anyway.

**Comment by vvs-** [comment]
Thanks for all your efforts put into this.

BTW, calling it a calculator isn't fair anymore. It's much closer to a general purpose CAS now that calculus is implemented. In fact, using expression tree at the lowest level warrants that it's in a different weight category than any calculator with just arbitrary precision arithmetic. I suppose you just don't want to scare arbitrary users from thinking that it's too complicated for everyday use. And indeed it's as simple as a desktop calculator.

**Comment by vvs-** [comment]
Thanks! The pace of improvement is really fast.
